apiVersion: jumo.dev/v1
kind: ConnectorIntegration
metadata:
  id: google-home-integration
  namespace: dev.jumo.connectors
  name: Google Workspace Home Integration
spec:
  ownerRealm: home
  category: PRODUCTIVITY
  memberConnectorRefs:
    - kind: ConnectorPackage
      namespace: dev.jumo.connectors
      id: google-workspace
  description: Google Workspace integration for calendar and document access
