apiVersion: jumo.dev/v1
kind: ConnectorPackage
metadata:
  id: google-workspace
  namespace: dev.jumo.connectors
  name: Google Workspace Connector
spec:
  connectorId: google-workspace
  version: 1.0.0
  packageDigest: sha256:e9e87ed6b889d52a325a701eb3dcecc2281ffe6d29ae45a07932518ee993d23f
  manifestPath: .jumo/connector-packages/google/package.yml
  requiresAdapter: false
