apiVersion: jumo.dev/v1
kind: ConnectorPackage
metadata:
  id: google-workspace
  namespace: dev.jumo.connectors
  name: Google Workspace Connector
spec:
  connectorId: google-workspace
  version: 1.0.0
  packageDigest: sha256:517272dd1d9ff1b0b46b35e9543c500ff8f720db91d700e0451d40e8e2fb6dc7
  manifestPath: .jumo/connector-packages/google/package.yml
  requiresAdapter: false
