// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum AccessMode {

  PLAN_DIRECT("PLAN_DIRECT"),

  GATEWAY_ROUTED("GATEWAY_ROUTED");

  private final static Map<String, AccessMode> MAP;

  static {
    Map<String, AccessMode> map = new HashMap<String, AccessMode>();
    for ( AccessMode value : AccessMode.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  AccessMode(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static AccessMode fromString(String v) {
    return MAP.get(v);
  }

}