// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * A resumable, catalog-pinned unit composing typed connector reads, owner selections and an owner-approved EffectBatch (connector-action-runs-and-effect-batches AC1, generalizing the single NestorTurnProposal.ActionCandidate and effect_proposal row).
 */
public record ActionRun(String runId, String realmId, String conversationId, String turnId, String actionCatalogRevision, ActionRunStatus status, String createdAt, String updatedAt)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String runId = "";
        private String realmId = "";
        private String conversationId = "";
        private String turnId = "";
        private String actionCatalogRevision = "";
        private ActionRunStatus status = null;
        private String createdAt = "";
        private String updatedAt = "";


        public Builder runId(String runId) {
            this.runId = Objects.requireNonNull(runId);
            return this;
        }

        public Builder realmId(String realmId) {
            this.realmId = Objects.requireNonNull(realmId);
            return this;
        }

        public Builder conversationId(String conversationId) {
            this.conversationId = Objects.requireNonNull(conversationId);
            return this;
        }

        public Builder turnId(String turnId) {
            this.turnId = Objects.requireNonNull(turnId);
            return this;
        }

        public Builder actionCatalogRevision(String actionCatalogRevision) {
            this.actionCatalogRevision = Objects.requireNonNull(actionCatalogRevision);
            return this;
        }

        public Builder status(ActionRunStatus status) {
            this.status = Objects.requireNonNull(status);
            return this;
        }

        public Builder createdAt(String createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt);
            return this;
        }

        public Builder updatedAt(String updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt);
            return this;
        }

    public ActionRun build() {
            return new ActionRun(runId, realmId, conversationId, turnId, actionCatalogRevision, status, createdAt, updatedAt);
        }
    }
}
