// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.time.ZonedDateTime;
import java.util.Objects;


public record ActiveContractSet(String realmId, String contractSetDigest, String realmRevision, ZonedDateTime activatedAt, String activatedByDecisionRef)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String realmId = "";
        private String contractSetDigest = "";
        private String realmRevision = "";
        private ZonedDateTime activatedAt = null;
        private String activatedByDecisionRef = "";


        public Builder realmId(String realmId) {
            this.realmId = Objects.requireNonNull(realmId);
            return this;
        }

        public Builder contractSetDigest(String contractSetDigest) {
            this.contractSetDigest = Objects.requireNonNull(contractSetDigest);
            return this;
        }

        public Builder realmRevision(String realmRevision) {
            this.realmRevision = Objects.requireNonNull(realmRevision);
            return this;
        }

        public Builder activatedAt(ZonedDateTime activatedAt) {
            this.activatedAt = Objects.requireNonNull(activatedAt);
            return this;
        }

        public Builder activatedByDecisionRef(String activatedByDecisionRef) {
            this.activatedByDecisionRef = Objects.requireNonNull(activatedByDecisionRef);
            return this;
        }

    public ActiveContractSet build() {
            return new ActiveContractSet(realmId, contractSetDigest, realmRevision, activatedAt, activatedByDecisionRef);
        }
    }
}
