// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.Objects;


public record AdvisorProfileSpec(String ownerRealm, ContractReference roleDefinitionRef, List<AdvisorDialogueOption> dialogueOptions, List<ContractReference> practiceRefs)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ownerRealm = "";
        private ContractReference roleDefinitionRef = null;
        private List<AdvisorDialogueOption> dialogueOptions = List.of();
        private List<ContractReference> practiceRefs = List.of();


        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder roleDefinitionRef(ContractReference roleDefinitionRef) {
            this.roleDefinitionRef = Objects.requireNonNull(roleDefinitionRef);
            return this;
        }

        public Builder dialogueOptions(List<AdvisorDialogueOption> dialogueOptions) {
            this.dialogueOptions = Objects.requireNonNull(dialogueOptions);
            return this;
        }

        public Builder practiceRefs(List<ContractReference> practiceRefs) {
            this.practiceRefs = Objects.requireNonNull(practiceRefs);
            return this;
        }

    public AdvisorProfileSpec build() {
            return new AdvisorProfileSpec(ownerRealm, roleDefinitionRef, dialogueOptions, practiceRefs);
        }
    }
}
