// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.List;
import java.util.List;
import java.util.Objects;


public record AgentDefinitionSpec(List<String> responsibilities, List<String> requestedCapabilities, List<ProhibitedAuthority> prohibitedAuthority, List<RecommendedConnectorReference> recommendedConnectorRefs, AutonomyLevel defaultAutonomy, Ring modificationRing)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private List<String> responsibilities = List.of();
        private List<String> requestedCapabilities = List.of();
        private List<ProhibitedAuthority> prohibitedAuthority = List.of();
        private List<RecommendedConnectorReference> recommendedConnectorRefs = List.of();
        private AutonomyLevel defaultAutonomy = null;
        private Ring modificationRing = null;


        public Builder responsibilities(List<String> responsibilities) {
            this.responsibilities = Objects.requireNonNull(responsibilities);
            return this;
        }

        public Builder requestedCapabilities(List<String> requestedCapabilities) {
            this.requestedCapabilities = Objects.requireNonNull(requestedCapabilities);
            return this;
        }

        public Builder prohibitedAuthority(List<ProhibitedAuthority> prohibitedAuthority) {
            this.prohibitedAuthority = Objects.requireNonNull(prohibitedAuthority);
            return this;
        }

        public Builder recommendedConnectorRefs(List<RecommendedConnectorReference> recommendedConnectorRefs) {
            this.recommendedConnectorRefs = Objects.requireNonNull(recommendedConnectorRefs);
            return this;
        }

        public Builder defaultAutonomy(AutonomyLevel defaultAutonomy) {
            this.defaultAutonomy = Objects.requireNonNull(defaultAutonomy);
            return this;
        }

        public Builder modificationRing(Ring modificationRing) {
            this.modificationRing = Objects.requireNonNull(modificationRing);
            return this;
        }

    public AgentDefinitionSpec build() {
            return new AgentDefinitionSpec(responsibilities, requestedCapabilities, prohibitedAuthority, recommendedConnectorRefs, defaultAutonomy, modificationRing);
        }
    }
}
