// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * RFC 9457 compliant problem details model for API errors without unconstrained maps.
 */
public record ApiProblem(String type, String title, int status, String detail, String instance, String code, String realmId, String timestamp)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String type = "";
        private String title = "";
        private int status = 0;
        private String detail = "";
        private String instance = "";
        private String code = "";
        private String realmId = "";
        private String timestamp = "";


        public Builder type(String type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }

        public Builder title(String title) {
            this.title = Objects.requireNonNull(title);
            return this;
        }

        public Builder status(int status) {
            this.status = Objects.requireNonNull(status);
            return this;
        }

        public Builder detail(String detail) {
            this.detail = Objects.requireNonNull(detail);
            return this;
        }

        public Builder instance(String instance) {
            this.instance = Objects.requireNonNull(instance);
            return this;
        }

        public Builder code(String code) {
            this.code = Objects.requireNonNull(code);
            return this;
        }

        public Builder realmId(String realmId) {
            this.realmId = Objects.requireNonNull(realmId);
            return this;
        }

        public Builder timestamp(String timestamp) {
            this.timestamp = Objects.requireNonNull(timestamp);
            return this;
        }

    public ApiProblem build() {
            return new ApiProblem(type, title, status, detail, instance, code, realmId, timestamp);
        }
    }
}
