// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Response schema binding for a specific HTTP status code.
 */
public record ApiResponseBinding(int statusCode, String mediaType, SchemaBinding schemaBinding, String description)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private int statusCode = 0;
        private String mediaType = "";
        private SchemaBinding schemaBinding = null;
        private String description = "";


        public Builder statusCode(int statusCode) {
            this.statusCode = Objects.requireNonNull(statusCode);
            return this;
        }

        public Builder mediaType(String mediaType) {
            this.mediaType = Objects.requireNonNull(mediaType);
            return this;
        }

        public Builder schemaBinding(SchemaBinding schemaBinding) {
            this.schemaBinding = Objects.requireNonNull(schemaBinding);
            return this;
        }

        public Builder description(String description) {
            this.description = Objects.requireNonNull(description);
            return this;
        }

    public ApiResponseBinding build() {
            return new ApiResponseBinding(statusCode, mediaType, schemaBinding, description);
        }
    }
}
