// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Governed API surface contract mapping routes, verbs, and audiences to SchemaBindings.
 */
public record ApiSurface(String apiVersion, String kind, Metadata metadata, ApiSurfaceSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private ApiSurfaceSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(ApiSurfaceSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public ApiSurface build() {
            return new ApiSurface(apiVersion, kind, metadata, spec);
        }
    }
}
