// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Four questions asked of every submission, separate because they fail independently: a perfectly signed artifact can be unusable by an agent, and a well-described tool can have no business in this Realm.
 */
public record AppraisalDimensions(AppraisalDimension provenance, AppraisalDimension security, AppraisalDimension relevance, AppraisalDimension agentUsability)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private AppraisalDimension provenance = null;
        private AppraisalDimension security = null;
        private AppraisalDimension relevance = null;
        private AppraisalDimension agentUsability = null;


        public Builder provenance(AppraisalDimension provenance) {
            this.provenance = Objects.requireNonNull(provenance);
            return this;
        }

        public Builder security(AppraisalDimension security) {
            this.security = Objects.requireNonNull(security);
            return this;
        }

        public Builder relevance(AppraisalDimension relevance) {
            this.relevance = Objects.requireNonNull(relevance);
            return this;
        }

        public Builder agentUsability(AppraisalDimension agentUsability) {
            this.agentUsability = Objects.requireNonNull(agentUsability);
            return this;
        }

    public AppraisalDimensions build() {
            return new AppraisalDimensions(provenance, security, relevance, agentUsability);
        }
    }
}
