// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * The IHM-layer counterpart to ProcessStepKind (execution.yaml): AssistedJourney is a human-facing collection graph, while ProcessSpec remains the durable execution graph.
 */
public enum AssistedJourneyStepKind {

  COLLECT("COLLECT"),

  AWAIT("AWAIT"),

  CONFIRM("CONFIRM"),

  DIALOGUE_COLLECT("DIALOGUE_COLLECT"),

  SUB_JOURNEY("SUB_JOURNEY");

  private final static Map<String, AssistedJourneyStepKind> MAP;

  static {
    Map<String, AssistedJourneyStepKind> map = new HashMap<String, AssistedJourneyStepKind>();
    for ( AssistedJourneyStepKind value : AssistedJourneyStepKind.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  AssistedJourneyStepKind(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static AssistedJourneyStepKind fromString(String v) {
    return MAP.get(v);
  }

}