// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.List;
import java.util.List;
import java.util.Objects;


public record AssistedJourneySpec(String journeyId, String name, String description, String category, String icon, Boolean interruptible, AssistedJourneyConcurrencyPolicy concurrencyPolicy, Boolean firstRunMandatory, Boolean lifetimeUnique, String heroImage, JourneyPresentation presentation, ContractReference resourceBudgetRef, List<String> requiredCapabilities, List<ContractReference> policySetRefs, String emitsCapability, AssistedJourneyCompletionMode completionMode, AssistedJourneyNavigationMode navigationMode, AssistedJourneyEmission emission, List<AssistedJourneyEmissionBundleItem> emissionBundle, List<AssistedJourneyStep> steps, String summaryI18nKey)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String journeyId = "";
        private String name = "";
        private String description = "";
        private String category = "";
        private String icon = "";
        private Boolean interruptible = null;
        private AssistedJourneyConcurrencyPolicy concurrencyPolicy = null;
        private Boolean firstRunMandatory = null;
        private Boolean lifetimeUnique = null;
        private String heroImage = "";
        private JourneyPresentation presentation = null;
        private ContractReference resourceBudgetRef = null;
        private List<String> requiredCapabilities = List.of();
        private List<ContractReference> policySetRefs = List.of();
        private String emitsCapability = "";
        private AssistedJourneyCompletionMode completionMode = null;
        private AssistedJourneyNavigationMode navigationMode = null;
        private AssistedJourneyEmission emission = null;
        private List<AssistedJourneyEmissionBundleItem> emissionBundle = List.of();
        private List<AssistedJourneyStep> steps = List.of();
        private String summaryI18nKey = "";


        public Builder journeyId(String journeyId) {
            this.journeyId = Objects.requireNonNull(journeyId);
            return this;
        }

        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }

        public Builder description(String description) {
            this.description = Objects.requireNonNull(description);
            return this;
        }

        public Builder category(String category) {
            this.category = Objects.requireNonNull(category);
            return this;
        }

        public Builder icon(String icon) {
            this.icon = Objects.requireNonNull(icon);
            return this;
        }

        public Builder interruptible(Boolean interruptible) {
            this.interruptible = Objects.requireNonNull(interruptible);
            return this;
        }

        public Builder concurrencyPolicy(AssistedJourneyConcurrencyPolicy concurrencyPolicy) {
            this.concurrencyPolicy = Objects.requireNonNull(concurrencyPolicy);
            return this;
        }

        public Builder firstRunMandatory(Boolean firstRunMandatory) {
            this.firstRunMandatory = Objects.requireNonNull(firstRunMandatory);
            return this;
        }

        public Builder lifetimeUnique(Boolean lifetimeUnique) {
            this.lifetimeUnique = Objects.requireNonNull(lifetimeUnique);
            return this;
        }

        public Builder heroImage(String heroImage) {
            this.heroImage = Objects.requireNonNull(heroImage);
            return this;
        }

        public Builder presentation(JourneyPresentation presentation) {
            this.presentation = Objects.requireNonNull(presentation);
            return this;
        }

        public Builder resourceBudgetRef(ContractReference resourceBudgetRef) {
            this.resourceBudgetRef = Objects.requireNonNull(resourceBudgetRef);
            return this;
        }

        public Builder requiredCapabilities(List<String> requiredCapabilities) {
            this.requiredCapabilities = Objects.requireNonNull(requiredCapabilities);
            return this;
        }

        public Builder policySetRefs(List<ContractReference> policySetRefs) {
            this.policySetRefs = Objects.requireNonNull(policySetRefs);
            return this;
        }

        public Builder emitsCapability(String emitsCapability) {
            this.emitsCapability = Objects.requireNonNull(emitsCapability);
            return this;
        }

        public Builder completionMode(AssistedJourneyCompletionMode completionMode) {
            this.completionMode = Objects.requireNonNull(completionMode);
            return this;
        }

        public Builder navigationMode(AssistedJourneyNavigationMode navigationMode) {
            this.navigationMode = Objects.requireNonNull(navigationMode);
            return this;
        }

        public Builder emission(AssistedJourneyEmission emission) {
            this.emission = Objects.requireNonNull(emission);
            return this;
        }

        public Builder emissionBundle(List<AssistedJourneyEmissionBundleItem> emissionBundle) {
            this.emissionBundle = Objects.requireNonNull(emissionBundle);
            return this;
        }

        public Builder steps(List<AssistedJourneyStep> steps) {
            this.steps = Objects.requireNonNull(steps);
            return this;
        }

        public Builder summaryI18nKey(String summaryI18nKey) {
            this.summaryI18nKey = Objects.requireNonNull(summaryI18nKey);
            return this;
        }

    public AssistedJourneySpec build() {
            return new AssistedJourneySpec(journeyId, name, description, category, icon, interruptible, concurrencyPolicy, firstRunMandatory, lifetimeUnique, heroImage, presentation, resourceBudgetRef, requiredCapabilities, policySetRefs, emitsCapability, completionMode, navigationMode, emission, emissionBundle, steps, summaryI18nKey);
        }
    }
}
