// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record AssistedJourneyRoutingEligibilityCheck(String projectField, String teamField)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String projectField = "";
        private String teamField = "";


        public Builder projectField(String projectField) {
            this.projectField = Objects.requireNonNull(projectField);
            return this;
        }

        public Builder teamField(String teamField) {
            this.teamField = Objects.requireNonNull(teamField);
            return this;
        }

    public AssistedJourneyRoutingEligibilityCheck build() {
            return new AssistedJourneyRoutingEligibilityCheck(projectField, teamField);
        }
    }
}
