// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record AssistedJourneyFieldValidation(String field, Boolean required, Integer minimumLength, String pattern, Integer minimumItems)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String field = "";
        private Boolean required = null;
        private Integer minimumLength = null;
        private String pattern = "";
        private Integer minimumItems = null;


        public Builder field(String field) {
            this.field = Objects.requireNonNull(field);
            return this;
        }

        public Builder required(Boolean required) {
            this.required = Objects.requireNonNull(required);
            return this;
        }

        public Builder minimumLength(Integer minimumLength) {
            this.minimumLength = Objects.requireNonNull(minimumLength);
            return this;
        }

        public Builder pattern(String pattern) {
            this.pattern = Objects.requireNonNull(pattern);
            return this;
        }

        public Builder minimumItems(Integer minimumItems) {
            this.minimumItems = Objects.requireNonNull(minimumItems);
            return this;
        }

    public AssistedJourneyFieldValidation build() {
            return new AssistedJourneyFieldValidation(field, required, minimumLength, pattern, minimumItems);
        }
    }
}
