// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.List;
import java.util.Objects;


public record AssistedJourneyCollectionProjection(String field, String sourceField, List<String> keys, List<String> optionalKeys, List<AssistedJourneyFieldValidation> itemValidations, String itemReferenceKind)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String field = "";
        private String sourceField = "";
        private List<String> keys = List.of();
        private List<String> optionalKeys = List.of();
        private List<AssistedJourneyFieldValidation> itemValidations = List.of();
        private String itemReferenceKind = "";


        public Builder field(String field) {
            this.field = Objects.requireNonNull(field);
            return this;
        }

        public Builder sourceField(String sourceField) {
            this.sourceField = Objects.requireNonNull(sourceField);
            return this;
        }

        public Builder keys(List<String> keys) {
            this.keys = Objects.requireNonNull(keys);
            return this;
        }

        public Builder optionalKeys(List<String> optionalKeys) {
            this.optionalKeys = Objects.requireNonNull(optionalKeys);
            return this;
        }

        public Builder itemValidations(List<AssistedJourneyFieldValidation> itemValidations) {
            this.itemValidations = Objects.requireNonNull(itemValidations);
            return this;
        }

        public Builder itemReferenceKind(String itemReferenceKind) {
            this.itemReferenceKind = Objects.requireNonNull(itemReferenceKind);
            return this;
        }

    public AssistedJourneyCollectionProjection build() {
            return new AssistedJourneyCollectionProjection(field, sourceField, keys, optionalKeys, itemValidations, itemReferenceKind);
        }
    }
}
