// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum AssuranceLevel {

  NONE("NONE"),

  SELF_REPORTED("SELF_REPORTED"),

  OBSERVED("OBSERVED"),

  INDEPENDENTLY_VERIFIED("INDEPENDENTLY_VERIFIED");

  private final static Map<String, AssuranceLevel> MAP;

  static {
    Map<String, AssuranceLevel> map = new HashMap<String, AssuranceLevel>();
    for ( AssuranceLevel value : AssuranceLevel.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  AssuranceLevel(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static AssuranceLevel fromString(String v) {
    return MAP.get(v);
  }

}