// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum AttentionAdmissionReason {

  NO_ELIGIBLE_ROLE("NO_ELIGIBLE_ROLE"),

  ADMISSION_DECLINED("ADMISSION_DECLINED"),

  POLICY_DENIED("POLICY_DENIED");

  private final static Map<String, AttentionAdmissionReason> MAP;

  static {
    Map<String, AttentionAdmissionReason> map = new HashMap<String, AttentionAdmissionReason>();
    for ( AttentionAdmissionReason value : AttentionAdmissionReason.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  AttentionAdmissionReason(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static AttentionAdmissionReason fromString(String v) {
    return MAP.get(v);
  }

}