// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum AttentionTargetSubjectKind {

  ROLE("ROLE"),

  PRINCIPAL("PRINCIPAL");

  private final static Map<String, AttentionTargetSubjectKind> MAP;

  static {
    Map<String, AttentionTargetSubjectKind> map = new HashMap<String, AttentionTargetSubjectKind>();
    for ( AttentionTargetSubjectKind value : AttentionTargetSubjectKind.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  AttentionTargetSubjectKind(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static AttentionTargetSubjectKind fromString(String v) {
    return MAP.get(v);
  }

}