// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * The human-facing routing projection of something that wants a person. It is PostgreSQL recognized state (canonical decision 21), never a Git proposal or effect authority.
 */
public record AttentionItem(String apiVersion, String kind, Metadata metadata, AttentionItemSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private AttentionItemSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(AttentionItemSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public AttentionItem build() {
            return new AttentionItem(apiVersion, kind, metadata, spec);
        }
    }
}
