// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.List;
import java.time.ZonedDateTime;
import java.util.Objects;


public record AttentionItemSpec(AttentionType type, AttentionSource source, AttentionTarget target, String decisionRef, List<AttentionDecisionOption> decisionOptions, DataScope classification, AttentionUrgency urgency, AttentionInterruptibility interruptibility, AttentionRequestedResponse requestedResponse, DeliveryMode deliveryMode, Float confidence, AttentionAdmissionReason admissionReason, List<String> relatedCommitments, List<String> evidenceRefs, ZonedDateTime occurredAt)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private AttentionType type = null;
        private AttentionSource source = null;
        private AttentionTarget target = null;
        private String decisionRef = "";
        private List<AttentionDecisionOption> decisionOptions = List.of();
        private DataScope classification = null;
        private AttentionUrgency urgency = null;
        private AttentionInterruptibility interruptibility = null;
        private AttentionRequestedResponse requestedResponse = null;
        private DeliveryMode deliveryMode = null;
        private Float confidence = null;
        private AttentionAdmissionReason admissionReason = null;
        private List<String> relatedCommitments = List.of();
        private List<String> evidenceRefs = List.of();
        private ZonedDateTime occurredAt = null;


        public Builder type(AttentionType type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }

        public Builder source(AttentionSource source) {
            this.source = Objects.requireNonNull(source);
            return this;
        }

        public Builder target(AttentionTarget target) {
            this.target = Objects.requireNonNull(target);
            return this;
        }

        public Builder decisionRef(String decisionRef) {
            this.decisionRef = Objects.requireNonNull(decisionRef);
            return this;
        }

        public Builder decisionOptions(List<AttentionDecisionOption> decisionOptions) {
            this.decisionOptions = Objects.requireNonNull(decisionOptions);
            return this;
        }

        public Builder classification(DataScope classification) {
            this.classification = Objects.requireNonNull(classification);
            return this;
        }

        public Builder urgency(AttentionUrgency urgency) {
            this.urgency = Objects.requireNonNull(urgency);
            return this;
        }

        public Builder interruptibility(AttentionInterruptibility interruptibility) {
            this.interruptibility = Objects.requireNonNull(interruptibility);
            return this;
        }

        public Builder requestedResponse(AttentionRequestedResponse requestedResponse) {
            this.requestedResponse = Objects.requireNonNull(requestedResponse);
            return this;
        }

        public Builder deliveryMode(DeliveryMode deliveryMode) {
            this.deliveryMode = Objects.requireNonNull(deliveryMode);
            return this;
        }

        public Builder confidence(Float confidence) {
            this.confidence = Objects.requireNonNull(confidence);
            return this;
        }

        public Builder admissionReason(AttentionAdmissionReason admissionReason) {
            this.admissionReason = Objects.requireNonNull(admissionReason);
            return this;
        }

        public Builder relatedCommitments(List<String> relatedCommitments) {
            this.relatedCommitments = Objects.requireNonNull(relatedCommitments);
            return this;
        }

        public Builder evidenceRefs(List<String> evidenceRefs) {
            this.evidenceRefs = Objects.requireNonNull(evidenceRefs);
            return this;
        }

        public Builder occurredAt(ZonedDateTime occurredAt) {
            this.occurredAt = Objects.requireNonNull(occurredAt);
            return this;
        }

    public AttentionItemSpec build() {
            return new AttentionItemSpec(type, source, target, decisionRef, decisionOptions, classification, urgency, interruptibility, requestedResponse, deliveryMode, confidence, admissionReason, relatedCommitments, evidenceRefs, occurredAt);
        }
    }
}
