// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Progressive autonomy ladder. Configured per action class, channel, audience, risk and Realm -- never as one global agent level.
 */
public enum AutonomyLevel {

  OBSERVE("OBSERVE"),

  DRAFT("DRAFT"),

  SUPERVISED("SUPERVISED"),

  BOUNDED_AUTONOMOUS("BOUNDED_AUTONOMOUS");

  private final static Map<String, AutonomyLevel> MAP;

  static {
    Map<String, AutonomyLevel> map = new HashMap<String, AutonomyLevel>();
    for ( AutonomyLevel value : AutonomyLevel.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  AutonomyLevel(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static AutonomyLevel fromString(String v) {
    return MAP.get(v);
  }

}