// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * A standing owner delegation, evaluated by policy at merge time rather than read by the authoring turn, per bounded-autonomous-merge-gates (ADR-0024). Declared per pathGlob, ring and capability -- never as one global boolean, since AutonomyLevel is configured per action class, channel, audience, risk and Realm and never as one global agent level. A change to the delegation itself is never eligible for the automatic merge it grants (fixpoint guard, Rego).
 */
public record AutonomousMergeDelegation(String apiVersion, String kind, Metadata metadata, AutonomousMergeDelegationSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private AutonomousMergeDelegationSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(AutonomousMergeDelegationSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public AutonomousMergeDelegation build() {
            return new AutonomousMergeDelegation(apiVersion, kind, metadata, spec);
        }
    }
}
