// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * A human-facing named preset over a WorkerRequirementProfile vector. Names an intent, never a model or a power score (ADR-0019, ADR-0082).
 */
public record CapabilityProfile(String apiVersion, String kind, Metadata metadata, CapabilityProfileSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private CapabilityProfileSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(CapabilityProfileSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public CapabilityProfile build() {
            return new CapabilityProfile(apiVersion, kind, metadata, spec);
        }
    }
}
