// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;

/**
 * Ordered multi-file changeset proposed against one repository, the unit ForgeApplier opens as one repository PR within a multi-repository saga (multi-repository-change-set-saga AC1). Owner approval and phase progression are tracked separately, not on this shape.
 */
public record ChangeSetProposal(String changeSetProposalId, String repository, String baseCommitSha, List<ChangeSetFile> files, String expectedTreeDigest, boolean ownerApproved)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String changeSetProposalId = "";
        private String repository = "";
        private String baseCommitSha = "";
        private List<ChangeSetFile> files = List.of();
        private String expectedTreeDigest = "";
        private boolean ownerApproved = false;


        public Builder changeSetProposalId(String changeSetProposalId) {
            this.changeSetProposalId = Objects.requireNonNull(changeSetProposalId);
            return this;
        }

        public Builder repository(String repository) {
            this.repository = Objects.requireNonNull(repository);
            return this;
        }

        public Builder baseCommitSha(String baseCommitSha) {
            this.baseCommitSha = Objects.requireNonNull(baseCommitSha);
            return this;
        }

        public Builder files(List<ChangeSetFile> files) {
            this.files = Objects.requireNonNull(files);
            return this;
        }

        public Builder expectedTreeDigest(String expectedTreeDigest) {
            this.expectedTreeDigest = Objects.requireNonNull(expectedTreeDigest);
            return this;
        }

        public Builder ownerApproved(boolean ownerApproved) {
            this.ownerApproved = Objects.requireNonNull(ownerApproved);
            return this;
        }

    public ChangeSetProposal build() {
            return new ChangeSetProposal(changeSetProposalId, repository, baseCommitSha, files, expectedTreeDigest, ownerApproved);
        }
    }
}
