// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Observed record of the single atomic PR ForgeApplier opened for a ChangeSetProposal (multi-repository-change-set-saga AC2/AC5). Existence is idempotency evidence -- a second saga execution against the same changeSetProposalId returns this record instead of re-opening a PR.
 */
public record ChangeSetProjection(String changeSetProposalId, String realmId, String provider, String externalId, String url, String state, String branchSha, String changesetSha256, String observedAt)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String changeSetProposalId = "";
        private String realmId = "";
        private String provider = "";
        private String externalId = "";
        private String url = "";
        private String state = "";
        private String branchSha = "";
        private String changesetSha256 = "";
        private String observedAt = "";


        public Builder changeSetProposalId(String changeSetProposalId) {
            this.changeSetProposalId = Objects.requireNonNull(changeSetProposalId);
            return this;
        }

        public Builder realmId(String realmId) {
            this.realmId = Objects.requireNonNull(realmId);
            return this;
        }

        public Builder provider(String provider) {
            this.provider = Objects.requireNonNull(provider);
            return this;
        }

        public Builder externalId(String externalId) {
            this.externalId = Objects.requireNonNull(externalId);
            return this;
        }

        public Builder url(String url) {
            this.url = Objects.requireNonNull(url);
            return this;
        }

        public Builder state(String state) {
            this.state = Objects.requireNonNull(state);
            return this;
        }

        public Builder branchSha(String branchSha) {
            this.branchSha = Objects.requireNonNull(branchSha);
            return this;
        }

        public Builder changesetSha256(String changesetSha256) {
            this.changesetSha256 = Objects.requireNonNull(changesetSha256);
            return this;
        }

        public Builder observedAt(String observedAt) {
            this.observedAt = Objects.requireNonNull(observedAt);
            return this;
        }

    public ChangeSetProjection build() {
            return new ChangeSetProjection(changeSetProposalId, realmId, provider, externalId, url, state, branchSha, changesetSha256, observedAt);
        }
    }
}
