// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;


public record ChiefOfStaffProfileSpec(String ownerRealm, ContractReference roleDefinitionRef, ContractReference intakeProcessSpecRef, ContractReference directWorkProcessSpecRef, String authority, String connectorCatalogScope, ClarificationPolicy clarification, List<DispositionRule> dispositionRules, AcknowledgementPolicy acknowledgement, ContractReference statusPracticeRef)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ownerRealm = "";
        private ContractReference roleDefinitionRef = null;
        private ContractReference intakeProcessSpecRef = null;
        private ContractReference directWorkProcessSpecRef = null;
        private String authority = "";
        private String connectorCatalogScope = "";
        private ClarificationPolicy clarification = null;
        private List<DispositionRule> dispositionRules = List.of();
        private AcknowledgementPolicy acknowledgement = null;
        private ContractReference statusPracticeRef = null;


        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder roleDefinitionRef(ContractReference roleDefinitionRef) {
            this.roleDefinitionRef = Objects.requireNonNull(roleDefinitionRef);
            return this;
        }

        public Builder intakeProcessSpecRef(ContractReference intakeProcessSpecRef) {
            this.intakeProcessSpecRef = Objects.requireNonNull(intakeProcessSpecRef);
            return this;
        }

        public Builder directWorkProcessSpecRef(ContractReference directWorkProcessSpecRef) {
            this.directWorkProcessSpecRef = Objects.requireNonNull(directWorkProcessSpecRef);
            return this;
        }

        public Builder authority(String authority) {
            this.authority = Objects.requireNonNull(authority);
            return this;
        }

        public Builder connectorCatalogScope(String connectorCatalogScope) {
            this.connectorCatalogScope = Objects.requireNonNull(connectorCatalogScope);
            return this;
        }

        public Builder clarification(ClarificationPolicy clarification) {
            this.clarification = Objects.requireNonNull(clarification);
            return this;
        }

        public Builder dispositionRules(List<DispositionRule> dispositionRules) {
            this.dispositionRules = Objects.requireNonNull(dispositionRules);
            return this;
        }

        public Builder acknowledgement(AcknowledgementPolicy acknowledgement) {
            this.acknowledgement = Objects.requireNonNull(acknowledgement);
            return this;
        }

        public Builder statusPracticeRef(ContractReference statusPracticeRef) {
            this.statusPracticeRef = Objects.requireNonNull(statusPracticeRef);
            return this;
        }

    public ChiefOfStaffProfileSpec build() {
            return new ChiefOfStaffProfileSpec(ownerRealm, roleDefinitionRef, intakeProcessSpecRef, directWorkProcessSpecRef, authority, connectorCatalogScope, clarification, dispositionRules, acknowledgement, statusPracticeRef);
        }
    }
}
