// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record ClarificationPolicy(boolean enabled, int maximumTurns, String onInsufficientInformation, OnExhaustionOutcome onExhaustion)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private boolean enabled = false;
        private int maximumTurns = 0;
        private String onInsufficientInformation = "";
        private OnExhaustionOutcome onExhaustion = null;


        public Builder enabled(boolean enabled) {
            this.enabled = Objects.requireNonNull(enabled);
            return this;
        }

        public Builder maximumTurns(int maximumTurns) {
            this.maximumTurns = Objects.requireNonNull(maximumTurns);
            return this;
        }

        public Builder onInsufficientInformation(String onInsufficientInformation) {
            this.onInsufficientInformation = Objects.requireNonNull(onInsufficientInformation);
            return this;
        }

        public Builder onExhaustion(OnExhaustionOutcome onExhaustion) {
            this.onExhaustion = Objects.requireNonNull(onExhaustion);
            return this;
        }

    public ClarificationPolicy build() {
            return new ClarificationPolicy(enabled, maximumTurns, onInsufficientInformation, onExhaustion);
        }
    }
}
