// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.time.ZonedDateTime;
import java.util.Objects;

/**
 * Recognized pending CLI turn and sealed prompt, bound to one execution lease.
 */
public record CliDialogueDispatch(String leaseId, String realmId, String conversationId, String turnId, String invocationId, String promptCiphertext, String promptDigest, String status, ZonedDateTime completedAt)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String leaseId = "";
        private String realmId = "";
        private String conversationId = "";
        private String turnId = "";
        private String invocationId = "";
        private String promptCiphertext = "";
        private String promptDigest = "";
        private String status = "";
        private ZonedDateTime completedAt = null;


        public Builder leaseId(String leaseId) {
            this.leaseId = Objects.requireNonNull(leaseId);
            return this;
        }

        public Builder realmId(String realmId) {
            this.realmId = Objects.requireNonNull(realmId);
            return this;
        }

        public Builder conversationId(String conversationId) {
            this.conversationId = Objects.requireNonNull(conversationId);
            return this;
        }

        public Builder turnId(String turnId) {
            this.turnId = Objects.requireNonNull(turnId);
            return this;
        }

        public Builder invocationId(String invocationId) {
            this.invocationId = Objects.requireNonNull(invocationId);
            return this;
        }

        public Builder promptCiphertext(String promptCiphertext) {
            this.promptCiphertext = Objects.requireNonNull(promptCiphertext);
            return this;
        }

        public Builder promptDigest(String promptDigest) {
            this.promptDigest = Objects.requireNonNull(promptDigest);
            return this;
        }

        public Builder status(String status) {
            this.status = Objects.requireNonNull(status);
            return this;
        }

        public Builder completedAt(ZonedDateTime completedAt) {
            this.completedAt = Objects.requireNonNull(completedAt);
            return this;
        }

    public CliDialogueDispatch build() {
            return new CliDialogueDispatch(leaseId, realmId, conversationId, turnId, invocationId, promptCiphertext, promptDigest, status, completedAt);
        }
    }
}
