// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Sanitized final output payload, exit code, and evidence digest from a CLI execution.
 */
public record CliInvocationResult(String workOrderId, String status, int exitCode, SchemaBoundPayload sanitizedOutputPayload, String evidenceDigest, Integer tokensConsumed, String completedAt)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String workOrderId = "";
        private String status = "";
        private int exitCode = 0;
        private SchemaBoundPayload sanitizedOutputPayload = null;
        private String evidenceDigest = "";
        private Integer tokensConsumed = null;
        private String completedAt = "";


        public Builder workOrderId(String workOrderId) {
            this.workOrderId = Objects.requireNonNull(workOrderId);
            return this;
        }

        public Builder status(String status) {
            this.status = Objects.requireNonNull(status);
            return this;
        }

        public Builder exitCode(int exitCode) {
            this.exitCode = Objects.requireNonNull(exitCode);
            return this;
        }

        public Builder sanitizedOutputPayload(SchemaBoundPayload sanitizedOutputPayload) {
            this.sanitizedOutputPayload = Objects.requireNonNull(sanitizedOutputPayload);
            return this;
        }

        public Builder evidenceDigest(String evidenceDigest) {
            this.evidenceDigest = Objects.requireNonNull(evidenceDigest);
            return this;
        }

        public Builder tokensConsumed(Integer tokensConsumed) {
            this.tokensConsumed = Objects.requireNonNull(tokensConsumed);
            return this;
        }

        public Builder completedAt(String completedAt) {
            this.completedAt = Objects.requireNonNull(completedAt);
            return this;
        }

    public CliInvocationResult build() {
            return new CliInvocationResult(workOrderId, status, exitCode, sanitizedOutputPayload, evidenceDigest, tokensConsumed, completedAt);
        }
    }
}
