// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Observed installation and doctor health status of a CLI tool on a machine.
 */
public record CliInstallationObservation(ContractReference machineRef, ContractReference toolRef, ContractReference installedReleaseRef, String status, String doctorSummary, String observedAt)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private ContractReference machineRef = null;
        private ContractReference toolRef = null;
        private ContractReference installedReleaseRef = null;
        private String status = "";
        private String doctorSummary = "";
        private String observedAt = "";


        public Builder machineRef(ContractReference machineRef) {
            this.machineRef = Objects.requireNonNull(machineRef);
            return this;
        }

        public Builder toolRef(ContractReference toolRef) {
            this.toolRef = Objects.requireNonNull(toolRef);
            return this;
        }

        public Builder installedReleaseRef(ContractReference installedReleaseRef) {
            this.installedReleaseRef = Objects.requireNonNull(installedReleaseRef);
            return this;
        }

        public Builder status(String status) {
            this.status = Objects.requireNonNull(status);
            return this;
        }

        public Builder doctorSummary(String doctorSummary) {
            this.doctorSummary = Objects.requireNonNull(doctorSummary);
            return this;
        }

        public Builder observedAt(String observedAt) {
            this.observedAt = Objects.requireNonNull(observedAt);
            return this;
        }

    public CliInstallationObservation build() {
            return new CliInstallationObservation(machineRef, toolRef, installedReleaseRef, status, doctorSummary, observedAt);
        }
    }
}
