// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Exact CLI release's qualified format for an isolated lease-local MCP configuration.
 */
public record CliMcpAdapterProfile(String configurationFormat, String toolNameEncoding, String configSchemaDigest, String smokeEvidenceRef)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String configurationFormat = "";
        private String toolNameEncoding = "";
        private String configSchemaDigest = "";
        private String smokeEvidenceRef = "";


        public Builder configurationFormat(String configurationFormat) {
            this.configurationFormat = Objects.requireNonNull(configurationFormat);
            return this;
        }

        public Builder toolNameEncoding(String toolNameEncoding) {
            this.toolNameEncoding = Objects.requireNonNull(toolNameEncoding);
            return this;
        }

        public Builder configSchemaDigest(String configSchemaDigest) {
            this.configSchemaDigest = Objects.requireNonNull(configSchemaDigest);
            return this;
        }

        public Builder smokeEvidenceRef(String smokeEvidenceRef) {
            this.smokeEvidenceRef = Objects.requireNonNull(smokeEvidenceRef);
            return this;
        }

    public CliMcpAdapterProfile build() {
            return new CliMcpAdapterProfile(configurationFormat, toolNameEncoding, configSchemaDigest, smokeEvidenceRef);
        }
    }
}
