// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum CliQualification {

  QUALIFIED("QUALIFIED"),

  DECLARABLE_ONLY("DECLARABLE_ONLY"),

  DEPRECATED("DEPRECATED");

  private final static Map<String, CliQualification> MAP;

  static {
    Map<String, CliQualification> map = new HashMap<String, CliQualification>();
    for ( CliQualification value : CliQualification.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  CliQualification(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static CliQualification fromString(String v) {
    return MAP.get(v);
  }

}