// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;

/**
 * Specification for a CliToolDefinition contract.
 */
public record CliToolDefinitionSpec(String toolName, WorkerCli cli, CliQualification qualification, List<String> supportedAdapterProfiles, String defaultProfile)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String toolName = "";
        private WorkerCli cli = null;
        private CliQualification qualification = null;
        private List<String> supportedAdapterProfiles = List.of();
        private String defaultProfile = "";


        public Builder toolName(String toolName) {
            this.toolName = Objects.requireNonNull(toolName);
            return this;
        }

        public Builder cli(WorkerCli cli) {
            this.cli = Objects.requireNonNull(cli);
            return this;
        }

        public Builder qualification(CliQualification qualification) {
            this.qualification = Objects.requireNonNull(qualification);
            return this;
        }

        public Builder supportedAdapterProfiles(List<String> supportedAdapterProfiles) {
            this.supportedAdapterProfiles = Objects.requireNonNull(supportedAdapterProfiles);
            return this;
        }

        public Builder defaultProfile(String defaultProfile) {
            this.defaultProfile = Objects.requireNonNull(defaultProfile);
            return this;
        }

    public CliToolDefinitionSpec build() {
            return new CliToolDefinitionSpec(toolName, cli, qualification, supportedAdapterProfiles, defaultProfile);
        }
    }
}
