// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Observed consumption metrics from CLI tool invocations.
 */
public record CliUsageObservation(ContractReference toolRef, Integer tokensUsed, Integer callsCount, Integer durationMs, String capturedAt)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private ContractReference toolRef = null;
        private Integer tokensUsed = null;
        private Integer callsCount = null;
        private Integer durationMs = null;
        private String capturedAt = "";


        public Builder toolRef(ContractReference toolRef) {
            this.toolRef = Objects.requireNonNull(toolRef);
            return this;
        }

        public Builder tokensUsed(Integer tokensUsed) {
            this.tokensUsed = Objects.requireNonNull(tokensUsed);
            return this;
        }

        public Builder callsCount(Integer callsCount) {
            this.callsCount = Objects.requireNonNull(callsCount);
            return this;
        }

        public Builder durationMs(Integer durationMs) {
            this.durationMs = Objects.requireNonNull(durationMs);
            return this;
        }

        public Builder capturedAt(String capturedAt) {
            this.capturedAt = Objects.requireNonNull(capturedAt);
            return this;
        }

    public CliUsageObservation build() {
            return new CliUsageObservation(toolRef, tokensUsed, callsCount, durationMs, capturedAt);
        }
    }
}
