// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.Objects;


public record ComplianceProfileSpec(String ownerRealm, String frameworkName, String edition, String officialUri, ComplianceStatus status, ContractReference controlCatalogRef, List<ComplianceMapping> mappings, List<ProcessingRegisterEntry> processingRegister)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ownerRealm = "";
        private String frameworkName = "";
        private String edition = "";
        private String officialUri = "";
        private ComplianceStatus status = null;
        private ContractReference controlCatalogRef = null;
        private List<ComplianceMapping> mappings = List.of();
        private List<ProcessingRegisterEntry> processingRegister = List.of();


        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder frameworkName(String frameworkName) {
            this.frameworkName = Objects.requireNonNull(frameworkName);
            return this;
        }

        public Builder edition(String edition) {
            this.edition = Objects.requireNonNull(edition);
            return this;
        }

        public Builder officialUri(String officialUri) {
            this.officialUri = Objects.requireNonNull(officialUri);
            return this;
        }

        public Builder status(ComplianceStatus status) {
            this.status = Objects.requireNonNull(status);
            return this;
        }

        public Builder controlCatalogRef(ContractReference controlCatalogRef) {
            this.controlCatalogRef = Objects.requireNonNull(controlCatalogRef);
            return this;
        }

        public Builder mappings(List<ComplianceMapping> mappings) {
            this.mappings = Objects.requireNonNull(mappings);
            return this;
        }

        public Builder processingRegister(List<ProcessingRegisterEntry> processingRegister) {
            this.processingRegister = Objects.requireNonNull(processingRegister);
            return this;
        }

    public ComplianceProfileSpec build() {
            return new ComplianceProfileSpec(ownerRealm, frameworkName, edition, officialUri, status, controlCatalogRef, mappings, processingRegister);
        }
    }
}
