// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * A named referential (edition, official URI) and its mappings to a ControlCatalog (docs/concepts/positionnement-conceptuel.md#conformite-et-auditabilite-par-construction). Split out of GovernanceOverlay. Never recopies referential text -- identifiers, edition, and URI only. Carries the RGPD art. 30 processing register: a compliance profile scoped to data protection references the processing activities it covers, rather than inventing a separate kind for a register most Realms will attach to exactly one profile.
 */
public record ComplianceProfile(String apiVersion, String kind, Metadata metadata, ComplianceProfileSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private ComplianceProfileSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(ComplianceProfileSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public ComplianceProfile build() {
            return new ComplianceProfile(apiVersion, kind, metadata, spec);
        }
    }
}
