// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * MAPPED or EVIDENCED is never a certification claim by itself. Only EXTERNALLY_ATTESTED, backed by an EvidenceProfile with independent attestation, may be shown as one.
 */
public enum ComplianceStatus {

  NOT_ASSESSED("NOT_ASSESSED"),

  MAPPED("MAPPED"),

  EVIDENCED("EVIDENCED"),

  EXTERNALLY_ATTESTED("EXTERNALLY_ATTESTED");

  private final static Map<String, ComplianceStatus> MAP;

  static {
    Map<String, ComplianceStatus> map = new HashMap<String, ComplianceStatus>();
    for ( ComplianceStatus value : ComplianceStatus.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  ComplianceStatus(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static ComplianceStatus fromString(String v) {
    return MAP.get(v);
  }

}