// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record ConnectorIntentRationale(ContractReference connectorDefinitionRef, String reason)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private ContractReference connectorDefinitionRef = null;
        private String reason = "";


        public Builder connectorDefinitionRef(ContractReference connectorDefinitionRef) {
            this.connectorDefinitionRef = Objects.requireNonNull(connectorDefinitionRef);
            return this;
        }

        public Builder reason(String reason) {
            this.reason = Objects.requireNonNull(reason);
            return this;
        }

    public ConnectorIntentRationale build() {
            return new ConnectorIntentRationale(connectorDefinitionRef, reason);
        }
    }
}
