// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.time.ZonedDateTime;
import java.util.List;
import java.util.List;
import java.util.List;
import java.util.Objects;


public record ConnectorAppraisalSpec(String ownerRealm, ContractReference mcpBundleRef, String appraisedDigest, ContractReference appraisedByRoleDefinitionRef, ContractReference verifiedByRoleDefinitionRef, ZonedDateTime appraisedAt, AppraisalVerdict verdict, List<String> conditions, AppraisalDimensions dimensions, List<UpstreamToolEntry> upstreamInventory, List<String> evidenceRefs)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ownerRealm = "";
        private ContractReference mcpBundleRef = null;
        private String appraisedDigest = "";
        private ContractReference appraisedByRoleDefinitionRef = null;
        private ContractReference verifiedByRoleDefinitionRef = null;
        private ZonedDateTime appraisedAt = null;
        private AppraisalVerdict verdict = null;
        private List<String> conditions = List.of();
        private AppraisalDimensions dimensions = null;
        private List<UpstreamToolEntry> upstreamInventory = List.of();
        private List<String> evidenceRefs = List.of();


        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder mcpBundleRef(ContractReference mcpBundleRef) {
            this.mcpBundleRef = Objects.requireNonNull(mcpBundleRef);
            return this;
        }

        public Builder appraisedDigest(String appraisedDigest) {
            this.appraisedDigest = Objects.requireNonNull(appraisedDigest);
            return this;
        }

        public Builder appraisedByRoleDefinitionRef(ContractReference appraisedByRoleDefinitionRef) {
            this.appraisedByRoleDefinitionRef = Objects.requireNonNull(appraisedByRoleDefinitionRef);
            return this;
        }

        public Builder verifiedByRoleDefinitionRef(ContractReference verifiedByRoleDefinitionRef) {
            this.verifiedByRoleDefinitionRef = Objects.requireNonNull(verifiedByRoleDefinitionRef);
            return this;
        }

        public Builder appraisedAt(ZonedDateTime appraisedAt) {
            this.appraisedAt = Objects.requireNonNull(appraisedAt);
            return this;
        }

        public Builder verdict(AppraisalVerdict verdict) {
            this.verdict = Objects.requireNonNull(verdict);
            return this;
        }

        public Builder conditions(List<String> conditions) {
            this.conditions = Objects.requireNonNull(conditions);
            return this;
        }

        public Builder dimensions(AppraisalDimensions dimensions) {
            this.dimensions = Objects.requireNonNull(dimensions);
            return this;
        }

        public Builder upstreamInventory(List<UpstreamToolEntry> upstreamInventory) {
            this.upstreamInventory = Objects.requireNonNull(upstreamInventory);
            return this;
        }

        public Builder evidenceRefs(List<String> evidenceRefs) {
            this.evidenceRefs = Objects.requireNonNull(evidenceRefs);
            return this;
        }

    public ConnectorAppraisalSpec build() {
            return new ConnectorAppraisalSpec(ownerRealm, mcpBundleRef, appraisedDigest, appraisedByRoleDefinitionRef, verifiedByRoleDefinitionRef, appraisedAt, verdict, conditions, dimensions, upstreamInventory, evidenceRefs);
        }
    }
}
