// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Observed result and evidence of a connector test case execution.
 */
public record ConnectorTestResult(String planId, String testCaseId, String status, String actualOutputDigest, Integer executionTimeMs, String sanitizedEvidence, String executedAt)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String planId = "";
        private String testCaseId = "";
        private String status = "";
        private String actualOutputDigest = "";
        private Integer executionTimeMs = null;
        private String sanitizedEvidence = "";
        private String executedAt = "";


        public Builder planId(String planId) {
            this.planId = Objects.requireNonNull(planId);
            return this;
        }

        public Builder testCaseId(String testCaseId) {
            this.testCaseId = Objects.requireNonNull(testCaseId);
            return this;
        }

        public Builder status(String status) {
            this.status = Objects.requireNonNull(status);
            return this;
        }

        public Builder actualOutputDigest(String actualOutputDigest) {
            this.actualOutputDigest = Objects.requireNonNull(actualOutputDigest);
            return this;
        }

        public Builder executionTimeMs(Integer executionTimeMs) {
            this.executionTimeMs = Objects.requireNonNull(executionTimeMs);
            return this;
        }

        public Builder sanitizedEvidence(String sanitizedEvidence) {
            this.sanitizedEvidence = Objects.requireNonNull(sanitizedEvidence);
            return this;
        }

        public Builder executedAt(String executedAt) {
            this.executedAt = Objects.requireNonNull(executedAt);
            return this;
        }

    public ConnectorTestResult build() {
            return new ConnectorTestResult(planId, testCaseId, status, actualOutputDigest, executionTimeMs, sanitizedEvidence, executedAt);
        }
    }
}
