// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;


public record ConnectorPackageCertificationSpec(ContractReference connectorPackageRef, String packageDigest, String imageDigest, String signatureDigest, String sbomDigest, String provenanceDigest, String licenceDigest, String testDigest, List<String> supportedTransportDigests)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private ContractReference connectorPackageRef = null;
        private String packageDigest = "";
        private String imageDigest = "";
        private String signatureDigest = "";
        private String sbomDigest = "";
        private String provenanceDigest = "";
        private String licenceDigest = "";
        private String testDigest = "";
        private List<String> supportedTransportDigests = List.of();


        public Builder connectorPackageRef(ContractReference connectorPackageRef) {
            this.connectorPackageRef = Objects.requireNonNull(connectorPackageRef);
            return this;
        }

        public Builder packageDigest(String packageDigest) {
            this.packageDigest = Objects.requireNonNull(packageDigest);
            return this;
        }

        public Builder imageDigest(String imageDigest) {
            this.imageDigest = Objects.requireNonNull(imageDigest);
            return this;
        }

        public Builder signatureDigest(String signatureDigest) {
            this.signatureDigest = Objects.requireNonNull(signatureDigest);
            return this;
        }

        public Builder sbomDigest(String sbomDigest) {
            this.sbomDigest = Objects.requireNonNull(sbomDigest);
            return this;
        }

        public Builder provenanceDigest(String provenanceDigest) {
            this.provenanceDigest = Objects.requireNonNull(provenanceDigest);
            return this;
        }

        public Builder licenceDigest(String licenceDigest) {
            this.licenceDigest = Objects.requireNonNull(licenceDigest);
            return this;
        }

        public Builder testDigest(String testDigest) {
            this.testDigest = Objects.requireNonNull(testDigest);
            return this;
        }

        public Builder supportedTransportDigests(List<String> supportedTransportDigests) {
            this.supportedTransportDigests = Objects.requireNonNull(supportedTransportDigests);
            return this;
        }

    public ConnectorPackageCertificationSpec build() {
            return new ConnectorPackageCertificationSpec(connectorPackageRef, packageDigest, imageDigest, signatureDigest, sbomDigest, provenanceDigest, licenceDigest, testDigest, supportedTransportDigests);
        }
    }
}
