// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;

/**
 * Specification for a ConnectorIntegration contract.
 */
public record ConnectorIntegrationSpec(String ownerRealm, String category, List<String> memberConnectorRefs, String description)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ownerRealm = "";
        private String category = "";
        private List<String> memberConnectorRefs = List.of();
        private String description = "";


        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder category(String category) {
            this.category = Objects.requireNonNull(category);
            return this;
        }

        public Builder memberConnectorRefs(List<String> memberConnectorRefs) {
            this.memberConnectorRefs = Objects.requireNonNull(memberConnectorRefs);
            return this;
        }

        public Builder description(String description) {
            this.description = Objects.requireNonNull(description);
            return this;
        }

    public ConnectorIntegrationSpec build() {
            return new ConnectorIntegrationSpec(ownerRealm, category, memberConnectorRefs, description);
        }
    }
}
