// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * A single test case in a connector verification plan.
 */
public record ConnectorTestCase(String testCaseId, String operationId, String effectClass, SchemaBoundPayload inputPayload, String expectedOutputDigest, SchemaBoundPayload rollbackPayload)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String testCaseId = "";
        private String operationId = "";
        private String effectClass = "";
        private SchemaBoundPayload inputPayload = null;
        private String expectedOutputDigest = "";
        private SchemaBoundPayload rollbackPayload = null;


        public Builder testCaseId(String testCaseId) {
            this.testCaseId = Objects.requireNonNull(testCaseId);
            return this;
        }

        public Builder operationId(String operationId) {
            this.operationId = Objects.requireNonNull(operationId);
            return this;
        }

        public Builder effectClass(String effectClass) {
            this.effectClass = Objects.requireNonNull(effectClass);
            return this;
        }

        public Builder inputPayload(SchemaBoundPayload inputPayload) {
            this.inputPayload = Objects.requireNonNull(inputPayload);
            return this;
        }

        public Builder expectedOutputDigest(String expectedOutputDigest) {
            this.expectedOutputDigest = Objects.requireNonNull(expectedOutputDigest);
            return this;
        }

        public Builder rollbackPayload(SchemaBoundPayload rollbackPayload) {
            this.rollbackPayload = Objects.requireNonNull(rollbackPayload);
            return this;
        }

    public ConnectorTestCase build() {
            return new ConnectorTestCase(testCaseId, operationId, effectClass, inputPayload, expectedOutputDigest, rollbackPayload);
        }
    }
}
