// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.Objects;

/**
 * Structured output of a DIALOGUE_COLLECT step capturing what connectors the assistant proposes in response to the user's stated intent (AssistedJourneyStep.promptRef, PromptOutput form: STRUCTURED). A proposal, never a grant or a configuration: selectedConnectorRefs must be drawn only from the realm's declared ConnectorDefinition catalog supplied as the prompt's RAG context (the same corpus ContractLoader loads for CapabilityGatewayService), never invented by the model. The user still confirms selection explicitly; this class only bounds what the model may say back.
 */
public record ConnectorIntentProposal(List<ContractReference> selectedConnectorDefinitionRefs, List<ConnectorIntentRationale> rationale, String openQuestion)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private List<ContractReference> selectedConnectorDefinitionRefs = List.of();
        private List<ConnectorIntentRationale> rationale = List.of();
        private String openQuestion = "";


        public Builder selectedConnectorDefinitionRefs(List<ContractReference> selectedConnectorDefinitionRefs) {
            this.selectedConnectorDefinitionRefs = Objects.requireNonNull(selectedConnectorDefinitionRefs);
            return this;
        }

        public Builder rationale(List<ConnectorIntentRationale> rationale) {
            this.rationale = Objects.requireNonNull(rationale);
            return this;
        }

        public Builder openQuestion(String openQuestion) {
            this.openQuestion = Objects.requireNonNull(openQuestion);
            return this;
        }

    public ConnectorIntentProposal build() {
            return new ConnectorIntentProposal(selectedConnectorDefinitionRefs, rationale, openQuestion);
        }
    }
}
