// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;


public record ConnectorDefinitionSpec(String ownerRealm, ConnectorLifecycle lifecycle, ConnectorTransport transport, String configurationRef, ContractReference mcpBundleRef, ContractReference remoteMcpServiceRef, ContractReference connectorPackageRef, ConnectorPlacement placement, List<ConnectorOperation> operations)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ownerRealm = "";
        private ConnectorLifecycle lifecycle = null;
        private ConnectorTransport transport = null;
        private String configurationRef = "";
        private ContractReference mcpBundleRef = null;
        private ContractReference remoteMcpServiceRef = null;
        private ContractReference connectorPackageRef = null;
        private ConnectorPlacement placement = null;
        private List<ConnectorOperation> operations = List.of();


        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder lifecycle(ConnectorLifecycle lifecycle) {
            this.lifecycle = Objects.requireNonNull(lifecycle);
            return this;
        }

        public Builder transport(ConnectorTransport transport) {
            this.transport = Objects.requireNonNull(transport);
            return this;
        }

        public Builder configurationRef(String configurationRef) {
            this.configurationRef = Objects.requireNonNull(configurationRef);
            return this;
        }

        public Builder mcpBundleRef(ContractReference mcpBundleRef) {
            this.mcpBundleRef = Objects.requireNonNull(mcpBundleRef);
            return this;
        }

        public Builder remoteMcpServiceRef(ContractReference remoteMcpServiceRef) {
            this.remoteMcpServiceRef = Objects.requireNonNull(remoteMcpServiceRef);
            return this;
        }

        public Builder connectorPackageRef(ContractReference connectorPackageRef) {
            this.connectorPackageRef = Objects.requireNonNull(connectorPackageRef);
            return this;
        }

        public Builder placement(ConnectorPlacement placement) {
            this.placement = Objects.requireNonNull(placement);
            return this;
        }

        public Builder operations(List<ConnectorOperation> operations) {
            this.operations = Objects.requireNonNull(operations);
            return this;
        }

    public ConnectorDefinitionSpec build() {
            return new ConnectorDefinitionSpec(ownerRealm, lifecycle, transport, configurationRef, mcpBundleRef, remoteMcpServiceRef, connectorPackageRef, placement, operations);
        }
    }
}
