// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.List;
import java.util.Objects;

/**
 * Structured output of a DIALOGUE_COLLECT step (operator-connector-recommendation-handoff AC2) distinguishing three kinds of connector need for a stated project purpose: a Realm connector that already exists, an MCP catalogue entry that is sourced but not yet installed, and a need with no governed candidate at all. Never a grant, install, activation or invocation -- the user still confirms a selection explicitly, and only create-connector's own journey can turn a sourcedCatalogCandidates entry into a declared connector. availableConnectorDefinitionRefs entries must resolve in the Realm's own declared catalog (supplied as connectorCatalog); sourcedCatalogCandidates entries must resolve in the supplied mcpCatalogCandidates generation; unresolvedAccessNeeds carries plain text only, with no ref or catalogue id slot, so it can never itself assert that a connector product exists.
 */
public record ConnectorAccessProposal(List<RecommendedConnectorReference> availableConnectorDefinitionRefs, List<RecommendedCatalogCandidate> sourcedCatalogCandidates, List<String> unresolvedAccessNeeds)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private List<RecommendedConnectorReference> availableConnectorDefinitionRefs = List.of();
        private List<RecommendedCatalogCandidate> sourcedCatalogCandidates = List.of();
        private List<String> unresolvedAccessNeeds = List.of();


        public Builder availableConnectorDefinitionRefs(List<RecommendedConnectorReference> availableConnectorDefinitionRefs) {
            this.availableConnectorDefinitionRefs = Objects.requireNonNull(availableConnectorDefinitionRefs);
            return this;
        }

        public Builder sourcedCatalogCandidates(List<RecommendedCatalogCandidate> sourcedCatalogCandidates) {
            this.sourcedCatalogCandidates = Objects.requireNonNull(sourcedCatalogCandidates);
            return this;
        }

        public Builder unresolvedAccessNeeds(List<String> unresolvedAccessNeeds) {
            this.unresolvedAccessNeeds = Objects.requireNonNull(unresolvedAccessNeeds);
            return this;
        }

    public ConnectorAccessProposal build() {
            return new ConnectorAccessProposal(availableConnectorDefinitionRefs, sourcedCatalogCandidates, unresolvedAccessNeeds);
        }
    }
}
