// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;

/**
 * Deterministic test plan for verifying connector operations on a target machine.
 */
public record ConnectorTestPlan(String planId, String connectorRef, String targetMachineRef, List<ConnectorTestCase> testCases, String planDigest)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String planId = "";
        private String connectorRef = "";
        private String targetMachineRef = "";
        private List<ConnectorTestCase> testCases = List.of();
        private String planDigest = "";


        public Builder planId(String planId) {
            this.planId = Objects.requireNonNull(planId);
            return this;
        }

        public Builder connectorRef(String connectorRef) {
            this.connectorRef = Objects.requireNonNull(connectorRef);
            return this;
        }

        public Builder targetMachineRef(String targetMachineRef) {
            this.targetMachineRef = Objects.requireNonNull(targetMachineRef);
            return this;
        }

        public Builder testCases(List<ConnectorTestCase> testCases) {
            this.testCases = Objects.requireNonNull(testCases);
            return this;
        }

        public Builder planDigest(String planDigest) {
            this.planDigest = Objects.requireNonNull(planDigest);
            return this;
        }

    public ConnectorTestPlan build() {
            return new ConnectorTestPlan(planId, connectorRef, targetMachineRef, testCases, planDigest);
        }
    }
}
