// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * What the work spent, in units ResourceBudget declares. Keys held identical to ResourceBudget.spec.limits by scripts/validate-integration-contracts.py today; Rego takes over that cross-check.
 */
public record ConsumptionReport(Integer tokens, Float estimatedCostEur, String wallClock, Integer modelCalls, Integer toolCalls)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private Integer tokens = null;
        private Float estimatedCostEur = null;
        private String wallClock = "";
        private Integer modelCalls = null;
        private Integer toolCalls = null;


        public Builder tokens(Integer tokens) {
            this.tokens = Objects.requireNonNull(tokens);
            return this;
        }

        public Builder estimatedCostEur(Float estimatedCostEur) {
            this.estimatedCostEur = Objects.requireNonNull(estimatedCostEur);
            return this;
        }

        public Builder wallClock(String wallClock) {
            this.wallClock = Objects.requireNonNull(wallClock);
            return this;
        }

        public Builder modelCalls(Integer modelCalls) {
            this.modelCalls = Objects.requireNonNull(modelCalls);
            return this;
        }

        public Builder toolCalls(Integer toolCalls) {
            this.toolCalls = Objects.requireNonNull(toolCalls);
            return this;
        }

    public ConsumptionReport build() {
            return new ConsumptionReport(tokens, estimatedCostEur, wallClock, modelCalls, toolCalls);
        }
    }
}
