// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Internal controls, reusable across ComplianceProfiles (docs/concepts/positionnement-conceptuel.md#conformite-et-auditabilite-par-construction). Split out of the source GovernanceOverlay's inline `controls[]` array, so a control is declared once and mapped from many profiles rather than copy-pasted per referential.
 */
public record ControlCatalog(String apiVersion, String kind, Metadata metadata, ControlCatalogSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private ControlCatalogSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(ControlCatalogSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public ControlCatalog build() {
            return new ControlCatalog(apiVersion, kind, metadata, spec);
        }
    }
}
