// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum ContextRetrievalMode {

  CURRENT_CONTEXT("CURRENT_CONTEXT");

  private final static Map<String, ContextRetrievalMode> MAP;

  static {
    Map<String, ContextRetrievalMode> map = new HashMap<String, ContextRetrievalMode>();
    for ( ContextRetrievalMode value : ContextRetrievalMode.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  ContextRetrievalMode(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static ContextRetrievalMode fromString(String v) {
    return MAP.get(v);
  }

}