// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * The closed set of ConversationService turn kinds. Declared on the PromptTemplate that serves it, so the platform resolves task -> prompt from the contract instead of naming the PromptTemplate id in a switch.
 */
public enum ConversationTask {

  COORDINATE("COORDINATE"),

  DELIBERATE("DELIBERATE"),

  COMPACT("COMPACT"),

  STRUCTURED_INTENT("STRUCTURED_INTENT"),

  INTAKE("INTAKE");

  private final static Map<String, ConversationTask> MAP;

  static {
    Map<String, ConversationTask> map = new HashMap<String, ConversationTask>();
    for ( ConversationTask value : ConversationTask.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  ConversationTask(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static ConversationTask fromString(String v) {
    return MAP.get(v);
  }

}