// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum CoordinationProfileName {

  FAST_LANE("FAST_LANE"),

  VERTICAL_COMMAND("VERTICAL_COMMAND"),

  COOPERATIVE_ADAPTIVE("COOPERATIVE_ADAPTIVE"),

  ASSURANCE_CELL("ASSURANCE_CELL");

  private final static Map<String, CoordinationProfileName> MAP;

  static {
    Map<String, CoordinationProfileName> map = new HashMap<String, CoordinationProfileName>();
    for ( CoordinationProfileName value : CoordinationProfileName.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  CoordinationProfileName(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static CoordinationProfileName fromString(String v) {
    return MAP.get(v);
  }

}