// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum CostClass {

  LOW("LOW"),

  MEDIUM("MEDIUM"),

  HIGH("HIGH");

  private final static Map<String, CostClass> MAP;

  static {
    Map<String, CostClass> map = new HashMap<String, CostClass>();
    for ( CostClass value : CostClass.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  CostClass(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static CostClass fromString(String v) {
    return MAP.get(v);
  }

}