// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * How a ProviderAccount's activated credential is carried on an outbound request through provider-egress. Matches RequestShape's per-protocol header choice one for one.
 */
public enum CredentialHeaderStyle {

  AUTHORIZATION_BEARER("AUTHORIZATION_BEARER"),

  X_API_KEY("X_API_KEY"),

  X_GOOG_API_KEY("X_GOOG_API_KEY");

  private final static Map<String, CredentialHeaderStyle> MAP;

  static {
    Map<String, CredentialHeaderStyle> map = new HashMap<String, CredentialHeaderStyle>();
    for ( CredentialHeaderStyle value : CredentialHeaderStyle.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  CredentialHeaderStyle(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static CredentialHeaderStyle fromString(String v) {
    return MAP.get(v);
  }

}