// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.time.LocalDate;
import java.util.Objects;


public record DataProtectionImpactAssessment(String necessityAndProportionality, List<String> risksToDataSubjects, List<String> mitigations, LocalDate assessedAt, String reviewer)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String necessityAndProportionality = "";
        private List<String> risksToDataSubjects = List.of();
        private List<String> mitigations = List.of();
        private LocalDate assessedAt = null;
        private String reviewer = "";


        public Builder necessityAndProportionality(String necessityAndProportionality) {
            this.necessityAndProportionality = Objects.requireNonNull(necessityAndProportionality);
            return this;
        }

        public Builder risksToDataSubjects(List<String> risksToDataSubjects) {
            this.risksToDataSubjects = Objects.requireNonNull(risksToDataSubjects);
            return this;
        }

        public Builder mitigations(List<String> mitigations) {
            this.mitigations = Objects.requireNonNull(mitigations);
            return this;
        }

        public Builder assessedAt(LocalDate assessedAt) {
            this.assessedAt = Objects.requireNonNull(assessedAt);
            return this;
        }

        public Builder reviewer(String reviewer) {
            this.reviewer = Objects.requireNonNull(reviewer);
            return this;
        }

    public DataProtectionImpactAssessment build() {
            return new DataProtectionImpactAssessment(necessityAndProportionality, risksToDataSubjects, mitigations, assessedAt, reviewer);
        }
    }
}
