// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Widest audience a document or capability's data may be served to. Kept as one enum for audience/publication checks: see InformationClassification and the classification/compartment/release-transformation split below for the narrower declassification-transformation concept. DataScope itself is not retired, since dozens of existing schemas key off it for a single publication-boundary check, and splitting it everywhere at once would be overreach for that one check.
 */
public enum DataScope {

  PUBLISHED_SUMMARY("PUBLISHED_SUMMARY"),

  TYPED_ATTENTION_ONLY("TYPED_ATTENTION_ONLY"),

  PROJECT_SCOPED("PROJECT_SCOPED"),

  REALM_PRIVATE("REALM_PRIVATE"),

  ORGANIZATION_ONLY("ORGANIZATION_ONLY");

  private final static Map<String, DataScope> MAP;

  static {
    Map<String, DataScope> map = new HashMap<String, DataScope>();
    for ( DataScope value : DataScope.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  DataScope(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static DataScope fromString(String v) {
    return MAP.get(v);
  }

}