// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum DeploymentTarget {

  DOCKER_COMPOSE("docker-compose"),

  SYSTEMD("systemd"),

  KUBERNETES("kubernetes"),

  NONE("none");

  private final static Map<String, DeploymentTarget> MAP;

  static {
    Map<String, DeploymentTarget> map = new HashMap<String, DeploymentTarget>();
    for ( DeploymentTarget value : DeploymentTarget.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  DeploymentTarget(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static DeploymentTarget fromString(String v) {
    return MAP.get(v);
  }

}