// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record DiagnosticDimension(String dimension, String rationale)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String dimension = "";
        private String rationale = "";


        public Builder dimension(String dimension) {
            this.dimension = Objects.requireNonNull(dimension);
            return this;
        }

        public Builder rationale(String rationale) {
            this.rationale = Objects.requireNonNull(rationale);
            return this;
        }

    public DiagnosticDimension build() {
            return new DiagnosticDimension(dimension, rationale);
        }
    }
}
