// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record DispositionRule(String id, DispositionMatch match, DispositionOutcome outcome)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String id = "";
        private DispositionMatch match = null;
        private DispositionOutcome outcome = null;


        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }

        public Builder match(DispositionMatch match) {
            this.match = Objects.requireNonNull(match);
            return this;
        }

        public Builder outcome(DispositionOutcome outcome) {
            this.outcome = Objects.requireNonNull(outcome);
            return this;
        }

    public DispositionRule build() {
            return new DispositionRule(id, match, outcome);
        }
    }
}
