// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * A YAML document with ${placeholder} scalars, rendered into the contract a journey proposes. The body is one string rather than a typed nesting because the shape it renders is the shape of whichever kind the journey emits -- the same reason a step payload with no generated class declares payloadSchemaRef against a raw JSON Schema (projection.yaml). Substitution happens after the body is parsed, so a placeholder standing alone as a value may be filled by a list or a mapping, not only by a scalar.
 */
public record DocumentTemplate(String apiVersion, String kind, Metadata metadata, DocumentTemplateBody spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private DocumentTemplateBody spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(DocumentTemplateBody spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public DocumentTemplate build() {
            return new DocumentTemplate(apiVersion, kind, metadata, spec);
        }
    }
}
