// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record DocumentationRoot(String path, DataScope maximumAudience)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String path = "";
        private DataScope maximumAudience = null;


        public Builder path(String path) {
            this.path = Objects.requireNonNull(path);
            return this;
        }

        public Builder maximumAudience(DataScope maximumAudience) {
            this.maximumAudience = Objects.requireNonNull(maximumAudience);
            return this;
        }

    public DocumentationRoot build() {
            return new DocumentationRoot(path, maximumAudience);
        }
    }
}
