// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record DocumentTemplateBody(String renders, String body)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String renders = "";
        private String body = "";


        public Builder renders(String renders) {
            this.renders = Objects.requireNonNull(renders);
            return this;
        }

        public Builder body(String body) {
            this.body = Objects.requireNonNull(body);
            return this;
        }

    public DocumentTemplateBody build() {
            return new DocumentTemplateBody(renders, body);
        }
    }
}
