// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Recognized-state lifecycle of an EffectBatch, the approval and recovery unit for owner-approved external-effect lines.
 */
public enum EffectBatchStatus {

  DRAFT("DRAFT"),

  AWAITING_APPROVAL("AWAITING_APPROVAL"),

  APPROVED("APPROVED"),

  DISPATCHING("DISPATCHING"),

  COMPLETED("COMPLETED"),

  PAUSED("PAUSED"),

  CANCELLED("CANCELLED");

  private final static Map<String, EffectBatchStatus> MAP;

  static {
    Map<String, EffectBatchStatus> map = new HashMap<String, EffectBatchStatus>();
    for ( EffectBatchStatus value : EffectBatchStatus.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  EffectBatchStatus(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static EffectBatchStatus fromString(String v) {
    return MAP.get(v);
  }

}