// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record EffortRungSpec(ReasoningEffort rung, String modelAlias, ProviderNativeEffort nativeEffort)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private ReasoningEffort rung = null;
        private String modelAlias = "";
        private ProviderNativeEffort nativeEffort = null;


        public Builder rung(ReasoningEffort rung) {
            this.rung = Objects.requireNonNull(rung);
            return this;
        }

        public Builder modelAlias(String modelAlias) {
            this.modelAlias = Objects.requireNonNull(modelAlias);
            return this;
        }

        public Builder nativeEffort(ProviderNativeEffort nativeEffort) {
            this.nativeEffort = Objects.requireNonNull(nativeEffort);
            return this;
        }

    public EffortRungSpec build() {
            return new EffortRungSpec(rung, modelAlias, nativeEffort);
        }
    }
}
