// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record EngagementTermination(String maximumDuration, boolean allowEarlyTermination)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String maximumDuration = "";
        private boolean allowEarlyTermination = false;


        public Builder maximumDuration(String maximumDuration) {
            this.maximumDuration = Objects.requireNonNull(maximumDuration);
            return this;
        }

        public Builder allowEarlyTermination(boolean allowEarlyTermination) {
            this.allowEarlyTermination = Objects.requireNonNull(allowEarlyTermination);
            return this;
        }

    public EngagementTermination build() {
            return new EngagementTermination(maximumDuration, allowEarlyTermination);
        }
    }
}
