// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum EntitlementHolder {

  PRINCIPAL("PRINCIPAL"),

  ORGANIZATION("ORGANIZATION");

  private final static Map<String, EntitlementHolder> MAP;

  static {
    Map<String, EntitlementHolder> map = new HashMap<String, EntitlementHolder>();
    for ( EntitlementHolder value : EntitlementHolder.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  EntitlementHolder(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static EntitlementHolder fromString(String v) {
    return MAP.get(v);
  }

}