// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record EntitlementUseContext(EntitlementVerdict verdict, TermsReview termsReview)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private EntitlementVerdict verdict = null;
        private TermsReview termsReview = null;


        public Builder verdict(EntitlementVerdict verdict) {
            this.verdict = Objects.requireNonNull(verdict);
            return this;
        }

        public Builder termsReview(TermsReview termsReview) {
            this.termsReview = Objects.requireNonNull(termsReview);
            return this;
        }

    public EntitlementUseContext build() {
            return new EntitlementUseContext(verdict, termsReview);
        }
    }
}
