// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * The type, source, freshness, independence, and retention an assessment's evidence must meet. Split out of GovernanceOverlay. Carries the DPIA (RGPD art. 35) alongside the pre-existing evidence-quality fields -- an impact assessment is itself a form of evidence about the system, not a separate concept.
 */
public record EvidenceProfile(String apiVersion, String kind, Metadata metadata, EvidenceProfileSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private EvidenceProfileSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(EvidenceProfileSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public EvidenceProfile build() {
            return new EvidenceProfile(apiVersion, kind, metadata, spec);
        }
    }
}
