// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.time.ZonedDateTime;
import java.util.Objects;

/**
 * Append-only sanitized execution observation linked to one WorkerInvocation.
 */
public record EvidenceRecord(String id, String ownerRealm, String workerInvocationRef, String eventKind, String eventSha256, boolean contentSanitized, ZonedDateTime capturedAt)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String id = "";
        private String ownerRealm = "";
        private String workerInvocationRef = "";
        private String eventKind = "";
        private String eventSha256 = "";
        private boolean contentSanitized = false;
        private ZonedDateTime capturedAt = null;


        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }

        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder workerInvocationRef(String workerInvocationRef) {
            this.workerInvocationRef = Objects.requireNonNull(workerInvocationRef);
            return this;
        }

        public Builder eventKind(String eventKind) {
            this.eventKind = Objects.requireNonNull(eventKind);
            return this;
        }

        public Builder eventSha256(String eventSha256) {
            this.eventSha256 = Objects.requireNonNull(eventSha256);
            return this;
        }

        public Builder contentSanitized(boolean contentSanitized) {
            this.contentSanitized = Objects.requireNonNull(contentSanitized);
            return this;
        }

        public Builder capturedAt(ZonedDateTime capturedAt) {
            this.capturedAt = Objects.requireNonNull(capturedAt);
            return this;
        }

    public EvidenceRecord build() {
            return new EvidenceRecord(id, ownerRealm, workerInvocationRef, eventKind, eventSha256, contentSanitized, capturedAt);
        }
    }
}
