// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;


public record EvidenceProfileSpec(String ownerRealm, String evidenceType, String source, String requiredFreshness, AssuranceLevel requiredIndependence, String retention, String claimCoverage, String method, String sourceDependence, List<String> defeaters, DataProtectionImpactAssessment dpia)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ownerRealm = "";
        private String evidenceType = "";
        private String source = "";
        private String requiredFreshness = "";
        private AssuranceLevel requiredIndependence = null;
        private String retention = "";
        private String claimCoverage = "";
        private String method = "";
        private String sourceDependence = "";
        private List<String> defeaters = List.of();
        private DataProtectionImpactAssessment dpia = null;


        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder evidenceType(String evidenceType) {
            this.evidenceType = Objects.requireNonNull(evidenceType);
            return this;
        }

        public Builder source(String source) {
            this.source = Objects.requireNonNull(source);
            return this;
        }

        public Builder requiredFreshness(String requiredFreshness) {
            this.requiredFreshness = Objects.requireNonNull(requiredFreshness);
            return this;
        }

        public Builder requiredIndependence(AssuranceLevel requiredIndependence) {
            this.requiredIndependence = Objects.requireNonNull(requiredIndependence);
            return this;
        }

        public Builder retention(String retention) {
            this.retention = Objects.requireNonNull(retention);
            return this;
        }

        public Builder claimCoverage(String claimCoverage) {
            this.claimCoverage = Objects.requireNonNull(claimCoverage);
            return this;
        }

        public Builder method(String method) {
            this.method = Objects.requireNonNull(method);
            return this;
        }

        public Builder sourceDependence(String sourceDependence) {
            this.sourceDependence = Objects.requireNonNull(sourceDependence);
            return this;
        }

        public Builder defeaters(List<String> defeaters) {
            this.defeaters = Objects.requireNonNull(defeaters);
            return this;
        }

        public Builder dpia(DataProtectionImpactAssessment dpia) {
            this.dpia = Objects.requireNonNull(dpia);
            return this;
        }

    public EvidenceProfileSpec build() {
            return new EvidenceProfileSpec(ownerRealm, evidenceType, source, requiredFreshness, requiredIndependence, retention, claimCoverage, method, sourceDependence, defeaters, dpia);
        }
    }
}
