// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;

/**
 * Ephemeral sandbox execution lease bound to a machine, WorkOrder, SHA, and contract digest.
 */
public record ExecutionCellLease(String leaseId, String machineId, String workOrderId, String gitCommitSha, String contractDigest, String status, String grantedAt, String expiresAt, List<String> delegatedSecretBindings)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String leaseId = "";
        private String machineId = "";
        private String workOrderId = "";
        private String gitCommitSha = "";
        private String contractDigest = "";
        private String status = "";
        private String grantedAt = "";
        private String expiresAt = "";
        private List<String> delegatedSecretBindings = List.of();


        public Builder leaseId(String leaseId) {
            this.leaseId = Objects.requireNonNull(leaseId);
            return this;
        }

        public Builder machineId(String machineId) {
            this.machineId = Objects.requireNonNull(machineId);
            return this;
        }

        public Builder workOrderId(String workOrderId) {
            this.workOrderId = Objects.requireNonNull(workOrderId);
            return this;
        }

        public Builder gitCommitSha(String gitCommitSha) {
            this.gitCommitSha = Objects.requireNonNull(gitCommitSha);
            return this;
        }

        public Builder contractDigest(String contractDigest) {
            this.contractDigest = Objects.requireNonNull(contractDigest);
            return this;
        }

        public Builder status(String status) {
            this.status = Objects.requireNonNull(status);
            return this;
        }

        public Builder grantedAt(String grantedAt) {
            this.grantedAt = Objects.requireNonNull(grantedAt);
            return this;
        }

        public Builder expiresAt(String expiresAt) {
            this.expiresAt = Objects.requireNonNull(expiresAt);
            return this;
        }

        public Builder delegatedSecretBindings(List<String> delegatedSecretBindings) {
            this.delegatedSecretBindings = Objects.requireNonNull(delegatedSecretBindings);
            return this;
        }

    public ExecutionCellLease build() {
            return new ExecutionCellLease(leaseId, machineId, workOrderId, gitCommitSha, contractDigest, status, grantedAt, expiresAt, delegatedSecretBindings);
        }
    }
}
