// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Portable declaration of a pinned, verifiable non-AI execution environment and its finite tool inventory (execution-toolchain-contract-foundations). Describes environment sufficiency only -- never connector authority, provider selection, credential custody, or arbitrary host-shell execution; distinct from WorkerCli, which qualifies an AI CLI.
 */
public record ExecutionToolchain(String apiVersion, String kind, Metadata metadata, ExecutionToolchainSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private ExecutionToolchainSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(ExecutionToolchainSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public ExecutionToolchain build() {
            return new ExecutionToolchain(apiVersion, kind, metadata, spec);
        }
    }
}
