// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * An immutable artifact identity -- a tag or version string alone is a moving target; evidence names the bytes that ran (mirrors WorkerImage's own reasoning for a worker image).
 */
public record ExecutionToolchainArtifact(String reference, String digest)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String reference = "";
        private String digest = "";


        public Builder reference(String reference) {
            this.reference = Objects.requireNonNull(reference);
            return this;
        }

        public Builder digest(String digest) {
            this.digest = Objects.requireNonNull(digest);
            return this;
        }

    public ExecutionToolchainArtifact build() {
            return new ExecutionToolchainArtifact(reference, digest);
        }
    }
}
