// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum ExecutionLeaseKind {

  WORK_ORDER("WORK_ORDER"),

  DIALOGUE("DIALOGUE");

  private final static Map<String, ExecutionLeaseKind> MAP;

  static {
    Map<String, ExecutionLeaseKind> map = new HashMap<String, ExecutionLeaseKind>();
    for ( ExecutionLeaseKind value : ExecutionLeaseKind.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  ExecutionLeaseKind(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static ExecutionLeaseKind fromString(String v) {
    return MAP.get(v);
  }

}