// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.Objects;

/**
 * Specification for an ExecutionMachine contract.
 */
public record ExecutionMachineSpec(String ownerRealm, MachineOrigin origin, MachineEnvironment environment, MachineDesiredState desiredState, String hostDefinitionRef, List<String> installedCliRefs, List<String> installedConnectorRefs, String ansibleBaselineRef, MachineNetworkConfig network)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ownerRealm = "";
        private MachineOrigin origin = null;
        private MachineEnvironment environment = null;
        private MachineDesiredState desiredState = null;
        private String hostDefinitionRef = "";
        private List<String> installedCliRefs = List.of();
        private List<String> installedConnectorRefs = List.of();
        private String ansibleBaselineRef = "";
        private MachineNetworkConfig network = null;


        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder origin(MachineOrigin origin) {
            this.origin = Objects.requireNonNull(origin);
            return this;
        }

        public Builder environment(MachineEnvironment environment) {
            this.environment = Objects.requireNonNull(environment);
            return this;
        }

        public Builder desiredState(MachineDesiredState desiredState) {
            this.desiredState = Objects.requireNonNull(desiredState);
            return this;
        }

        public Builder hostDefinitionRef(String hostDefinitionRef) {
            this.hostDefinitionRef = Objects.requireNonNull(hostDefinitionRef);
            return this;
        }

        public Builder installedCliRefs(List<String> installedCliRefs) {
            this.installedCliRefs = Objects.requireNonNull(installedCliRefs);
            return this;
        }

        public Builder installedConnectorRefs(List<String> installedConnectorRefs) {
            this.installedConnectorRefs = Objects.requireNonNull(installedConnectorRefs);
            return this;
        }

        public Builder ansibleBaselineRef(String ansibleBaselineRef) {
            this.ansibleBaselineRef = Objects.requireNonNull(ansibleBaselineRef);
            return this;
        }

        public Builder network(MachineNetworkConfig network) {
            this.network = Objects.requireNonNull(network);
            return this;
        }

    public ExecutionMachineSpec build() {
            return new ExecutionMachineSpec(ownerRealm, origin, environment, desiredState, hostDefinitionRef, installedCliRefs, installedConnectorRefs, ansibleBaselineRef, network);
        }
    }
}
