// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;


public record ExecutionToolchainSpec(String ownerRealm, ExecutionToolchainArtifact artifact, List<ExecutionToolchainTool> tools, ConnectorLifecycle lifecycle)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ownerRealm = "";
        private ExecutionToolchainArtifact artifact = null;
        private List<ExecutionToolchainTool> tools = List.of();
        private ConnectorLifecycle lifecycle = null;


        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder artifact(ExecutionToolchainArtifact artifact) {
            this.artifact = Objects.requireNonNull(artifact);
            return this;
        }

        public Builder tools(List<ExecutionToolchainTool> tools) {
            this.tools = Objects.requireNonNull(tools);
            return this;
        }

        public Builder lifecycle(ConnectorLifecycle lifecycle) {
            this.lifecycle = Objects.requireNonNull(lifecycle);
            return this;
        }

    public ExecutionToolchainSpec build() {
            return new ExecutionToolchainSpec(ownerRealm, artifact, tools, lifecycle);
        }
    }
}
