// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * One observable tool the artifact provides, named and versioned generically -- the schema itself never names Java, Maven, an LSP or any other specific tool.
 */
public record ExecutionToolchainTool(String name, String version, String digest)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String name = "";
        private String version = "";
        private String digest = "";


        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }

        public Builder version(String version) {
            this.version = Objects.requireNonNull(version);
            return this;
        }

        public Builder digest(String digest) {
            this.digest = Objects.requireNonNull(digest);
            return this;
        }

    public ExecutionToolchainTool build() {
            return new ExecutionToolchainTool(name, version, digest);
        }
    }
}
