// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum ExecutionCellLifecycle {

  PAIRED("PAIRED"),

  ENABLED("ENABLED"),

  SUSPENDED("SUSPENDED"),

  QUARANTINED("QUARANTINED"),

  RETIRED("RETIRED");

  private final static Map<String, ExecutionCellLifecycle> MAP;

  static {
    Map<String, ExecutionCellLifecycle> map = new HashMap<String, ExecutionCellLifecycle>();
    for ( ExecutionCellLifecycle value : ExecutionCellLifecycle.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  ExecutionCellLifecycle(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static ExecutionCellLifecycle fromString(String v) {
    return MAP.get(v);
  }

}