// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;

/**
 * Ephemeral sandbox execution lease bound to a machine and immutable active contract-set digest; a WORK_ORDER lease carries a task and SHA, while a DIALOGUE lease carries a conversation turn.
 */
public record ExecutionCellLease(String leaseId, String machineId, ExecutionLeaseKind leaseKind, String workOrderId, String gitCommitSha, String conversationTurnId, ContractReference providerAccountRef, String contractSetDigest, String status, String grantedAt, String expiresAt, List<String> delegatedSecretBindings)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String leaseId = "";
        private String machineId = "";
        private ExecutionLeaseKind leaseKind = null;
        private String workOrderId = "";
        private String gitCommitSha = "";
        private String conversationTurnId = "";
        private ContractReference providerAccountRef = null;
        private String contractSetDigest = "";
        private String status = "";
        private String grantedAt = "";
        private String expiresAt = "";
        private List<String> delegatedSecretBindings = List.of();


        public Builder leaseId(String leaseId) {
            this.leaseId = Objects.requireNonNull(leaseId);
            return this;
        }

        public Builder machineId(String machineId) {
            this.machineId = Objects.requireNonNull(machineId);
            return this;
        }

        public Builder leaseKind(ExecutionLeaseKind leaseKind) {
            this.leaseKind = Objects.requireNonNull(leaseKind);
            return this;
        }

        public Builder workOrderId(String workOrderId) {
            this.workOrderId = Objects.requireNonNull(workOrderId);
            return this;
        }

        public Builder gitCommitSha(String gitCommitSha) {
            this.gitCommitSha = Objects.requireNonNull(gitCommitSha);
            return this;
        }

        public Builder conversationTurnId(String conversationTurnId) {
            this.conversationTurnId = Objects.requireNonNull(conversationTurnId);
            return this;
        }

        public Builder providerAccountRef(ContractReference providerAccountRef) {
            this.providerAccountRef = Objects.requireNonNull(providerAccountRef);
            return this;
        }

        public Builder contractSetDigest(String contractSetDigest) {
            this.contractSetDigest = Objects.requireNonNull(contractSetDigest);
            return this;
        }

        public Builder status(String status) {
            this.status = Objects.requireNonNull(status);
            return this;
        }

        public Builder grantedAt(String grantedAt) {
            this.grantedAt = Objects.requireNonNull(grantedAt);
            return this;
        }

        public Builder expiresAt(String expiresAt) {
            this.expiresAt = Objects.requireNonNull(expiresAt);
            return this;
        }

        public Builder delegatedSecretBindings(List<String> delegatedSecretBindings) {
            this.delegatedSecretBindings = Objects.requireNonNull(delegatedSecretBindings);
            return this;
        }

    public ExecutionCellLease build() {
            return new ExecutionCellLease(leaseId, machineId, leaseKind, workOrderId, gitCommitSha, conversationTurnId, providerAccountRef, contractSetDigest, status, grantedAt, expiresAt, delegatedSecretBindings);
        }
    }
}
