// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum FacetCreateMode {

  LIFECYCLE_COMMAND("LIFECYCLE_COMMAND"),

  NONE("NONE");

  private final static Map<String, FacetCreateMode> MAP;

  static {
    Map<String, FacetCreateMode> map = new HashMap<String, FacetCreateMode>();
    for ( FacetCreateMode value : FacetCreateMode.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  FacetCreateMode(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static FacetCreateMode fromString(String v) {
    return MAP.get(v);
  }

}