// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record FederatedPeerSigning(String peerKeyId, String peerPublicKeySha256)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String peerKeyId = "";
        private String peerPublicKeySha256 = "";


        public Builder peerKeyId(String peerKeyId) {
            this.peerKeyId = Objects.requireNonNull(peerKeyId);
            return this;
        }

        public Builder peerPublicKeySha256(String peerPublicKeySha256) {
            this.peerPublicKeySha256 = Objects.requireNonNull(peerPublicKeySha256);
            return this;
        }

    public FederatedPeerSigning build() {
            return new FederatedPeerSigning(peerKeyId, peerPublicKeySha256);
        }
    }
}
