// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * A negotiated, namespaced protocol profile. Describes messages only and cannot grant authority.
 */
public record FederationProfile(String apiVersion, String kind, Metadata metadata, FederationProfileSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private FederationProfileSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(FederationProfileSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public FederationProfile build() {
            return new FederationProfile(apiVersion, kind, metadata, spec);
        }
    }
}
