// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;


public record FederationProfileSpec(String ownerRealm, String namespace, String version, String handlerModuleRef, List<FederationMessage> messages)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ownerRealm = "";
        private String namespace = "";
        private String version = "";
        private String handlerModuleRef = "";
        private List<FederationMessage> messages = List.of();


        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder namespace(String namespace) {
            this.namespace = Objects.requireNonNull(namespace);
            return this;
        }

        public Builder version(String version) {
            this.version = Objects.requireNonNull(version);
            return this;
        }

        public Builder handlerModuleRef(String handlerModuleRef) {
            this.handlerModuleRef = Objects.requireNonNull(handlerModuleRef);
            return this;
        }

        public Builder messages(List<FederationMessage> messages) {
            this.messages = Objects.requireNonNull(messages);
            return this;
        }

    public FederationProfileSpec build() {
            return new FederationProfileSpec(ownerRealm, namespace, version, handlerModuleRef, messages);
        }
    }
}
