// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Semantic shape of one field's value, never a component name. A front-end component registry is the only place this resolves to a concrete widget. STRUCTURED_YAML also names a WritePathEditor value (interface.yaml): same underlying shape, two different concerns -- there a write-target file format, here a field's read/edit representation -- so the shared name is deliberate, not an oversight.
 */
public enum FieldRepresentation {

  SHORT_TEXT("SHORT_TEXT"),

  MULTILINE_TEXT("MULTILINE_TEXT"),

  IDENTIFIER("IDENTIFIER"),

  ENUMERATION("ENUMERATION"),

  ENTITY_REFERENCE("ENTITY_REFERENCE"),

  ENTITY_COLLECTION("ENTITY_COLLECTION"),

  BOOLEAN_FLAG("BOOLEAN_FLAG"),

  QUANTITY("QUANTITY"),

  DURATION("DURATION"),

  TIMESTAMP("TIMESTAMP"),

  SECRET("SECRET"),

  PATH_GLOB("PATH_GLOB"),

  CAPABILITY_NAME("CAPABILITY_NAME"),

  MARKDOWN("MARKDOWN"),

  STRUCTURED_YAML("STRUCTURED_YAML");

  private final static Map<String, FieldRepresentation> MAP;

  static {
    Map<String, FieldRepresentation> map = new HashMap<String, FieldRepresentation>();
    for ( FieldRepresentation value : FieldRepresentation.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  FieldRepresentation(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static FieldRepresentation fromString(String v) {
    return MAP.get(v);
  }

}