// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Delegation is never transitive. A grant to A does not let A pass it to B.
 */
public enum ForbiddenSolicitationReach {

  RAW_MEMORY_ACCESS("raw_memory_access"),

  SECRET_ACCESS("secret_access"),

  TRANSITIVE_CAPABILITY_USE("transitive_capability_use"),

  POLICY_INSPECTION("policy_inspection"),

  CROSS_REALM_IDENTITY_RESOLUTION("cross_realm_identity_resolution");

  private final static Map<String, ForbiddenSolicitationReach> MAP;

  static {
    Map<String, ForbiddenSolicitationReach> map = new HashMap<String, ForbiddenSolicitationReach>();
    for ( ForbiddenSolicitationReach value : ForbiddenSolicitationReach.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  ForbiddenSolicitationReach(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static ForbiddenSolicitationReach fromString(String v) {
    return MAP.get(v);
  }

}