// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * GitHub is the only implemented Forge in V0, behind a Forge-neutral abstraction (canonical decision 55).
 */
public enum ForgeProvider {

  GITHUB("github"),

  GITLAB("gitlab");

  private final static Map<String, ForgeProvider> MAP;

  static {
    Map<String, ForgeProvider> map = new HashMap<String, ForgeProvider>();
    for ( ForgeProvider value : ForgeProvider.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  ForgeProvider(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static ForgeProvider fromString(String v) {
    return MAP.get(v);
  }

}