// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;


public record GoldenTaskCase(String id, TaskClass taskClass, String instruction, List<BenchmarkDimension> dimensions)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String id = "";
        private TaskClass taskClass = null;
        private String instruction = "";
        private List<BenchmarkDimension> dimensions = List.of();


        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }

        public Builder taskClass(TaskClass taskClass) {
            this.taskClass = Objects.requireNonNull(taskClass);
            return this;
        }

        public Builder instruction(String instruction) {
            this.instruction = Objects.requireNonNull(instruction);
            return this;
        }

        public Builder dimensions(List<BenchmarkDimension> dimensions) {
            this.dimensions = Objects.requireNonNull(dimensions);
            return this;
        }

    public GoldenTaskCase build() {
            return new GoldenTaskCase(id, taskClass, instruction, dimensions);
        }
    }
}
