// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum HostnameInclusion {

  INCLUDED("INCLUDED"),

  UNASSIGNED("UNASSIGNED");

  private final static Map<String, HostnameInclusion> MAP;

  static {
    Map<String, HostnameInclusion> map = new HashMap<String, HostnameInclusion>();
    for ( HostnameInclusion value : HostnameInclusion.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  HostnameInclusion(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static HostnameInclusion fromString(String v) {
    return MAP.get(v);
  }

}