// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Candidate LinkML class proposal derived from an external MCP tool schema.
 */
public record ImportedSchemaCandidate(String candidateId, String externalSchemaDigest, String proposedLinkmlClass, String transformationStrategy, String justification)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String candidateId = "";
        private String externalSchemaDigest = "";
        private String proposedLinkmlClass = "";
        private String transformationStrategy = "";
        private String justification = "";


        public Builder candidateId(String candidateId) {
            this.candidateId = Objects.requireNonNull(candidateId);
            return this;
        }

        public Builder externalSchemaDigest(String externalSchemaDigest) {
            this.externalSchemaDigest = Objects.requireNonNull(externalSchemaDigest);
            return this;
        }

        public Builder proposedLinkmlClass(String proposedLinkmlClass) {
            this.proposedLinkmlClass = Objects.requireNonNull(proposedLinkmlClass);
            return this;
        }

        public Builder transformationStrategy(String transformationStrategy) {
            this.transformationStrategy = Objects.requireNonNull(transformationStrategy);
            return this;
        }

        public Builder justification(String justification) {
            this.justification = Objects.requireNonNull(justification);
            return this;
        }

    public ImportedSchemaCandidate build() {
            return new ImportedSchemaCandidate(candidateId, externalSchemaDigest, proposedLinkmlClass, transformationStrategy, justification);
        }
    }
}
