// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Required so the loop's effect on corpus size is visible per recommendation. CONSOLIDATE and DELETE exist because an additions-only loop is the failure mode check-corpus-budget.py bounds.
 */
public enum ImprovementDirection {

  ADD("ADD"),

  CONSOLIDATE("CONSOLIDATE"),

  CORRECT("CORRECT"),

  DELETE("DELETE");

  private final static Map<String, ImprovementDirection> MAP;

  static {
    Map<String, ImprovementDirection> map = new HashMap<String, ImprovementDirection>();
    for ( ImprovementDirection value : ImprovementDirection.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  ImprovementDirection(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static ImprovementDirection fromString(String v) {
    return MAP.get(v);
  }

}