// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Closed, and every entry computable without a model from material that already exists: protocol fields, WorkOrder state, budgets, front matter and recognized state.
 */
public enum ImprovementMeasure {

  CLARIFICATION_TURNS_USED("CLARIFICATION_TURNS_USED"),

  WORK_DECLINE_RATE("WORK_DECLINE_RATE"),

  BUDGET_CONSUMPTION_RATIO("BUDGET_CONSUMPTION_RATIO"),

  ASSURANCE_SHORTFALL("ASSURANCE_SHORTFALL"),

  DOCUMENT_STALENESS("DOCUMENT_STALENESS"),

  MISSING_COMPLETION_EVIDENCE("MISSING_COMPLETION_EVIDENCE"),

  SUPERSESSION_COUNT("SUPERSESSION_COUNT"),

  CAPTURE_TO_COMPLETION_ELAPSED("CAPTURE_TO_COMPLETION_ELAPSED"),

  CORPUS_BUDGET_HEADROOM("CORPUS_BUDGET_HEADROOM"),

  NON_NORMATIVE_CITATION_RATE("NON_NORMATIVE_CITATION_RATE"),

  ATTENTION_ACTED_ON_RATIO("ATTENTION_ACTED_ON_RATIO");

  private final static Map<String, ImprovementMeasure> MAP;

  static {
    Map<String, ImprovementMeasure> map = new HashMap<String, ImprovementMeasure>();
    for ( ImprovementMeasure value : ImprovementMeasure.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  ImprovementMeasure(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static ImprovementMeasure fromString(String v) {
    return MAP.get(v);
  }

}