// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.Objects;


public record ImprovementLoopSpec(String ownerRealm, ContractReference projectRef, String purpose, List<ImprovementMeasure> measures, ContractReference synthesisPracticeRef, ContractReference assessmentProcessSpecRef, List<ImprovementTarget> targets, ImprovementCeilings ceilings)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ownerRealm = "";
        private ContractReference projectRef = null;
        private String purpose = "";
        private List<ImprovementMeasure> measures = List.of();
        private ContractReference synthesisPracticeRef = null;
        private ContractReference assessmentProcessSpecRef = null;
        private List<ImprovementTarget> targets = List.of();
        private ImprovementCeilings ceilings = null;


        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder projectRef(ContractReference projectRef) {
            this.projectRef = Objects.requireNonNull(projectRef);
            return this;
        }

        public Builder purpose(String purpose) {
            this.purpose = Objects.requireNonNull(purpose);
            return this;
        }

        public Builder measures(List<ImprovementMeasure> measures) {
            this.measures = Objects.requireNonNull(measures);
            return this;
        }

        public Builder synthesisPracticeRef(ContractReference synthesisPracticeRef) {
            this.synthesisPracticeRef = Objects.requireNonNull(synthesisPracticeRef);
            return this;
        }

        public Builder assessmentProcessSpecRef(ContractReference assessmentProcessSpecRef) {
            this.assessmentProcessSpecRef = Objects.requireNonNull(assessmentProcessSpecRef);
            return this;
        }

        public Builder targets(List<ImprovementTarget> targets) {
            this.targets = Objects.requireNonNull(targets);
            return this;
        }

        public Builder ceilings(ImprovementCeilings ceilings) {
            this.ceilings = Objects.requireNonNull(ceilings);
            return this;
        }

    public ImprovementLoopSpec build() {
            return new ImprovementLoopSpec(ownerRealm, projectRef, purpose, measures, synthesisPracticeRef, assessmentProcessSpecRef, targets, ceilings);
        }
    }
}
