// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record ImprovementCeilings(int maximumOpenRecommendations, String recommendationExpiry, boolean mayRaiseCorpusCeiling)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private int maximumOpenRecommendations = 0;
        private String recommendationExpiry = "";
        private boolean mayRaiseCorpusCeiling = false;


        public Builder maximumOpenRecommendations(int maximumOpenRecommendations) {
            this.maximumOpenRecommendations = Objects.requireNonNull(maximumOpenRecommendations);
            return this;
        }

        public Builder recommendationExpiry(String recommendationExpiry) {
            this.recommendationExpiry = Objects.requireNonNull(recommendationExpiry);
            return this;
        }

        public Builder mayRaiseCorpusCeiling(boolean mayRaiseCorpusCeiling) {
            this.mayRaiseCorpusCeiling = Objects.requireNonNull(mayRaiseCorpusCeiling);
            return this;
        }

    public ImprovementCeilings build() {
            return new ImprovementCeilings(maximumOpenRecommendations, recommendationExpiry, mayRaiseCorpusCeiling);
        }
    }
}
