// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum ImprovementState {

  OPEN("OPEN"),

  ACCEPTED("ACCEPTED"),

  REJECTED("REJECTED"),

  SUPERSEDED("SUPERSEDED"),

  EXPIRED("EXPIRED");

  private final static Map<String, ImprovementState> MAP;

  static {
    Map<String, ImprovementState> map = new HashMap<String, ImprovementState>();
    for ( ImprovementState value : ImprovementState.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  ImprovementState(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static ImprovementState fromString(String v) {
    return MAP.get(v);
  }

}