// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * ADVISORY means no automated check confirms a WorkOrder's producer and verifier are distinct actors in this realm. A declaration is not a control -- it is a claim the owner makes, and ENFORCED costs an observation and a reference to it, same as BranchProtectionState.
 */
public enum IndependentVerificationState {

  ADVISORY("ADVISORY"),

  ENFORCED("ENFORCED");

  private final static Map<String, IndependentVerificationState> MAP;

  static {
    Map<String, IndependentVerificationState> map = new HashMap<String, IndependentVerificationState>();
    for ( IndependentVerificationState value : IndependentVerificationState.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  IndependentVerificationState(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static IndependentVerificationState fromString(String v) {
    return MAP.get(v);
  }

}