// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum IntentKind {

  QUESTION("QUESTION"),

  RESEARCH("RESEARCH"),

  PROJECT_WORK("PROJECT_WORK"),

  STATUS("STATUS"),

  COMMUNICATION("COMMUNICATION"),

  OTHER("OTHER");

  private final static Map<String, IntentKind> MAP;

  static {
    Map<String, IntentKind> map = new HashMap<String, IntentKind>();
    for ( IntentKind value : IntentKind.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  IntentKind(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static IntentKind fromString(String v) {
    return MAP.get(v);
  }

}