// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum InterfaceEntity {

  REALM("Realm"),

  AGENT("Agent"),

  CHANGEPROPOSAL("ChangeProposal"),

  FORGEPROJECTION("ForgeProjection"),

  EVIDENCE("Evidence"),

  ATTENTIONITEM("AttentionItem"),

  TEAM("Team"),

  WORKORDER("WorkOrder"),

  EXECUTIONMACHINE("ExecutionMachine"),

  CLITOOL("CliTool"),

  CONNECTORPACKAGE("ConnectorPackage");

  private final static Map<String, InterfaceEntity> MAP;

  static {
    Map<String, InterfaceEntity> map = new HashMap<String, InterfaceEntity>();
    for ( InterfaceEntity value : InterfaceEntity.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  InterfaceEntity(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static InterfaceEntity fromString(String v) {
    return MAP.get(v);
  }

}