// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum JourneyVerificationCapability {

  PROVIDER_SMOKE("PROVIDER_SMOKE"),

  CLI_SMOKE("CLI_SMOKE"),

  SESSION_PAIRING("SESSION_PAIRING");

  private final static Map<String, JourneyVerificationCapability> MAP;

  static {
    Map<String, JourneyVerificationCapability> map = new HashMap<String, JourneyVerificationCapability>();
    for ( JourneyVerificationCapability value : JourneyVerificationCapability.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  JourneyVerificationCapability(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static JourneyVerificationCapability fromString(String v) {
    return MAP.get(v);
  }

}