// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * How the step list renders.
 */
public enum JourneyStepperLayout {

  VERTICAL("VERTICAL"),

  HORIZONTAL("HORIZONTAL");

  private final static Map<String, JourneyStepperLayout> MAP;

  static {
    Map<String, JourneyStepperLayout> map = new HashMap<String, JourneyStepperLayout>();
    for ( JourneyStepperLayout value : JourneyStepperLayout.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  JourneyStepperLayout(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static JourneyStepperLayout fromString(String v) {
    return MAP.get(v);
  }

}