// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.List;
import java.util.List;
import java.util.List;
import java.util.Objects;


public record JumoKitSpec(String minimumJumoVersion, List<KitBindingDeclaration> bindings, List<String> exports, List<String> assetExports, List<KitProfile> profiles, List<KitModule> modules)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String minimumJumoVersion = "";
        private List<KitBindingDeclaration> bindings = List.of();
        private List<String> exports = List.of();
        private List<String> assetExports = List.of();
        private List<KitProfile> profiles = List.of();
        private List<KitModule> modules = List.of();


        public Builder minimumJumoVersion(String minimumJumoVersion) {
            this.minimumJumoVersion = Objects.requireNonNull(minimumJumoVersion);
            return this;
        }

        public Builder bindings(List<KitBindingDeclaration> bindings) {
            this.bindings = Objects.requireNonNull(bindings);
            return this;
        }

        public Builder exports(List<String> exports) {
            this.exports = Objects.requireNonNull(exports);
            return this;
        }

        public Builder assetExports(List<String> assetExports) {
            this.assetExports = Objects.requireNonNull(assetExports);
            return this;
        }

        public Builder profiles(List<KitProfile> profiles) {
            this.profiles = Objects.requireNonNull(profiles);
            return this;
        }

        public Builder modules(List<KitModule> modules) {
            this.modules = Objects.requireNonNull(modules);
            return this;
        }

    public JumoKitSpec build() {
            return new JumoKitSpec(minimumJumoVersion, bindings, exports, assetExports, profiles, modules);
        }
    }
}
