// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Open string-keyed map (string|number|boolean values) in the source schema, modeled as key/value pairs; value kept as string, the widest common representation.
 */
public record KitBindingValue(String key, String value)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String key = "";
        private String value = "";


        public Builder key(String key) {
            this.key = Objects.requireNonNull(key);
            return this;
        }

        public Builder value(String value) {
            this.value = Objects.requireNonNull(value);
            return this;
        }

    public KitBindingValue build() {
            return new KitBindingValue(key, value);
        }
    }
}
