// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record KitBindingDeclaration(String key, KitBindingValueType type)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String key = "";
        private KitBindingValueType type = null;


        public Builder key(String key) {
            this.key = Objects.requireNonNull(key);
            return this;
        }

        public Builder type(KitBindingValueType type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }

    public KitBindingDeclaration build() {
            return new KitBindingDeclaration(key, type);
        }
    }
}
