// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Realm-local, closed binding for one Jumo Kit release. Supplies values but never grants authority.
 */
public record KitBinding(String apiVersion, String kind, Metadata metadata, KitBindingSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private KitBindingSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(KitBindingSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public KitBinding build() {
            return new KitBinding(apiVersion, kind, metadata, spec);
        }
    }
}
