// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum KitBindingValueType {

  STRING("STRING"),

  NUMBER("NUMBER"),

  BOOLEAN("BOOLEAN"),

  REALM_ID("REALM_ID"),

  PROJECT_ID("PROJECT_ID"),

  ENDPOINT_URL("ENDPOINT_URL"),

  CONFIGURATION_REF("CONFIGURATION_REF"),

  SECRET_SLOT("SECRET_SLOT");

  private final static Map<String, KitBindingValueType> MAP;

  static {
    Map<String, KitBindingValueType> map = new HashMap<String, KitBindingValueType>();
    for ( KitBindingValueType value : KitBindingValueType.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  KitBindingValueType(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static KitBindingValueType fromString(String v) {
    return MAP.get(v);
  }

}