// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.Objects;


public record KitProfile(String id, List<String> exports, List<String> includes)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String id = "";
        private List<String> exports = List.of();
        private List<String> includes = List.of();


        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }

        public Builder exports(List<String> exports) {
            this.exports = Objects.requireNonNull(exports);
            return this;
        }

        public Builder includes(List<String> includes) {
            this.includes = Objects.requireNonNull(includes);
            return this;
        }

    public KitProfile build() {
            return new KitProfile(id, exports, includes);
        }
    }
}
