// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Sanitized evidence of one incremental refresh or reconciliation pass over a KnowledgeSource -- counters, status and reason codes, never source text.
 */
public record KnowledgeSyncRun(String corpusId, String sourceId, String trigger, String status, String startedAt, String completedAt, Integer documentsScanned, Integer documentsUpdated, Integer documentsDeleted, Integer documentsExcluded, String reasonCode, String errorSummary)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String corpusId = "";
        private String sourceId = "";
        private String trigger = "";
        private String status = "";
        private String startedAt = "";
        private String completedAt = "";
        private Integer documentsScanned = null;
        private Integer documentsUpdated = null;
        private Integer documentsDeleted = null;
        private Integer documentsExcluded = null;
        private String reasonCode = "";
        private String errorSummary = "";


        public Builder corpusId(String corpusId) {
            this.corpusId = Objects.requireNonNull(corpusId);
            return this;
        }

        public Builder sourceId(String sourceId) {
            this.sourceId = Objects.requireNonNull(sourceId);
            return this;
        }

        public Builder trigger(String trigger) {
            this.trigger = Objects.requireNonNull(trigger);
            return this;
        }

        public Builder status(String status) {
            this.status = Objects.requireNonNull(status);
            return this;
        }

        public Builder startedAt(String startedAt) {
            this.startedAt = Objects.requireNonNull(startedAt);
            return this;
        }

        public Builder completedAt(String completedAt) {
            this.completedAt = Objects.requireNonNull(completedAt);
            return this;
        }

        public Builder documentsScanned(Integer documentsScanned) {
            this.documentsScanned = Objects.requireNonNull(documentsScanned);
            return this;
        }

        public Builder documentsUpdated(Integer documentsUpdated) {
            this.documentsUpdated = Objects.requireNonNull(documentsUpdated);
            return this;
        }

        public Builder documentsDeleted(Integer documentsDeleted) {
            this.documentsDeleted = Objects.requireNonNull(documentsDeleted);
            return this;
        }

        public Builder documentsExcluded(Integer documentsExcluded) {
            this.documentsExcluded = Objects.requireNonNull(documentsExcluded);
            return this;
        }

        public Builder reasonCode(String reasonCode) {
            this.reasonCode = Objects.requireNonNull(reasonCode);
            return this;
        }

        public Builder errorSummary(String errorSummary) {
            this.errorSummary = Objects.requireNonNull(errorSummary);
            return this;
        }

    public KnowledgeSyncRun build() {
            return new KnowledgeSyncRun(corpusId, sourceId, trigger, status, startedAt, completedAt, documentsScanned, documentsUpdated, documentsDeleted, documentsExcluded, reasonCode, errorSummary);
        }
    }
}
