// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;

/**
 * Reconstructible recognized-state projection of one source document admitted into a KnowledgeCorpus (knowledge-retrieval-git-vertical AC1). Content is replaced atomically by the sync run that observes a new sourceRevision; a purge clears content and chunks in the same transaction and leaves this row as a content-free tombstone.
 */
public record KnowledgeDocument(String realmId, String projectId, String corpusId, String sourceId, KnowledgeSourceKind sourceKind, String sourceDocumentId, String locator, String title, String mimeType, String language, List<String> sourceOwners, String sourceRevision, String contentHash, String sourceUpdatedAt, String observedAt, String indexedAt, DataScope audience, InformationClassification classification, boolean normative, String lifecycle, String exclusionReason, String content, String lastSyncRunId)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String realmId = "";
        private String projectId = "";
        private String corpusId = "";
        private String sourceId = "";
        private KnowledgeSourceKind sourceKind = null;
        private String sourceDocumentId = "";
        private String locator = "";
        private String title = "";
        private String mimeType = "";
        private String language = "";
        private List<String> sourceOwners = List.of();
        private String sourceRevision = "";
        private String contentHash = "";
        private String sourceUpdatedAt = "";
        private String observedAt = "";
        private String indexedAt = "";
        private DataScope audience = null;
        private InformationClassification classification = null;
        private boolean normative = false;
        private String lifecycle = "";
        private String exclusionReason = "";
        private String content = "";
        private String lastSyncRunId = "";


        public Builder realmId(String realmId) {
            this.realmId = Objects.requireNonNull(realmId);
            return this;
        }

        public Builder projectId(String projectId) {
            this.projectId = Objects.requireNonNull(projectId);
            return this;
        }

        public Builder corpusId(String corpusId) {
            this.corpusId = Objects.requireNonNull(corpusId);
            return this;
        }

        public Builder sourceId(String sourceId) {
            this.sourceId = Objects.requireNonNull(sourceId);
            return this;
        }

        public Builder sourceKind(KnowledgeSourceKind sourceKind) {
            this.sourceKind = Objects.requireNonNull(sourceKind);
            return this;
        }

        public Builder sourceDocumentId(String sourceDocumentId) {
            this.sourceDocumentId = Objects.requireNonNull(sourceDocumentId);
            return this;
        }

        public Builder locator(String locator) {
            this.locator = Objects.requireNonNull(locator);
            return this;
        }

        public Builder title(String title) {
            this.title = Objects.requireNonNull(title);
            return this;
        }

        public Builder mimeType(String mimeType) {
            this.mimeType = Objects.requireNonNull(mimeType);
            return this;
        }

        public Builder language(String language) {
            this.language = Objects.requireNonNull(language);
            return this;
        }

        public Builder sourceOwners(List<String> sourceOwners) {
            this.sourceOwners = Objects.requireNonNull(sourceOwners);
            return this;
        }

        public Builder sourceRevision(String sourceRevision) {
            this.sourceRevision = Objects.requireNonNull(sourceRevision);
            return this;
        }

        public Builder contentHash(String contentHash) {
            this.contentHash = Objects.requireNonNull(contentHash);
            return this;
        }

        public Builder sourceUpdatedAt(String sourceUpdatedAt) {
            this.sourceUpdatedAt = Objects.requireNonNull(sourceUpdatedAt);
            return this;
        }

        public Builder observedAt(String observedAt) {
            this.observedAt = Objects.requireNonNull(observedAt);
            return this;
        }

        public Builder indexedAt(String indexedAt) {
            this.indexedAt = Objects.requireNonNull(indexedAt);
            return this;
        }

        public Builder audience(DataScope audience) {
            this.audience = Objects.requireNonNull(audience);
            return this;
        }

        public Builder classification(InformationClassification classification) {
            this.classification = Objects.requireNonNull(classification);
            return this;
        }

        public Builder normative(boolean normative) {
            this.normative = Objects.requireNonNull(normative);
            return this;
        }

        public Builder lifecycle(String lifecycle) {
            this.lifecycle = Objects.requireNonNull(lifecycle);
            return this;
        }

        public Builder exclusionReason(String exclusionReason) {
            this.exclusionReason = Objects.requireNonNull(exclusionReason);
            return this;
        }

        public Builder content(String content) {
            this.content = Objects.requireNonNull(content);
            return this;
        }

        public Builder lastSyncRunId(String lastSyncRunId) {
            this.lastSyncRunId = Objects.requireNonNull(lastSyncRunId);
            return this;
        }

    public KnowledgeDocument build() {
            return new KnowledgeDocument(realmId, projectId, corpusId, sourceId, sourceKind, sourceDocumentId, locator, title, mimeType, language, sourceOwners, sourceRevision, contentHash, sourceUpdatedAt, observedAt, indexedAt, audience, classification, normative, lifecycle, exclusionReason, content, lastSyncRunId);
        }
    }
}
