// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum KnowledgeSourceKind {

  COMPOSED_REALM("COMPOSED_REALM"),

  PROJECT_GIT("PROJECT_GIT"),

  CONNECTOR_SNAPSHOT("CONNECTOR_SNAPSHOT");

  private final static Map<String, KnowledgeSourceKind> MAP;

  static {
    Map<String, KnowledgeSourceKind> map = new HashMap<String, KnowledgeSourceKind>();
    for ( KnowledgeSourceKind value : KnowledgeSourceKind.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  KnowledgeSourceKind(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static KnowledgeSourceKind fromString(String v) {
    return MAP.get(v);
  }

}