// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Realm-owned, grant-governed set of retrievable sources. Its index is derived recognized state and grants no authority.
 */
public record KnowledgeCorpus(String apiVersion, String kind, Metadata metadata, KnowledgeCorpusSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private KnowledgeCorpusSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(KnowledgeCorpusSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public KnowledgeCorpus build() {
            return new KnowledgeCorpus(apiVersion, kind, metadata, spec);
        }
    }
}
