// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Restart-safe watermark for one KnowledgeSource's incremental refresh -- the last Git revision or connector change token observed, without any credential.
 */
public record KnowledgeSyncCursor(String corpusId, String sourceId, String cursorKind, String cursorValue, String updatedAt)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String corpusId = "";
        private String sourceId = "";
        private String cursorKind = "";
        private String cursorValue = "";
        private String updatedAt = "";


        public Builder corpusId(String corpusId) {
            this.corpusId = Objects.requireNonNull(corpusId);
            return this;
        }

        public Builder sourceId(String sourceId) {
            this.sourceId = Objects.requireNonNull(sourceId);
            return this;
        }

        public Builder cursorKind(String cursorKind) {
            this.cursorKind = Objects.requireNonNull(cursorKind);
            return this;
        }

        public Builder cursorValue(String cursorValue) {
            this.cursorValue = Objects.requireNonNull(cursorValue);
            return this;
        }

        public Builder updatedAt(String updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt);
            return this;
        }

    public KnowledgeSyncCursor build() {
            return new KnowledgeSyncCursor(corpusId, sourceId, cursorKind, cursorValue, updatedAt);
        }
    }
}
