// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Explicit declaration of an overridden document from a lower layer or imported kit.
 */
public record LayerOverride(String layer, String id)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String layer = "";
        private String id = "";


        public Builder layer(String layer) {
            this.layer = Objects.requireNonNull(layer);
            return this;
        }

        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }

    public LayerOverride build() {
            return new LayerOverride(layer, id);
        }
    }
}
