// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Observed real-time health and load status of an execution machine.
 */
public record MachineHealthObservation(String machineId, String status, String lastHeartbeatAt, Integer activeLeasesCount, Float systemLoad, Float memoryUsagePercent, Float diskUsagePercent)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String machineId = "";
        private String status = "";
        private String lastHeartbeatAt = "";
        private Integer activeLeasesCount = null;
        private Float systemLoad = null;
        private Float memoryUsagePercent = null;
        private Float diskUsagePercent = null;


        public Builder machineId(String machineId) {
            this.machineId = Objects.requireNonNull(machineId);
            return this;
        }

        public Builder status(String status) {
            this.status = Objects.requireNonNull(status);
            return this;
        }

        public Builder lastHeartbeatAt(String lastHeartbeatAt) {
            this.lastHeartbeatAt = Objects.requireNonNull(lastHeartbeatAt);
            return this;
        }

        public Builder activeLeasesCount(Integer activeLeasesCount) {
            this.activeLeasesCount = Objects.requireNonNull(activeLeasesCount);
            return this;
        }

        public Builder systemLoad(Float systemLoad) {
            this.systemLoad = Objects.requireNonNull(systemLoad);
            return this;
        }

        public Builder memoryUsagePercent(Float memoryUsagePercent) {
            this.memoryUsagePercent = Objects.requireNonNull(memoryUsagePercent);
            return this;
        }

        public Builder diskUsagePercent(Float diskUsagePercent) {
            this.diskUsagePercent = Objects.requireNonNull(diskUsagePercent);
            return this;
        }

    public MachineHealthObservation build() {
            return new MachineHealthObservation(machineId, status, lastHeartbeatAt, activeLeasesCount, systemLoad, memoryUsagePercent, diskUsagePercent);
        }
    }
}
