// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Observed runtime installation (CLI or connector) on a target machine.
 */
public record MachineRuntimeInstallation(String installationId, String machineId, String kind, ContractReference runtimeRef, String releaseDigest, String status, String installedAt)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String installationId = "";
        private String machineId = "";
        private String kind = "";
        private ContractReference runtimeRef = null;
        private String releaseDigest = "";
        private String status = "";
        private String installedAt = "";


        public Builder installationId(String installationId) {
            this.installationId = Objects.requireNonNull(installationId);
            return this;
        }

        public Builder machineId(String machineId) {
            this.machineId = Objects.requireNonNull(machineId);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder runtimeRef(ContractReference runtimeRef) {
            this.runtimeRef = Objects.requireNonNull(runtimeRef);
            return this;
        }

        public Builder releaseDigest(String releaseDigest) {
            this.releaseDigest = Objects.requireNonNull(releaseDigest);
            return this;
        }

        public Builder status(String status) {
            this.status = Objects.requireNonNull(status);
            return this;
        }

        public Builder installedAt(String installedAt) {
            this.installedAt = Objects.requireNonNull(installedAt);
            return this;
        }

    public MachineRuntimeInstallation build() {
            return new MachineRuntimeInstallation(installationId, machineId, kind, runtimeRef, releaseDigest, status, installedAt);
        }
    }
}
