// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;

/**
 * Specification of an allowlisted machine admin playbook.
 */
public record MachineAdminPlaybookSpec(String playbookPath, String playbookDigest, String signature, String variablesSchemaId, List<String> allowedRealms, String description, String appliesToCapability)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String playbookPath = "";
        private String playbookDigest = "";
        private String signature = "";
        private String variablesSchemaId = "";
        private List<String> allowedRealms = List.of();
        private String description = "";
        private String appliesToCapability = "";


        public Builder playbookPath(String playbookPath) {
            this.playbookPath = Objects.requireNonNull(playbookPath);
            return this;
        }

        public Builder playbookDigest(String playbookDigest) {
            this.playbookDigest = Objects.requireNonNull(playbookDigest);
            return this;
        }

        public Builder signature(String signature) {
            this.signature = Objects.requireNonNull(signature);
            return this;
        }

        public Builder variablesSchemaId(String variablesSchemaId) {
            this.variablesSchemaId = Objects.requireNonNull(variablesSchemaId);
            return this;
        }

        public Builder allowedRealms(List<String> allowedRealms) {
            this.allowedRealms = Objects.requireNonNull(allowedRealms);
            return this;
        }

        public Builder description(String description) {
            this.description = Objects.requireNonNull(description);
            return this;
        }

        public Builder appliesToCapability(String appliesToCapability) {
            this.appliesToCapability = Objects.requireNonNull(appliesToCapability);
            return this;
        }

    public MachineAdminPlaybookSpec build() {
            return new MachineAdminPlaybookSpec(playbookPath, playbookDigest, signature, variablesSchemaId, allowedRealms, description, appliesToCapability);
        }
    }
}
