// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Specification for a MachineHostDefinition contract.
 */
public record MachineHostDefinitionSpec(String ownerRealm, String driver, String domainPrefix, String storagePool, String bridgeNetwork, Integer memoryBytes, Integer vcpuCount)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ownerRealm = "";
        private String driver = "";
        private String domainPrefix = "";
        private String storagePool = "";
        private String bridgeNetwork = "";
        private Integer memoryBytes = null;
        private Integer vcpuCount = null;


        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder driver(String driver) {
            this.driver = Objects.requireNonNull(driver);
            return this;
        }

        public Builder domainPrefix(String domainPrefix) {
            this.domainPrefix = Objects.requireNonNull(domainPrefix);
            return this;
        }

        public Builder storagePool(String storagePool) {
            this.storagePool = Objects.requireNonNull(storagePool);
            return this;
        }

        public Builder bridgeNetwork(String bridgeNetwork) {
            this.bridgeNetwork = Objects.requireNonNull(bridgeNetwork);
            return this;
        }

        public Builder memoryBytes(Integer memoryBytes) {
            this.memoryBytes = Objects.requireNonNull(memoryBytes);
            return this;
        }

        public Builder vcpuCount(Integer vcpuCount) {
            this.vcpuCount = Objects.requireNonNull(vcpuCount);
            return this;
        }

    public MachineHostDefinitionSpec build() {
            return new MachineHostDefinitionSpec(ownerRealm, driver, domainPrefix, storagePool, bridgeNetwork, memoryBytes, vcpuCount);
        }
    }
}
