// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Observed hardware and OS characteristics of an enrolled machine.
 */
public record MachineInventoryObservation(String osName, String osVersion, String arch, String kernelVersion, Integer cpuCount, Integer memoryBytes, Integer diskBytes, String agentVersion, String observedAt)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String osName = "";
        private String osVersion = "";
        private String arch = "";
        private String kernelVersion = "";
        private Integer cpuCount = null;
        private Integer memoryBytes = null;
        private Integer diskBytes = null;
        private String agentVersion = "";
        private String observedAt = "";


        public Builder osName(String osName) {
            this.osName = Objects.requireNonNull(osName);
            return this;
        }

        public Builder osVersion(String osVersion) {
            this.osVersion = Objects.requireNonNull(osVersion);
            return this;
        }

        public Builder arch(String arch) {
            this.arch = Objects.requireNonNull(arch);
            return this;
        }

        public Builder kernelVersion(String kernelVersion) {
            this.kernelVersion = Objects.requireNonNull(kernelVersion);
            return this;
        }

        public Builder cpuCount(Integer cpuCount) {
            this.cpuCount = Objects.requireNonNull(cpuCount);
            return this;
        }

        public Builder memoryBytes(Integer memoryBytes) {
            this.memoryBytes = Objects.requireNonNull(memoryBytes);
            return this;
        }

        public Builder diskBytes(Integer diskBytes) {
            this.diskBytes = Objects.requireNonNull(diskBytes);
            return this;
        }

        public Builder agentVersion(String agentVersion) {
            this.agentVersion = Objects.requireNonNull(agentVersion);
            return this;
        }

        public Builder observedAt(String observedAt) {
            this.observedAt = Objects.requireNonNull(observedAt);
            return this;
        }

    public MachineInventoryObservation build() {
            return new MachineInventoryObservation(osName, osVersion, arch, kernelVersion, cpuCount, memoryBytes, diskBytes, agentVersion, observedAt);
        }
    }
}
