// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Short-lived enrollment challenge issued by the control plane.
 */
public record MachineEnrollmentChallenge(String token, String realmId, String machineId, String bootstrapDigest, String expiresAt)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String token = "";
        private String realmId = "";
        private String machineId = "";
        private String bootstrapDigest = "";
        private String expiresAt = "";


        public Builder token(String token) {
            this.token = Objects.requireNonNull(token);
            return this;
        }

        public Builder realmId(String realmId) {
            this.realmId = Objects.requireNonNull(realmId);
            return this;
        }

        public Builder machineId(String machineId) {
            this.machineId = Objects.requireNonNull(machineId);
            return this;
        }

        public Builder bootstrapDigest(String bootstrapDigest) {
            this.bootstrapDigest = Objects.requireNonNull(bootstrapDigest);
            return this;
        }

        public Builder expiresAt(String expiresAt) {
            this.expiresAt = Objects.requireNonNull(expiresAt);
            return this;
        }

    public MachineEnrollmentChallenge build() {
            return new MachineEnrollmentChallenge(token, realmId, machineId, bootstrapDigest, expiresAt);
        }
    }
}
