// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum McpArgumentValueKind {

  LITERAL("LITERAL"),

  PARAMETER("PARAMETER"),

  CREDENTIAL("CREDENTIAL");

  private final static Map<String, McpArgumentValueKind> MAP;

  static {
    Map<String, McpArgumentValueKind> map = new HashMap<String, McpArgumentValueKind>();
    for ( McpArgumentValueKind value : McpArgumentValueKind.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  McpArgumentValueKind(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static McpArgumentValueKind fromString(String v) {
    return MAP.get(v);
  }

}