// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record McpArgumentValue(McpArgumentValueKind valueKind, String literal, String parameterRef, String credentialSlotRef)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private McpArgumentValueKind valueKind = null;
        private String literal = "";
        private String parameterRef = "";
        private String credentialSlotRef = "";


        public Builder valueKind(McpArgumentValueKind valueKind) {
            this.valueKind = Objects.requireNonNull(valueKind);
            return this;
        }

        public Builder literal(String literal) {
            this.literal = Objects.requireNonNull(literal);
            return this;
        }

        public Builder parameterRef(String parameterRef) {
            this.parameterRef = Objects.requireNonNull(parameterRef);
            return this;
        }

        public Builder credentialSlotRef(String credentialSlotRef) {
            this.credentialSlotRef = Objects.requireNonNull(credentialSlotRef);
            return this;
        }

    public McpArgumentValue build() {
            return new McpArgumentValue(valueKind, literal, parameterRef, credentialSlotRef);
        }
    }
}
