// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record McpBindingParameter(String parameterRef, String value)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String parameterRef = "";
        private String value = "";


        public Builder parameterRef(String parameterRef) {
            this.parameterRef = Objects.requireNonNull(parameterRef);
            return this;
        }

        public Builder value(String value) {
            this.value = Objects.requireNonNull(value);
            return this;
        }

    public McpBindingParameter build() {
            return new McpBindingParameter(parameterRef, value);
        }
    }
}
