// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record McpBundleArtifact(String format, String reference, String digest, String publisher, String signatureRef, String sbomRef, String license)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String format = "";
        private String reference = "";
        private String digest = "";
        private String publisher = "";
        private String signatureRef = "";
        private String sbomRef = "";
        private String license = "";


        public Builder format(String format) {
            this.format = Objects.requireNonNull(format);
            return this;
        }

        public Builder reference(String reference) {
            this.reference = Objects.requireNonNull(reference);
            return this;
        }

        public Builder digest(String digest) {
            this.digest = Objects.requireNonNull(digest);
            return this;
        }

        public Builder publisher(String publisher) {
            this.publisher = Objects.requireNonNull(publisher);
            return this;
        }

        public Builder signatureRef(String signatureRef) {
            this.signatureRef = Objects.requireNonNull(signatureRef);
            return this;
        }

        public Builder sbomRef(String sbomRef) {
            this.sbomRef = Objects.requireNonNull(sbomRef);
            return this;
        }

        public Builder license(String license) {
            this.license = Objects.requireNonNull(license);
            return this;
        }

    public McpBundleArtifact build() {
            return new McpBundleArtifact(format, reference, digest, publisher, signatureRef, sbomRef, license);
        }
    }
}
