// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;


public record McpBundleOperation(String id, String exposedName, String upstreamToolName, boolean untrustedOutput, String agentGuidance, String capabilityRef, String description, OperationEffect effect, OperationIdempotency idempotency, OperationReconciliation reconciliation, String monetaryAmountInput, String monetaryCurrency, String inputSchemaRef, String outputSchemaRef, List<ContractReference> secretBindingRefs, String recoveryPlanDigest, String killSwitchRef)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String id = "";
        private String exposedName = "";
        private String upstreamToolName = "";
        private boolean untrustedOutput = false;
        private String agentGuidance = "";
        private String capabilityRef = "";
        private String description = "";
        private OperationEffect effect = null;
        private OperationIdempotency idempotency = null;
        private OperationReconciliation reconciliation = null;
        private String monetaryAmountInput = "";
        private String monetaryCurrency = "";
        private String inputSchemaRef = "";
        private String outputSchemaRef = "";
        private List<ContractReference> secretBindingRefs = List.of();
        private String recoveryPlanDigest = "";
        private String killSwitchRef = "";


        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }

        public Builder exposedName(String exposedName) {
            this.exposedName = Objects.requireNonNull(exposedName);
            return this;
        }

        public Builder upstreamToolName(String upstreamToolName) {
            this.upstreamToolName = Objects.requireNonNull(upstreamToolName);
            return this;
        }

        public Builder untrustedOutput(boolean untrustedOutput) {
            this.untrustedOutput = Objects.requireNonNull(untrustedOutput);
            return this;
        }

        public Builder agentGuidance(String agentGuidance) {
            this.agentGuidance = Objects.requireNonNull(agentGuidance);
            return this;
        }

        public Builder capabilityRef(String capabilityRef) {
            this.capabilityRef = Objects.requireNonNull(capabilityRef);
            return this;
        }

        public Builder description(String description) {
            this.description = Objects.requireNonNull(description);
            return this;
        }

        public Builder effect(OperationEffect effect) {
            this.effect = Objects.requireNonNull(effect);
            return this;
        }

        public Builder idempotency(OperationIdempotency idempotency) {
            this.idempotency = Objects.requireNonNull(idempotency);
            return this;
        }

        public Builder reconciliation(OperationReconciliation reconciliation) {
            this.reconciliation = Objects.requireNonNull(reconciliation);
            return this;
        }

        public Builder monetaryAmountInput(String monetaryAmountInput) {
            this.monetaryAmountInput = Objects.requireNonNull(monetaryAmountInput);
            return this;
        }

        public Builder monetaryCurrency(String monetaryCurrency) {
            this.monetaryCurrency = Objects.requireNonNull(monetaryCurrency);
            return this;
        }

        public Builder inputSchemaRef(String inputSchemaRef) {
            this.inputSchemaRef = Objects.requireNonNull(inputSchemaRef);
            return this;
        }

        public Builder outputSchemaRef(String outputSchemaRef) {
            this.outputSchemaRef = Objects.requireNonNull(outputSchemaRef);
            return this;
        }

        public Builder secretBindingRefs(List<ContractReference> secretBindingRefs) {
            this.secretBindingRefs = Objects.requireNonNull(secretBindingRefs);
            return this;
        }

        public Builder recoveryPlanDigest(String recoveryPlanDigest) {
            this.recoveryPlanDigest = Objects.requireNonNull(recoveryPlanDigest);
            return this;
        }

        public Builder killSwitchRef(String killSwitchRef) {
            this.killSwitchRef = Objects.requireNonNull(killSwitchRef);
            return this;
        }

    public McpBundleOperation build() {
            return new McpBundleOperation(id, exposedName, upstreamToolName, untrustedOutput, agentGuidance, capabilityRef, description, effect, idempotency, reconciliation, monetaryAmountInput, monetaryCurrency, inputSchemaRef, outputSchemaRef, secretBindingRefs, recoveryPlanDigest, killSwitchRef);
        }
    }
}
