// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.time.ZonedDateTime;
import java.util.Objects;


public record McpCatalogAssessment(String catalogId, String dimension, McpCatalogAssessmentOutcome outcome, String evidenceDigest, ZonedDateTime assessedAt)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String catalogId = "";
        private String dimension = "";
        private McpCatalogAssessmentOutcome outcome = null;
        private String evidenceDigest = "";
        private ZonedDateTime assessedAt = null;


        public Builder catalogId(String catalogId) {
            this.catalogId = Objects.requireNonNull(catalogId);
            return this;
        }

        public Builder dimension(String dimension) {
            this.dimension = Objects.requireNonNull(dimension);
            return this;
        }

        public Builder outcome(McpCatalogAssessmentOutcome outcome) {
            this.outcome = Objects.requireNonNull(outcome);
            return this;
        }

        public Builder evidenceDigest(String evidenceDigest) {
            this.evidenceDigest = Objects.requireNonNull(evidenceDigest);
            return this;
        }

        public Builder assessedAt(ZonedDateTime assessedAt) {
            this.assessedAt = Objects.requireNonNull(assessedAt);
            return this;
        }

    public McpCatalogAssessment build() {
            return new McpCatalogAssessment(catalogId, dimension, outcome, evidenceDigest, assessedAt);
        }
    }
}
