// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * One mcp_catalog_listing row's (source_id, external_id) pair, carried verbatim as two strings and never composed into one, because the same server listed by two sources is legitimately two catalogue entries. It replaces the retired importedSourceDigest, whose page-level checksum named up to a hundred servers rather than one.
 */
public record McpCatalogListingKey(String sourceId, String externalId)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String sourceId = "";
        private String externalId = "";


        public Builder sourceId(String sourceId) {
            this.sourceId = Objects.requireNonNull(sourceId);
            return this;
        }

        public Builder externalId(String externalId) {
            this.externalId = Objects.requireNonNull(externalId);
            return this;
        }

    public McpCatalogListingKey build() {
            return new McpCatalogListingKey(sourceId, externalId);
        }
    }
}
