// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum McpCatalogInstallability {

  REMOTE_READY("REMOTE_READY"),

  OCI_READY("OCI_READY"),

  FACTORY_REQUIRED("FACTORY_REQUIRED"),

  UNSUPPORTED("UNSUPPORTED"),

  BLOCKED("BLOCKED"),

  WITHDRAWN("WITHDRAWN");

  private final static Map<String, McpCatalogInstallability> MAP;

  static {
    Map<String, McpCatalogInstallability> map = new HashMap<String, McpCatalogInstallability>();
    for ( McpCatalogInstallability value : McpCatalogInstallability.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  McpCatalogInstallability(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static McpCatalogInstallability fromString(String v) {
    return MAP.get(v);
  }

}