// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record McpCatalogIdentity(String catalogId, String identityType, String identityValue, boolean strong, String sourceId)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String catalogId = "";
        private String identityType = "";
        private String identityValue = "";
        private boolean strong = false;
        private String sourceId = "";


        public Builder catalogId(String catalogId) {
            this.catalogId = Objects.requireNonNull(catalogId);
            return this;
        }

        public Builder identityType(String identityType) {
            this.identityType = Objects.requireNonNull(identityType);
            return this;
        }

        public Builder identityValue(String identityValue) {
            this.identityValue = Objects.requireNonNull(identityValue);
            return this;
        }

        public Builder strong(boolean strong) {
            this.strong = Objects.requireNonNull(strong);
            return this;
        }

        public Builder sourceId(String sourceId) {
            this.sourceId = Objects.requireNonNull(sourceId);
            return this;
        }

    public McpCatalogIdentity build() {
            return new McpCatalogIdentity(catalogId, identityType, identityValue, strong, sourceId);
        }
    }
}
