// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum McpElicitationValueType {

  TEXT("TEXT"),

  BOOLEAN("BOOLEAN"),

  ENUM("ENUM");

  private final static Map<String, McpElicitationValueType> MAP;

  static {
    Map<String, McpElicitationValueType> map = new HashMap<String, McpElicitationValueType>();
    for ( McpElicitationValueType value : McpElicitationValueType.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  McpElicitationValueType(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static McpElicitationValueType fromString(String v) {
    return MAP.get(v);
  }

}