// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * One exact HTTPS origin a binding may resolve for its lease; policy limits origin to a literal or ORIGIN parameter.
 */
public record McpEgressRule(McpArgumentValue origin)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private McpArgumentValue origin = null;


        public Builder origin(McpArgumentValue origin) {
            this.origin = Objects.requireNonNull(origin);
            return this;
        }

    public McpEgressRule build() {
            return new McpEgressRule(origin);
        }
    }
}
