// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;

/**
 * One closed, appraised field a FORM-mode MCP elicitation may request. Values are never contractual state.
 */
public record McpElicitationField(String name, String label, McpElicitationValueType valueType, boolean required, boolean sensitive, Integer maxLength, List<String> allowedValues)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String name = "";
        private String label = "";
        private McpElicitationValueType valueType = null;
        private boolean required = false;
        private boolean sensitive = false;
        private Integer maxLength = null;
        private List<String> allowedValues = List.of();


        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }

        public Builder label(String label) {
            this.label = Objects.requireNonNull(label);
            return this;
        }

        public Builder valueType(McpElicitationValueType valueType) {
            this.valueType = Objects.requireNonNull(valueType);
            return this;
        }

        public Builder required(boolean required) {
            this.required = Objects.requireNonNull(required);
            return this;
        }

        public Builder sensitive(boolean sensitive) {
            this.sensitive = Objects.requireNonNull(sensitive);
            return this;
        }

        public Builder maxLength(Integer maxLength) {
            this.maxLength = Objects.requireNonNull(maxLength);
            return this;
        }

        public Builder allowedValues(List<String> allowedValues) {
            this.allowedValues = Objects.requireNonNull(allowedValues);
            return this;
        }

    public McpElicitationField build() {
            return new McpElicitationField(name, label, valueType, required, sensitive, maxLength, allowedValues);
        }
    }
}
