// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.Objects;

/**
 * PostgreSQL event recording an MCP inventory discovered under an exact Realm lease; it is not a Git contract.
 */
public record McpInventorySnapshot(String serverId, String ownerRealm, ContractReference workOrderRef, String executionCellLeaseRef, ContractReference executionMachineRef, String contractRevision, String artifactOrEndpoint, String serverName, String serverVersion, String protocolVersion, List<String> capabilities, List<McpToolDescriptor> tools, String inventoryDigest, String discoveredAt)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String serverId = "";
        private String ownerRealm = "";
        private ContractReference workOrderRef = null;
        private String executionCellLeaseRef = "";
        private ContractReference executionMachineRef = null;
        private String contractRevision = "";
        private String artifactOrEndpoint = "";
        private String serverName = "";
        private String serverVersion = "";
        private String protocolVersion = "";
        private List<String> capabilities = List.of();
        private List<McpToolDescriptor> tools = List.of();
        private String inventoryDigest = "";
        private String discoveredAt = "";


        public Builder serverId(String serverId) {
            this.serverId = Objects.requireNonNull(serverId);
            return this;
        }

        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder workOrderRef(ContractReference workOrderRef) {
            this.workOrderRef = Objects.requireNonNull(workOrderRef);
            return this;
        }

        public Builder executionCellLeaseRef(String executionCellLeaseRef) {
            this.executionCellLeaseRef = Objects.requireNonNull(executionCellLeaseRef);
            return this;
        }

        public Builder executionMachineRef(ContractReference executionMachineRef) {
            this.executionMachineRef = Objects.requireNonNull(executionMachineRef);
            return this;
        }

        public Builder contractRevision(String contractRevision) {
            this.contractRevision = Objects.requireNonNull(contractRevision);
            return this;
        }

        public Builder artifactOrEndpoint(String artifactOrEndpoint) {
            this.artifactOrEndpoint = Objects.requireNonNull(artifactOrEndpoint);
            return this;
        }

        public Builder serverName(String serverName) {
            this.serverName = Objects.requireNonNull(serverName);
            return this;
        }

        public Builder serverVersion(String serverVersion) {
            this.serverVersion = Objects.requireNonNull(serverVersion);
            return this;
        }

        public Builder protocolVersion(String protocolVersion) {
            this.protocolVersion = Objects.requireNonNull(protocolVersion);
            return this;
        }

        public Builder capabilities(List<String> capabilities) {
            this.capabilities = Objects.requireNonNull(capabilities);
            return this;
        }

        public Builder tools(List<McpToolDescriptor> tools) {
            this.tools = Objects.requireNonNull(tools);
            return this;
        }

        public Builder inventoryDigest(String inventoryDigest) {
            this.inventoryDigest = Objects.requireNonNull(inventoryDigest);
            return this;
        }

        public Builder discoveredAt(String discoveredAt) {
            this.discoveredAt = Objects.requireNonNull(discoveredAt);
            return this;
        }

    public McpInventorySnapshot build() {
            return new McpInventorySnapshot(serverId, ownerRealm, workOrderRef, executionCellLeaseRef, executionMachineRef, contractRevision, artifactOrEndpoint, serverName, serverVersion, protocolVersion, capabilities, tools, inventoryDigest, discoveredAt);
        }
    }
}
