// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Machine acknowledgement that a signed MCP invocation receipt is about to dispatch upstream.
 */
public record McpInvocationDispatchRequest(McpInvocationAuthorizationReceipt receipt)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private McpInvocationAuthorizationReceipt receipt = null;


        public Builder receipt(McpInvocationAuthorizationReceipt receipt) {
            this.receipt = Objects.requireNonNull(receipt);
            return this;
        }

    public McpInvocationDispatchRequest build() {
            return new McpInvocationDispatchRequest(receipt);
        }
    }
}
