// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.time.ZonedDateTime;
import java.util.Objects;


public record McpMaterializationSnapshot(String snapshotId, String realmId, String recipeDigest, String resolvedLockDigest, String sbomDigest, String materializationDigest, String architecture, ZonedDateTime createdAt, String artifactDigest, String requestedOrigin, String finalOrigin, Boolean signatureVerified, String interpreterFacts)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String snapshotId = "";
        private String realmId = "";
        private String recipeDigest = "";
        private String resolvedLockDigest = "";
        private String sbomDigest = "";
        private String materializationDigest = "";
        private String architecture = "";
        private ZonedDateTime createdAt = null;
        private String artifactDigest = "";
        private String requestedOrigin = "";
        private String finalOrigin = "";
        private Boolean signatureVerified = null;
        private String interpreterFacts = "";


        public Builder snapshotId(String snapshotId) {
            this.snapshotId = Objects.requireNonNull(snapshotId);
            return this;
        }

        public Builder realmId(String realmId) {
            this.realmId = Objects.requireNonNull(realmId);
            return this;
        }

        public Builder recipeDigest(String recipeDigest) {
            this.recipeDigest = Objects.requireNonNull(recipeDigest);
            return this;
        }

        public Builder resolvedLockDigest(String resolvedLockDigest) {
            this.resolvedLockDigest = Objects.requireNonNull(resolvedLockDigest);
            return this;
        }

        public Builder sbomDigest(String sbomDigest) {
            this.sbomDigest = Objects.requireNonNull(sbomDigest);
            return this;
        }

        public Builder materializationDigest(String materializationDigest) {
            this.materializationDigest = Objects.requireNonNull(materializationDigest);
            return this;
        }

        public Builder architecture(String architecture) {
            this.architecture = Objects.requireNonNull(architecture);
            return this;
        }

        public Builder createdAt(ZonedDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt);
            return this;
        }

        public Builder artifactDigest(String artifactDigest) {
            this.artifactDigest = Objects.requireNonNull(artifactDigest);
            return this;
        }

        public Builder requestedOrigin(String requestedOrigin) {
            this.requestedOrigin = Objects.requireNonNull(requestedOrigin);
            return this;
        }

        public Builder finalOrigin(String finalOrigin) {
            this.finalOrigin = Objects.requireNonNull(finalOrigin);
            return this;
        }

        public Builder signatureVerified(Boolean signatureVerified) {
            this.signatureVerified = Objects.requireNonNull(signatureVerified);
            return this;
        }

        public Builder interpreterFacts(String interpreterFacts) {
            this.interpreterFacts = Objects.requireNonNull(interpreterFacts);
            return this;
        }

    public McpMaterializationSnapshot build() {
            return new McpMaterializationSnapshot(snapshotId, realmId, recipeDigest, resolvedLockDigest, sbomDigest, materializationDigest, architecture, createdAt, artifactDigest, requestedOrigin, finalOrigin, signatureVerified, interpreterFacts);
        }
    }
}
