// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum McpNetworkIsolationMode {

  NONE("NONE"),

  REMOTE_EXACT_ORIGIN("REMOTE_EXACT_ORIGIN"),

  LEASE_SCOPED_EXACT_ORIGIN("LEASE_SCOPED_EXACT_ORIGIN");

  private final static Map<String, McpNetworkIsolationMode> MAP;

  static {
    Map<String, McpNetworkIsolationMode> map = new HashMap<String, McpNetworkIsolationMode>();
    for ( McpNetworkIsolationMode value : McpNetworkIsolationMode.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  McpNetworkIsolationMode(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static McpNetworkIsolationMode fromString(String v) {
    return MAP.get(v);
  }

}