// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum McpParameterType {

  STRING("STRING"),

  INTEGER("INTEGER"),

  BOOLEAN("BOOLEAN"),

  ENUM("ENUM"),

  ORIGIN("ORIGIN");

  private final static Map<String, McpParameterType> MAP;

  static {
    Map<String, McpParameterType> map = new HashMap<String, McpParameterType>();
    for ( McpParameterType value : McpParameterType.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  McpParameterType(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static McpParameterType fromString(String v) {
    return MAP.get(v);
  }

}