// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record McpReconciliationCandidate(String candidateId, String leftCatalogId, String rightCatalogId, String algorithmVersion, float score, String evidenceDigest)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String candidateId = "";
        private String leftCatalogId = "";
        private String rightCatalogId = "";
        private String algorithmVersion = "";
        private float score = 0f;
        private String evidenceDigest = "";


        public Builder candidateId(String candidateId) {
            this.candidateId = Objects.requireNonNull(candidateId);
            return this;
        }

        public Builder leftCatalogId(String leftCatalogId) {
            this.leftCatalogId = Objects.requireNonNull(leftCatalogId);
            return this;
        }

        public Builder rightCatalogId(String rightCatalogId) {
            this.rightCatalogId = Objects.requireNonNull(rightCatalogId);
            return this;
        }

        public Builder algorithmVersion(String algorithmVersion) {
            this.algorithmVersion = Objects.requireNonNull(algorithmVersion);
            return this;
        }

        public Builder score(float score) {
            this.score = Objects.requireNonNull(score);
            return this;
        }

        public Builder evidenceDigest(String evidenceDigest) {
            this.evidenceDigest = Objects.requireNonNull(evidenceDigest);
            return this;
        }

    public McpReconciliationCandidate build() {
            return new McpReconciliationCandidate(candidateId, leftCatalogId, rightCatalogId, algorithmVersion, score, evidenceDigest);
        }
    }
}
