// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Sanitized audit record for one MCP resource read that reached the upstream fetch attempt. Unlike McpInvocationOutcome, carries no grantId -- a resource read has no InvocationCapabilityGrant to reference (ADR-0063 decision 9's asymmetry -- a resource needs only to be appraised and bounded, not a per-call grant), so there is no receipt to authorize or consume beforehand; this is a single post-attempt record, not a three-step authorize/dispatch/outcome ledger (generic-mcp-full-protocol AC1). A read the plan itself refuses before ever reaching upstream produces no record here, mirroring how a PEP-refused tool call never reaches McpInvocationAuthorizationRequest either.
 */
public record McpResourceReadAudit(String invocationId, String leaseId, String contractSetDigest, String resourceUri, McpInvocationOutcomeType outcome, String contentDigest, Integer contentSize, String reasonCode)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String invocationId = "";
        private String leaseId = "";
        private String contractSetDigest = "";
        private String resourceUri = "";
        private McpInvocationOutcomeType outcome = null;
        private String contentDigest = "";
        private Integer contentSize = null;
        private String reasonCode = "";


        public Builder invocationId(String invocationId) {
            this.invocationId = Objects.requireNonNull(invocationId);
            return this;
        }

        public Builder leaseId(String leaseId) {
            this.leaseId = Objects.requireNonNull(leaseId);
            return this;
        }

        public Builder contractSetDigest(String contractSetDigest) {
            this.contractSetDigest = Objects.requireNonNull(contractSetDigest);
            return this;
        }

        public Builder resourceUri(String resourceUri) {
            this.resourceUri = Objects.requireNonNull(resourceUri);
            return this;
        }

        public Builder outcome(McpInvocationOutcomeType outcome) {
            this.outcome = Objects.requireNonNull(outcome);
            return this;
        }

        public Builder contentDigest(String contentDigest) {
            this.contentDigest = Objects.requireNonNull(contentDigest);
            return this;
        }

        public Builder contentSize(Integer contentSize) {
            this.contentSize = Objects.requireNonNull(contentSize);
            return this;
        }

        public Builder reasonCode(String reasonCode) {
            this.reasonCode = Objects.requireNonNull(reasonCode);
            return this;
        }

    public McpResourceReadAudit build() {
            return new McpResourceReadAudit(invocationId, leaseId, contractSetDigest, resourceUri, outcome, contentDigest, contentSize, reasonCode);
        }
    }
}
