// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.time.ZonedDateTime;
import java.util.Objects;


public record McpReconciliationDecision(String decisionId, String candidateRef, McpReconciliationDecisionType decision, String algorithmVersion, String evidenceDigest, ContractReference authorRef, ContractReference approverRef, String supersedesDecisionRef, ZonedDateTime decidedAt)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String decisionId = "";
        private String candidateRef = "";
        private McpReconciliationDecisionType decision = null;
        private String algorithmVersion = "";
        private String evidenceDigest = "";
        private ContractReference authorRef = null;
        private ContractReference approverRef = null;
        private String supersedesDecisionRef = "";
        private ZonedDateTime decidedAt = null;


        public Builder decisionId(String decisionId) {
            this.decisionId = Objects.requireNonNull(decisionId);
            return this;
        }

        public Builder candidateRef(String candidateRef) {
            this.candidateRef = Objects.requireNonNull(candidateRef);
            return this;
        }

        public Builder decision(McpReconciliationDecisionType decision) {
            this.decision = Objects.requireNonNull(decision);
            return this;
        }

        public Builder algorithmVersion(String algorithmVersion) {
            this.algorithmVersion = Objects.requireNonNull(algorithmVersion);
            return this;
        }

        public Builder evidenceDigest(String evidenceDigest) {
            this.evidenceDigest = Objects.requireNonNull(evidenceDigest);
            return this;
        }

        public Builder authorRef(ContractReference authorRef) {
            this.authorRef = Objects.requireNonNull(authorRef);
            return this;
        }

        public Builder approverRef(ContractReference approverRef) {
            this.approverRef = Objects.requireNonNull(approverRef);
            return this;
        }

        public Builder supersedesDecisionRef(String supersedesDecisionRef) {
            this.supersedesDecisionRef = Objects.requireNonNull(supersedesDecisionRef);
            return this;
        }

        public Builder decidedAt(ZonedDateTime decidedAt) {
            this.decidedAt = Objects.requireNonNull(decidedAt);
            return this;
        }

    public McpReconciliationDecision build() {
            return new McpReconciliationDecision(decisionId, candidateRef, decision, algorithmVersion, evidenceDigest, authorRef, approverRef, supersedesDecisionRef, decidedAt);
        }
    }
}
