// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record McpRuntimeLimits(int maxMemoryBytes, int maxCpuMillis, int maxPayloadBytes, int timeoutMillis, int maxCallsPerMinute)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private int maxMemoryBytes = 0;
        private int maxCpuMillis = 0;
        private int maxPayloadBytes = 0;
        private int timeoutMillis = 0;
        private int maxCallsPerMinute = 0;


        public Builder maxMemoryBytes(int maxMemoryBytes) {
            this.maxMemoryBytes = Objects.requireNonNull(maxMemoryBytes);
            return this;
        }

        public Builder maxCpuMillis(int maxCpuMillis) {
            this.maxCpuMillis = Objects.requireNonNull(maxCpuMillis);
            return this;
        }

        public Builder maxPayloadBytes(int maxPayloadBytes) {
            this.maxPayloadBytes = Objects.requireNonNull(maxPayloadBytes);
            return this;
        }

        public Builder timeoutMillis(int timeoutMillis) {
            this.timeoutMillis = Objects.requireNonNull(timeoutMillis);
            return this;
        }

        public Builder maxCallsPerMinute(int maxCallsPerMinute) {
            this.maxCallsPerMinute = Objects.requireNonNull(maxCallsPerMinute);
            return this;
        }

    public McpRuntimeLimits build() {
            return new McpRuntimeLimits(maxMemoryBytes, maxCpuMillis, maxPayloadBytes, timeoutMillis, maxCallsPerMinute);
        }
    }
}
