// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Platform-scoped configuration for a bounded registry adapter. It authorizes neither installation nor execution.
 */
public record McpRegistrySource(String apiVersion, String kind, Metadata metadata, McpRegistrySourceSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private McpRegistrySourceSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(McpRegistrySourceSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public McpRegistrySource build() {
            return new McpRegistrySource(apiVersion, kind, metadata, spec);
        }
    }
}
