// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;


public record McpServerAppraisalSpec(String ownerRealm, ContractReference recipeRef, ContractReference bindingRef, String recipeDigest, String supplyDigest, String inventoryDigest, String bindingDigest, ContractReference appraisedByRoleDefinitionRef, ContractReference verifiedByRoleDefinitionRef, AppraisalVerdict verdict, List<String> evidenceRefs)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ownerRealm = "";
        private ContractReference recipeRef = null;
        private ContractReference bindingRef = null;
        private String recipeDigest = "";
        private String supplyDigest = "";
        private String inventoryDigest = "";
        private String bindingDigest = "";
        private ContractReference appraisedByRoleDefinitionRef = null;
        private ContractReference verifiedByRoleDefinitionRef = null;
        private AppraisalVerdict verdict = null;
        private List<String> evidenceRefs = List.of();


        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder recipeRef(ContractReference recipeRef) {
            this.recipeRef = Objects.requireNonNull(recipeRef);
            return this;
        }

        public Builder bindingRef(ContractReference bindingRef) {
            this.bindingRef = Objects.requireNonNull(bindingRef);
            return this;
        }

        public Builder recipeDigest(String recipeDigest) {
            this.recipeDigest = Objects.requireNonNull(recipeDigest);
            return this;
        }

        public Builder supplyDigest(String supplyDigest) {
            this.supplyDigest = Objects.requireNonNull(supplyDigest);
            return this;
        }

        public Builder inventoryDigest(String inventoryDigest) {
            this.inventoryDigest = Objects.requireNonNull(inventoryDigest);
            return this;
        }

        public Builder bindingDigest(String bindingDigest) {
            this.bindingDigest = Objects.requireNonNull(bindingDigest);
            return this;
        }

        public Builder appraisedByRoleDefinitionRef(ContractReference appraisedByRoleDefinitionRef) {
            this.appraisedByRoleDefinitionRef = Objects.requireNonNull(appraisedByRoleDefinitionRef);
            return this;
        }

        public Builder verifiedByRoleDefinitionRef(ContractReference verifiedByRoleDefinitionRef) {
            this.verifiedByRoleDefinitionRef = Objects.requireNonNull(verifiedByRoleDefinitionRef);
            return this;
        }

        public Builder verdict(AppraisalVerdict verdict) {
            this.verdict = Objects.requireNonNull(verdict);
            return this;
        }

        public Builder evidenceRefs(List<String> evidenceRefs) {
            this.evidenceRefs = Objects.requireNonNull(evidenceRefs);
            return this;
        }

    public McpServerAppraisalSpec build() {
            return new McpServerAppraisalSpec(ownerRealm, recipeRef, bindingRef, recipeDigest, supplyDigest, inventoryDigest, bindingDigest, appraisedByRoleDefinitionRef, verifiedByRoleDefinitionRef, verdict, evidenceRefs);
        }
    }
}
