// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Descriptor specifying MCP server transport and connection target.
 */
public record McpServerDescriptor(McpTransportType transport, String endpointUrl, String ociImage, String sourceRepository, String sourceCommitSha, Boolean tlsRequired)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private McpTransportType transport = null;
        private String endpointUrl = "";
        private String ociImage = "";
        private String sourceRepository = "";
        private String sourceCommitSha = "";
        private Boolean tlsRequired = null;


        public Builder transport(McpTransportType transport) {
            this.transport = Objects.requireNonNull(transport);
            return this;
        }

        public Builder endpointUrl(String endpointUrl) {
            this.endpointUrl = Objects.requireNonNull(endpointUrl);
            return this;
        }

        public Builder ociImage(String ociImage) {
            this.ociImage = Objects.requireNonNull(ociImage);
            return this;
        }

        public Builder sourceRepository(String sourceRepository) {
            this.sourceRepository = Objects.requireNonNull(sourceRepository);
            return this;
        }

        public Builder sourceCommitSha(String sourceCommitSha) {
            this.sourceCommitSha = Objects.requireNonNull(sourceCommitSha);
            return this;
        }

        public Builder tlsRequired(Boolean tlsRequired) {
            this.tlsRequired = Objects.requireNonNull(tlsRequired);
            return this;
        }

    public McpServerDescriptor build() {
            return new McpServerDescriptor(transport, endpointUrl, ociImage, sourceRepository, sourceCommitSha, tlsRequired);
        }
    }
}
