// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.Objects;


public record McpServerBindingSpec(String ownerRealm, ContractReference recipeRef, ContractReference executionMachineRef, McpBindingLifecycle lifecycle, ContractReference appraisalRef, List<McpBindingParameter> parameterValues, List<McpCredentialBinding> credentialBindings)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ownerRealm = "";
        private ContractReference recipeRef = null;
        private ContractReference executionMachineRef = null;
        private McpBindingLifecycle lifecycle = null;
        private ContractReference appraisalRef = null;
        private List<McpBindingParameter> parameterValues = List.of();
        private List<McpCredentialBinding> credentialBindings = List.of();


        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder recipeRef(ContractReference recipeRef) {
            this.recipeRef = Objects.requireNonNull(recipeRef);
            return this;
        }

        public Builder executionMachineRef(ContractReference executionMachineRef) {
            this.executionMachineRef = Objects.requireNonNull(executionMachineRef);
            return this;
        }

        public Builder lifecycle(McpBindingLifecycle lifecycle) {
            this.lifecycle = Objects.requireNonNull(lifecycle);
            return this;
        }

        public Builder appraisalRef(ContractReference appraisalRef) {
            this.appraisalRef = Objects.requireNonNull(appraisalRef);
            return this;
        }

        public Builder parameterValues(List<McpBindingParameter> parameterValues) {
            this.parameterValues = Objects.requireNonNull(parameterValues);
            return this;
        }

        public Builder credentialBindings(List<McpCredentialBinding> credentialBindings) {
            this.credentialBindings = Objects.requireNonNull(credentialBindings);
            return this;
        }

    public McpServerBindingSpec build() {
            return new McpServerBindingSpec(ownerRealm, recipeRef, executionMachineRef, lifecycle, appraisalRef, parameterValues, credentialBindings);
        }
    }
}
