// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Independent Realm decision bound to exact recipe, supply, inventory and binding digests; it grants no authority.
 */
public record McpServerAppraisal(String apiVersion, String kind, Metadata metadata, McpServerAppraisalSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private McpServerAppraisalSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(McpServerAppraisalSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public McpServerAppraisal build() {
            return new McpServerAppraisal(apiVersion, kind, metadata, spec);
        }
    }
}
