// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.List;
import java.util.List;
import java.util.List;
import java.util.List;
import java.util.List;
import java.util.Objects;


public record McpServerRecipeSpec(String ownerRealm, String importedSourceDigest, McpServerSupply supply, McpRecipeProtocol protocol, List<McpRecipeParameter> parameters, List<McpCredentialSlot> credentialSlots, List<McpArgumentValue> argv, List<McpNamedValue> env, List<McpNamedValue> headers, List<String> egressOrigins, McpRuntimeLimits limits, McpRecipeAuth auth, List<McpPrimitiveExposure> exposures)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ownerRealm = "";
        private String importedSourceDigest = "";
        private McpServerSupply supply = null;
        private McpRecipeProtocol protocol = null;
        private List<McpRecipeParameter> parameters = List.of();
        private List<McpCredentialSlot> credentialSlots = List.of();
        private List<McpArgumentValue> argv = List.of();
        private List<McpNamedValue> env = List.of();
        private List<McpNamedValue> headers = List.of();
        private List<String> egressOrigins = List.of();
        private McpRuntimeLimits limits = null;
        private McpRecipeAuth auth = null;
        private List<McpPrimitiveExposure> exposures = List.of();


        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder importedSourceDigest(String importedSourceDigest) {
            this.importedSourceDigest = Objects.requireNonNull(importedSourceDigest);
            return this;
        }

        public Builder supply(McpServerSupply supply) {
            this.supply = Objects.requireNonNull(supply);
            return this;
        }

        public Builder protocol(McpRecipeProtocol protocol) {
            this.protocol = Objects.requireNonNull(protocol);
            return this;
        }

        public Builder parameters(List<McpRecipeParameter> parameters) {
            this.parameters = Objects.requireNonNull(parameters);
            return this;
        }

        public Builder credentialSlots(List<McpCredentialSlot> credentialSlots) {
            this.credentialSlots = Objects.requireNonNull(credentialSlots);
            return this;
        }

        public Builder argv(List<McpArgumentValue> argv) {
            this.argv = Objects.requireNonNull(argv);
            return this;
        }

        public Builder env(List<McpNamedValue> env) {
            this.env = Objects.requireNonNull(env);
            return this;
        }

        public Builder headers(List<McpNamedValue> headers) {
            this.headers = Objects.requireNonNull(headers);
            return this;
        }

        public Builder egressOrigins(List<String> egressOrigins) {
            this.egressOrigins = Objects.requireNonNull(egressOrigins);
            return this;
        }

        public Builder limits(McpRuntimeLimits limits) {
            this.limits = Objects.requireNonNull(limits);
            return this;
        }

        public Builder auth(McpRecipeAuth auth) {
            this.auth = Objects.requireNonNull(auth);
            return this;
        }

        public Builder exposures(List<McpPrimitiveExposure> exposures) {
            this.exposures = Objects.requireNonNull(exposures);
            return this;
        }

    public McpServerRecipeSpec build() {
            return new McpServerRecipeSpec(ownerRealm, importedSourceDigest, supply, protocol, parameters, credentialSlots, argv, env, headers, egressOrigins, limits, auth, exposures);
        }
    }
}
