// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum McpTransportType {

  STREAMABLE_HTTP("STREAMABLE_HTTP"),

  STDIO_OCI("STDIO_OCI"),

  STDIO_SOURCE("STDIO_SOURCE");

  private final static Map<String, McpTransportType> MAP;

  static {
    Map<String, McpTransportType> map = new HashMap<String, McpTransportType>();
    for ( McpTransportType value : McpTransportType.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  McpTransportType(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static McpTransportType fromString(String v) {
    return MAP.get(v);
  }

}