// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Shared identity block for every contract document.
 */
public record Metadata(String id, String namespace, String name, String defaultDisplayName, LayerOverride overrides)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String id = "";
        private String namespace = "";
        private String name = "";
        private String defaultDisplayName = "";
        private LayerOverride overrides = null;


        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }

        public Builder namespace(String namespace) {
            this.namespace = Objects.requireNonNull(namespace);
            return this;
        }

        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }

        public Builder defaultDisplayName(String defaultDisplayName) {
            this.defaultDisplayName = Objects.requireNonNull(defaultDisplayName);
            return this;
        }

        public Builder overrides(LayerOverride overrides) {
            this.overrides = Objects.requireNonNull(overrides);
            return this;
        }

    public Metadata build() {
            return new Metadata(id, namespace, name, defaultDisplayName, overrides);
        }
    }
}
