// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record Milestone(String id, int order, String exitCondition)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String id = "";
        private int order = 0;
        private String exitCondition = "";


        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }

        public Builder order(int order) {
            this.order = Objects.requireNonNull(order);
            return this;
        }

        public Builder exitCondition(String exitCondition) {
            this.exitCondition = Objects.requireNonNull(exitCondition);
            return this;
        }

    public Milestone build() {
            return new Milestone(id, order, exitCondition);
        }
    }
}
