// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum Modality {

  TEXT("TEXT"),

  AUDIO("AUDIO"),

  IMAGE("IMAGE"),

  VIDEO("VIDEO");

  private final static Map<String, Modality> MAP;

  static {
    Map<String, Modality> map = new HashMap<String, Modality>();
    for ( Modality value : Modality.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  Modality(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static Modality fromString(String v) {
    return MAP.get(v);
  }

}