// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.math.BigDecimal;
import java.math.BigDecimal;
import java.math.BigDecimal;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Objects;

/**
 * The declared price of one model on its ProviderPlatform, denominated per million tokens (quota-usage-ledger-and-pricing AC1). FOUR rates and not two, because both the Anthropic and the OpenAI usage objects report cache-read and cache-creation tokens separately from uncached input, so a two-rate table would misprice every cached call -- which is most of them. USD because every published source reports USD, including the CLIs. A EUR figure is a display-time conversion against a declared dated rate and is never frozen into a ledger row, so that a later rate change cannot rewrite history.
 */
public record ModelPricingSpec(String modelAlias, BigDecimal uncachedInputPerMillion, BigDecimal outputPerMillion, BigDecimal cacheReadPerMillion, BigDecimal cacheWritePerMillion, String currency, LocalDate effectiveFrom)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String modelAlias = "";
        private BigDecimal uncachedInputPerMillion = null;
        private BigDecimal outputPerMillion = null;
        private BigDecimal cacheReadPerMillion = null;
        private BigDecimal cacheWritePerMillion = null;
        private String currency = "";
        private LocalDate effectiveFrom = null;


        public Builder modelAlias(String modelAlias) {
            this.modelAlias = Objects.requireNonNull(modelAlias);
            return this;
        }

        public Builder uncachedInputPerMillion(BigDecimal uncachedInputPerMillion) {
            this.uncachedInputPerMillion = Objects.requireNonNull(uncachedInputPerMillion);
            return this;
        }

        public Builder outputPerMillion(BigDecimal outputPerMillion) {
            this.outputPerMillion = Objects.requireNonNull(outputPerMillion);
            return this;
        }

        public Builder cacheReadPerMillion(BigDecimal cacheReadPerMillion) {
            this.cacheReadPerMillion = Objects.requireNonNull(cacheReadPerMillion);
            return this;
        }

        public Builder cacheWritePerMillion(BigDecimal cacheWritePerMillion) {
            this.cacheWritePerMillion = Objects.requireNonNull(cacheWritePerMillion);
            return this;
        }

        public Builder currency(String currency) {
            this.currency = Objects.requireNonNull(currency);
            return this;
        }

        public Builder effectiveFrom(LocalDate effectiveFrom) {
            this.effectiveFrom = Objects.requireNonNull(effectiveFrom);
            return this;
        }

    public ModelPricingSpec build() {
            return new ModelPricingSpec(modelAlias, uncachedInputPerMillion, outputPerMillion, cacheReadPerMillion, cacheWritePerMillion, currency, effectiveFrom);
        }
    }
}
