// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record ModuleDigestEntry(String moduleId, String digest)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String moduleId = "";
        private String digest = "";


        public Builder moduleId(String moduleId) {
            this.moduleId = Objects.requireNonNull(moduleId);
            return this;
        }

        public Builder digest(String digest) {
            this.digest = Objects.requireNonNull(digest);
            return this;
        }

    public ModuleDigestEntry build() {
            return new ModuleDigestEntry(moduleId, digest);
        }
    }
}
