// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Monetary limits are scoped to their declaring Realm only; no broader scope is available in v1.
 */
public enum MonetaryRiskPolicyScope {

  REALM_ONLY("REALM_ONLY");

  private final static Map<String, MonetaryRiskPolicyScope> MAP;

  static {
    Map<String, MonetaryRiskPolicyScope> map = new HashMap<String, MonetaryRiskPolicyScope>();
    for ( MonetaryRiskPolicyScope value : MonetaryRiskPolicyScope.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  MonetaryRiskPolicyScope(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static MonetaryRiskPolicyScope fromString(String v) {
    return MAP.get(v);
  }

}