// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * RESERVED counts toward its window's cumulative total and blocks dispatch of anything that would exceed it. CONSUMED is terminal and still counts (the money was spent). RELEASED is terminal and no longer counts (the reservation was never spent).
 */
public enum MonetaryReservationStatus {

  RESERVED("RESERVED"),

  CONSUMED("CONSUMED"),

  RELEASED("RELEASED");

  private final static Map<String, MonetaryReservationStatus> MAP;

  static {
    Map<String, MonetaryReservationStatus> map = new HashMap<String, MonetaryReservationStatus>();
    for ( MonetaryReservationStatus value : MonetaryReservationStatus.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  MonetaryReservationStatus(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static MonetaryReservationStatus fromString(String v) {
    return MAP.get(v);
  }

}