// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Realm-scoped monetary limits for declared external operations. The contract declares limits only; recognized reservations and reconciled consumption remain outside Git.
 */
public record MonetaryRiskPolicy(String apiVersion, String kind, Metadata metadata, MonetaryRiskPolicySpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private MonetaryRiskPolicySpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(MonetaryRiskPolicySpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public MonetaryRiskPolicy build() {
            return new MonetaryRiskPolicy(apiVersion, kind, metadata, spec);
        }
    }
}
