// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record MonetaryRiskPolicySpec(String ownerRealm, MonetaryRiskPolicyScope scope, String currency, String window, float perEffectLimit, float cumulativeLimit, MonetaryRiskPolicyLifecycle lifecycle)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ownerRealm = "";
        private MonetaryRiskPolicyScope scope = null;
        private String currency = "";
        private String window = "";
        private float perEffectLimit = 0f;
        private float cumulativeLimit = 0f;
        private MonetaryRiskPolicyLifecycle lifecycle = null;


        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder scope(MonetaryRiskPolicyScope scope) {
            this.scope = Objects.requireNonNull(scope);
            return this;
        }

        public Builder currency(String currency) {
            this.currency = Objects.requireNonNull(currency);
            return this;
        }

        public Builder window(String window) {
            this.window = Objects.requireNonNull(window);
            return this;
        }

        public Builder perEffectLimit(float perEffectLimit) {
            this.perEffectLimit = Objects.requireNonNull(perEffectLimit);
            return this;
        }

        public Builder cumulativeLimit(float cumulativeLimit) {
            this.cumulativeLimit = Objects.requireNonNull(cumulativeLimit);
            return this;
        }

        public Builder lifecycle(MonetaryRiskPolicyLifecycle lifecycle) {
            this.lifecycle = Objects.requireNonNull(lifecycle);
            return this;
        }

    public MonetaryRiskPolicySpec build() {
            return new MonetaryRiskPolicySpec(ownerRealm, scope, currency, window, perEffectLimit, cumulativeLimit, lifecycle);
        }
    }
}
