// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum NotificationChannel {

  MANDALA("MANDALA"),

  WEB_PUSH("WEB_PUSH"),

  EMAIL("EMAIL"),

  WEBCHAT("WEBCHAT"),

  WHATSAPP("WHATSAPP"),

  SMS("SMS"),

  TELEPHONY("TELEPHONY"),

  STENTOR("STENTOR");

  private final static Map<String, NotificationChannel> MAP;

  static {
    Map<String, NotificationChannel> map = new HashMap<String, NotificationChannel>();
    for ( NotificationChannel value : NotificationChannel.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  NotificationChannel(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static NotificationChannel fromString(String v) {
    return MAP.get(v);
  }

}