// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum Obligation {

  STEP_UP_AUTHENTICATION("STEP_UP_AUTHENTICATION"),

  HUMAN_OWNER_APPROVAL("HUMAN_OWNER_APPROVAL"),

  INDEPENDENT_VERIFICATION("INDEPENDENT_VERIFICATION"),

  DISCLOSE_AGENT_IDENTITY("DISCLOSE_AGENT_IDENTITY"),

  RETAIN_PROVENANCE("RETAIN_PROVENANCE"),

  REDACT_SECRETS("REDACT_SECRETS"),

  PREVIEW_BEFORE_SEND("PREVIEW_BEFORE_SEND");

  private final static Map<String, Obligation> MAP;

  static {
    Map<String, Obligation> map = new HashMap<String, Obligation>();
    for ( Obligation value : Obligation.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  Obligation(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static Obligation fromString(String v) {
    return MAP.get(v);
  }

}