// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record OfferingPremiumKitTerms(SourceVisibility sourceVisibility, boolean internalUsePerpetual, RedistributionTerms redistribution, RedistributionTerms resaleSaaS, boolean catalogUpdatesRequireSubscription, boolean supportRequireSubscription)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private SourceVisibility sourceVisibility = null;
        private boolean internalUsePerpetual = false;
        private RedistributionTerms redistribution = null;
        private RedistributionTerms resaleSaaS = null;
        private boolean catalogUpdatesRequireSubscription = false;
        private boolean supportRequireSubscription = false;


        public Builder sourceVisibility(SourceVisibility sourceVisibility) {
            this.sourceVisibility = Objects.requireNonNull(sourceVisibility);
            return this;
        }

        public Builder internalUsePerpetual(boolean internalUsePerpetual) {
            this.internalUsePerpetual = Objects.requireNonNull(internalUsePerpetual);
            return this;
        }

        public Builder redistribution(RedistributionTerms redistribution) {
            this.redistribution = Objects.requireNonNull(redistribution);
            return this;
        }

        public Builder resaleSaaS(RedistributionTerms resaleSaaS) {
            this.resaleSaaS = Objects.requireNonNull(resaleSaaS);
            return this;
        }

        public Builder catalogUpdatesRequireSubscription(boolean catalogUpdatesRequireSubscription) {
            this.catalogUpdatesRequireSubscription = Objects.requireNonNull(catalogUpdatesRequireSubscription);
            return this;
        }

        public Builder supportRequireSubscription(boolean supportRequireSubscription) {
            this.supportRequireSubscription = Objects.requireNonNull(supportRequireSubscription);
            return this;
        }

    public OfferingPremiumKitTerms build() {
            return new OfferingPremiumKitTerms(sourceVisibility, internalUsePerpetual, redistribution, resaleSaaS, catalogUpdatesRequireSubscription, supportRequireSubscription);
        }
    }
}
