// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record OfferingOverage(boolean optInRequired, float providerMarkupPercent, boolean hardCap)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private boolean optInRequired = false;
        private float providerMarkupPercent = 0f;
        private boolean hardCap = false;


        public Builder optInRequired(boolean optInRequired) {
            this.optInRequired = Objects.requireNonNull(optInRequired);
            return this;
        }

        public Builder providerMarkupPercent(float providerMarkupPercent) {
            this.providerMarkupPercent = Objects.requireNonNull(providerMarkupPercent);
            return this;
        }

        public Builder hardCap(boolean hardCap) {
            this.hardCap = Objects.requireNonNull(hardCap);
            return this;
        }

    public OfferingOverage build() {
            return new OfferingOverage(optInRequired, providerMarkupPercent, hardCap);
        }
    }
}
