// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record OfferingExport(boolean free, int exitWindowDays, int backupRetentionDays)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private boolean free = false;
        private int exitWindowDays = 0;
        private int backupRetentionDays = 0;


        public Builder free(boolean free) {
            this.free = Objects.requireNonNull(free);
            return this;
        }

        public Builder exitWindowDays(int exitWindowDays) {
            this.exitWindowDays = Objects.requireNonNull(exitWindowDays);
            return this;
        }

        public Builder backupRetentionDays(int backupRetentionDays) {
            this.backupRetentionDays = Objects.requireNonNull(backupRetentionDays);
            return this;
        }

    public OfferingExport build() {
            return new OfferingExport(free, exitWindowDays, backupRetentionDays);
        }
    }
}
