// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record OfferingOnboarding(int guidedMinutes)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private int guidedMinutes = 0;


        public Builder guidedMinutes(int guidedMinutes) {
            this.guidedMinutes = Objects.requireNonNull(guidedMinutes);
            return this;
        }

    public OfferingOnboarding build() {
            return new OfferingOnboarding(guidedMinutes);
        }
    }
}
