// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Explicit Git binding for Organization owners, administrators, and auditors. MEMBER is intentionally derived by OrganizationEnrollmentPolicy rather than written as an ambient role.
 */
public record OrganizationAccessBinding(String apiVersion, String kind, Metadata metadata, OrganizationAccessBindingSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private OrganizationAccessBindingSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(OrganizationAccessBindingSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public OrganizationAccessBinding build() {
            return new OrganizationAccessBinding(apiVersion, kind, metadata, spec);
        }
    }
}
