// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;


public record OrganizationPublicationPolicySpec(ContractReference organizationRef, List<InteroperabilityAdapter> allowedAdapters, String jwksUri, String publicKey, Integer maxPublishedRealms)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private ContractReference organizationRef = null;
        private List<InteroperabilityAdapter> allowedAdapters = List.of();
        private String jwksUri = "";
        private String publicKey = "";
        private Integer maxPublishedRealms = null;


        public Builder organizationRef(ContractReference organizationRef) {
            this.organizationRef = Objects.requireNonNull(organizationRef);
            return this;
        }

        public Builder allowedAdapters(List<InteroperabilityAdapter> allowedAdapters) {
            this.allowedAdapters = Objects.requireNonNull(allowedAdapters);
            return this;
        }

        public Builder jwksUri(String jwksUri) {
            this.jwksUri = Objects.requireNonNull(jwksUri);
            return this;
        }

        public Builder publicKey(String publicKey) {
            this.publicKey = Objects.requireNonNull(publicKey);
            return this;
        }

        public Builder maxPublishedRealms(Integer maxPublishedRealms) {
            this.maxPublishedRealms = Objects.requireNonNull(maxPublishedRealms);
            return this;
        }

    public OrganizationPublicationPolicySpec build() {
            return new OrganizationPublicationPolicySpec(organizationRef, allowedAdapters, jwksUri, publicKey, maxPublishedRealms);
        }
    }
}
