// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;


public record OrganizationBody(String contractRepository, List<String> memberRealmIds, String ownerPrincipalId, ContractReference realmProvisionerProjectionSpecRef)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String contractRepository = "";
        private List<String> memberRealmIds = List.of();
        private String ownerPrincipalId = "";
        private ContractReference realmProvisionerProjectionSpecRef = null;


        public Builder contractRepository(String contractRepository) {
            this.contractRepository = Objects.requireNonNull(contractRepository);
            return this;
        }

        public Builder memberRealmIds(List<String> memberRealmIds) {
            this.memberRealmIds = Objects.requireNonNull(memberRealmIds);
            return this;
        }

        public Builder ownerPrincipalId(String ownerPrincipalId) {
            this.ownerPrincipalId = Objects.requireNonNull(ownerPrincipalId);
            return this;
        }

        public Builder realmProvisionerProjectionSpecRef(ContractReference realmProvisionerProjectionSpecRef) {
            this.realmProvisionerProjectionSpecRef = Objects.requireNonNull(realmProvisionerProjectionSpecRef);
            return this;
        }

    public OrganizationBody build() {
            return new OrganizationBody(contractRepository, memberRealmIds, ownerPrincipalId, realmProvisionerProjectionSpecRef);
        }
    }
}
