// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.Objects;


public record OrganizationEnrollmentPolicySpec(ContractReference organizationRef, List<String> admittedEmailDomains, List<String> admittedEmails, String oidcRealm, boolean selfEnrollmentEnabled, ContractReference realmProvisionerProjectionSpecRef, String realmRepositoryTemplate)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private ContractReference organizationRef = null;
        private List<String> admittedEmailDomains = List.of();
        private List<String> admittedEmails = List.of();
        private String oidcRealm = "";
        private boolean selfEnrollmentEnabled = false;
        private ContractReference realmProvisionerProjectionSpecRef = null;
        private String realmRepositoryTemplate = "";


        public Builder organizationRef(ContractReference organizationRef) {
            this.organizationRef = Objects.requireNonNull(organizationRef);
            return this;
        }

        public Builder admittedEmailDomains(List<String> admittedEmailDomains) {
            this.admittedEmailDomains = Objects.requireNonNull(admittedEmailDomains);
            return this;
        }

        public Builder admittedEmails(List<String> admittedEmails) {
            this.admittedEmails = Objects.requireNonNull(admittedEmails);
            return this;
        }

        public Builder oidcRealm(String oidcRealm) {
            this.oidcRealm = Objects.requireNonNull(oidcRealm);
            return this;
        }

        public Builder selfEnrollmentEnabled(boolean selfEnrollmentEnabled) {
            this.selfEnrollmentEnabled = Objects.requireNonNull(selfEnrollmentEnabled);
            return this;
        }

        public Builder realmProvisionerProjectionSpecRef(ContractReference realmProvisionerProjectionSpecRef) {
            this.realmProvisionerProjectionSpecRef = Objects.requireNonNull(realmProvisionerProjectionSpecRef);
            return this;
        }

        public Builder realmRepositoryTemplate(String realmRepositoryTemplate) {
            this.realmRepositoryTemplate = Objects.requireNonNull(realmRepositoryTemplate);
            return this;
        }

    public OrganizationEnrollmentPolicySpec build() {
            return new OrganizationEnrollmentPolicySpec(organizationRef, admittedEmailDomains, admittedEmails, oidcRealm, selfEnrollmentEnabled, realmProvisionerProjectionSpecRef, realmRepositoryTemplate);
        }
    }
}
