// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record OrganizationAccessBindingSpec(ContractReference organizationRef, String principalId, OrganizationRole role)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private ContractReference organizationRef = null;
        private String principalId = "";
        private OrganizationRole role = null;


        public Builder organizationRef(ContractReference organizationRef) {
            this.organizationRef = Objects.requireNonNull(organizationRef);
            return this;
        }

        public Builder principalId(String principalId) {
            this.principalId = Objects.requireNonNull(principalId);
            return this;
        }

        public Builder role(OrganizationRole role) {
            this.role = Objects.requireNonNull(role);
            return this;
        }

    public OrganizationAccessBindingSpec build() {
            return new OrganizationAccessBindingSpec(organizationRef, principalId, role);
        }
    }
}
