// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * A tenant boundary with its own Git contract source. Unlike OrganizationSpec, which models an operational composition of roles, this contract names an Organization that composes policy for its member Realms without creating inter-Realm access or effect authority.
 */
public record Organization(String apiVersion, String kind, Metadata metadata, OrganizationBody spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private OrganizationBody spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(OrganizationBody spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public Organization build() {
            return new Organization(apiVersion, kind, metadata, spec);
        }
    }
}
