// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Governance role in an Organization tenant. It is deliberately distinct from a RoleDefinition: organization membership coordinates contracts and audit only and never grants a Realm's data, secret, execution-cell, or effect authority.
 */
public enum OrganizationRole {

  OWNER("OWNER"),

  ADMIN("ADMIN"),

  MEMBER("MEMBER"),

  AUDITOR("AUDITOR");

  private final static Map<String, OrganizationRole> MAP;

  static {
    Map<String, OrganizationRole> map = new HashMap<String, OrganizationRole>();
    for ( OrganizationRole value : OrganizationRole.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  OrganizationRole(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static OrganizationRole fromString(String v) {
    return MAP.get(v);
  }

}