// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * One PLATFORM capability operation exposed by a signed MCP gateway session plan, resolved from a validated KnowledgeCorpusGrant bound to the lease (knowledge-retrieval-access-and-cockpit AC3) -- the cross-cutting counterpart to PlannedOperation, which is always resolved from a connector-bound InvocationCapabilityGrant instead. Carries no upstream MCP server identity, recipe, binding or appraisal digest -- a PLATFORM operation is served by the control plane itself, never proxied to an upstream MCP process, so SessionPlan.platformOperations exists independently of SessionPlan.recipeDigest/bindingDigest/appraisalDigest/supplyDigest/negotiatedVersion/ negotiatedTransport/upstreamToolsDigest -- a lease bound to platform grants only, and no McpServerBinding, leaves all seven of those absent. Mirrors dev.jumo.mcpgateway.plan.PlannedPlatformOperation on the gateway side.
 */
public record PlannedPlatformOperation(String grantId, String exposedName, String inputSchema, boolean producesExternalEffect)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String grantId = "";
        private String exposedName = "";
        private String inputSchema = "";
        private boolean producesExternalEffect = false;


        public Builder grantId(String grantId) {
            this.grantId = Objects.requireNonNull(grantId);
            return this;
        }

        public Builder exposedName(String exposedName) {
            this.exposedName = Objects.requireNonNull(exposedName);
            return this;
        }

        public Builder inputSchema(String inputSchema) {
            this.inputSchema = Objects.requireNonNull(inputSchema);
            return this;
        }

        public Builder producesExternalEffect(boolean producesExternalEffect) {
            this.producesExternalEffect = Objects.requireNonNull(producesExternalEffect);
            return this;
        }

    public PlannedPlatformOperation build() {
            return new PlannedPlatformOperation(grantId, exposedName, inputSchema, producesExternalEffect);
        }
    }
}
