// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * One operation exposed by a signed MCP gateway session plan, resolved from a validated InvocationCapabilityGrant (mcp-gateway-session-plan-signing AC2). Mirrors dev.jumo.mcpgateway.plan.PlannedOperation on the gateway side.
 */
public record PlannedOperation(String grantId, String exposedName, String upstreamToolName, String description, String inputSchema, String outputSchema, boolean producesExternalEffect)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String grantId = "";
        private String exposedName = "";
        private String upstreamToolName = "";
        private String description = "";
        private String inputSchema = "";
        private String outputSchema = "";
        private boolean producesExternalEffect = false;


        public Builder grantId(String grantId) {
            this.grantId = Objects.requireNonNull(grantId);
            return this;
        }

        public Builder exposedName(String exposedName) {
            this.exposedName = Objects.requireNonNull(exposedName);
            return this;
        }

        public Builder upstreamToolName(String upstreamToolName) {
            this.upstreamToolName = Objects.requireNonNull(upstreamToolName);
            return this;
        }

        public Builder description(String description) {
            this.description = Objects.requireNonNull(description);
            return this;
        }

        public Builder inputSchema(String inputSchema) {
            this.inputSchema = Objects.requireNonNull(inputSchema);
            return this;
        }

        public Builder outputSchema(String outputSchema) {
            this.outputSchema = Objects.requireNonNull(outputSchema);
            return this;
        }

        public Builder producesExternalEffect(boolean producesExternalEffect) {
            this.producesExternalEffect = Objects.requireNonNull(producesExternalEffect);
            return this;
        }

    public PlannedOperation build() {
            return new PlannedOperation(grantId, exposedName, upstreamToolName, description, inputSchema, outputSchema, producesExternalEffect);
        }
    }
}
