// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;

/**
 * One ELICITATION exposure's bounds carried in a signed MCP gateway session plan -- opt-in per ADR-0063 decision 9, mirroring PlannedSampling's own asymmetry -- a plan with zero PlannedElicitation entries refuses every elicitation/create request outright, a plan with one bounds every request against it (elicitationSensitiveAllowed, allowedOrigins, both carried verbatim from the declared McpPrimitiveExposure rather than resolved eagerly, since neither names a live reference the way resourceBudgetRef or staticContentDigest do). Mirrors dev.jumo.mcpgateway.plan.PlannedElicitation on the gateway side. Like resources, prompts and sampling, elicitation carries no InvocationCapabilityGrant -- there is no per-call receipt to authorize or consume (generic-mcp-full-protocol AC4).
 */
public record PlannedElicitation(String exposedName, Boolean elicitationSensitiveAllowed, List<String> allowedOrigins)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String exposedName = "";
        private Boolean elicitationSensitiveAllowed = null;
        private List<String> allowedOrigins = List.of();


        public Builder exposedName(String exposedName) {
            this.exposedName = Objects.requireNonNull(exposedName);
            return this;
        }

        public Builder elicitationSensitiveAllowed(Boolean elicitationSensitiveAllowed) {
            this.elicitationSensitiveAllowed = Objects.requireNonNull(elicitationSensitiveAllowed);
            return this;
        }

        public Builder allowedOrigins(List<String> allowedOrigins) {
            this.allowedOrigins = Objects.requireNonNull(allowedOrigins);
            return this;
        }

    public PlannedElicitation build() {
            return new PlannedElicitation(exposedName, elicitationSensitiveAllowed, allowedOrigins);
        }
    }
}
