// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * The catalogue of platform operations an agent may be offered as tools. It declares which operations exist and to which AgentDefinition each is exposed; it grants nothing. Authority still comes from the capability an operation names, resolved at call time, and an operation is offerable to an agent only when that agent already requests that capability -- one authority model, the one Rego already checks. Sealed because widening the set a Realm's agents may be offered is a PLATFORM decision, not a Realm one.
 */
public record PlatformOperationSet(String apiVersion, String kind, Metadata metadata, PlatformOperationSetSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private PlatformOperationSetSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(PlatformOperationSetSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public PlatformOperationSet build() {
            return new PlatformOperationSet(apiVersion, kind, metadata, spec);
        }
    }
}
