// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;

/**
 * One platform operation exposable to an agent as a tool. riskTier, producesExternalEffect, reversible, requiredObligations and ringCeiling are deliberately absent -- every one of them is derived from capabilityRef at resolution time, so a declaration here could only ever contradict the capability it names. requiresGrant is implicit for the same reason it is not a field, since every call consumes a single-use InvocationCapabilityGrant.
 */
public record PlatformOperation(String exposedName, String capabilityRef, String description, String inputSchemaRef, String outputSchemaRef, String handlerId, List<ContractReference> exposedToAgentDefinitionRefs, Long maxResultBytes)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String exposedName = "";
        private String capabilityRef = "";
        private String description = "";
        private String inputSchemaRef = "";
        private String outputSchemaRef = "";
        private String handlerId = "";
        private List<ContractReference> exposedToAgentDefinitionRefs = List.of();
        private Long maxResultBytes = null;


        public Builder exposedName(String exposedName) {
            this.exposedName = Objects.requireNonNull(exposedName);
            return this;
        }

        public Builder capabilityRef(String capabilityRef) {
            this.capabilityRef = Objects.requireNonNull(capabilityRef);
            return this;
        }

        public Builder description(String description) {
            this.description = Objects.requireNonNull(description);
            return this;
        }

        public Builder inputSchemaRef(String inputSchemaRef) {
            this.inputSchemaRef = Objects.requireNonNull(inputSchemaRef);
            return this;
        }

        public Builder outputSchemaRef(String outputSchemaRef) {
            this.outputSchemaRef = Objects.requireNonNull(outputSchemaRef);
            return this;
        }

        public Builder handlerId(String handlerId) {
            this.handlerId = Objects.requireNonNull(handlerId);
            return this;
        }

        public Builder exposedToAgentDefinitionRefs(List<ContractReference> exposedToAgentDefinitionRefs) {
            this.exposedToAgentDefinitionRefs = Objects.requireNonNull(exposedToAgentDefinitionRefs);
            return this;
        }

        public Builder maxResultBytes(Long maxResultBytes) {
            this.maxResultBytes = Objects.requireNonNull(maxResultBytes);
            return this;
        }

    public PlatformOperation build() {
            return new PlatformOperation(exposedName, capabilityRef, description, inputSchemaRef, outputSchemaRef, handlerId, exposedToAgentDefinitionRefs, maxResultBytes);
        }
    }
}
