// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;


public record PolicySetSpec(PolicyScope scope, List<PolicyRule> rules)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private PolicyScope scope = null;
        private List<PolicyRule> rules = List.of();


        public Builder scope(PolicyScope scope) {
            this.scope = Objects.requireNonNull(scope);
            return this;
        }

        public Builder rules(List<PolicyRule> rules) {
            this.rules = Objects.requireNonNull(rules);
            return this;
        }

    public PolicySetSpec build() {
            return new PolicySetSpec(scope, rules);
        }
    }
}
