// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Executable authorization. Only policies allow, deny or impose obligations. Every action named here must resolve against the capability registry.
 */
public record PolicySet(String apiVersion, String kind, Metadata metadata, PolicySetSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private PolicySetSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(PolicySetSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public PolicySet build() {
            return new PolicySet(apiVersion, kind, metadata, spec);
        }
    }
}
