// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * A recurring governed invocation. Rather than owning its own cron/timezone/invokes fields, a Practice references a ProcessSpec (execution.yaml) whose START step is kind: TIMER -- the schedule lives once, on the process, not twice (once here and once conceptually on whatever the source schema's separate WorkflowDeclaration would have needed). This removes the source schema's `schedule` and `invokes` blocks entirely; `delivery`, `autonomy`, `budgetRef`, and `enabled` are unchanged.
 */
public record Practice(String apiVersion, String kind, Metadata metadata, PracticeSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private PracticeSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(PracticeSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public Practice build() {
            return new Practice(apiVersion, kind, metadata, spec);
        }
    }
}
