// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record PracticeSpec(String purpose, ContractReference processSpecRef, DeliveryMode delivery, AutonomyLevel autonomy, ContractReference resourceBudgetRef, Boolean enabled)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String purpose = "";
        private ContractReference processSpecRef = null;
        private DeliveryMode delivery = null;
        private AutonomyLevel autonomy = null;
        private ContractReference resourceBudgetRef = null;
        private Boolean enabled = null;


        public Builder purpose(String purpose) {
            this.purpose = Objects.requireNonNull(purpose);
            return this;
        }

        public Builder processSpecRef(ContractReference processSpecRef) {
            this.processSpecRef = Objects.requireNonNull(processSpecRef);
            return this;
        }

        public Builder delivery(DeliveryMode delivery) {
            this.delivery = Objects.requireNonNull(delivery);
            return this;
        }

        public Builder autonomy(AutonomyLevel autonomy) {
            this.autonomy = Objects.requireNonNull(autonomy);
            return this;
        }

        public Builder resourceBudgetRef(ContractReference resourceBudgetRef) {
            this.resourceBudgetRef = Objects.requireNonNull(resourceBudgetRef);
            return this;
        }

        public Builder enabled(Boolean enabled) {
            this.enabled = Objects.requireNonNull(enabled);
            return this;
        }

    public PracticeSpec build() {
            return new PracticeSpec(purpose, processSpecRef, delivery, autonomy, resourceBudgetRef, enabled);
        }
    }
}
