// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * How much is shown at once. CALM is the default posture -- Jumo is measured on attention it returns.
 */
public enum PresenceDensity {

  CALM("CALM"),

  STANDARD("STANDARD"),

  DENSE("DENSE");

  private final static Map<String, PresenceDensity> MAP;

  static {
    Map<String, PresenceDensity> map = new HashMap<String, PresenceDensity>();
    for ( PresenceDensity value : PresenceDensity.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  PresenceDensity(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static PresenceDensity fromString(String v) {
    return MAP.get(v);
  }

}