// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Explicit Realm-local binding between a member or owner Principal and its OIDC subject. It grants no authority and is never prompt context.
 */
public record PrincipalIdentityBinding(String apiVersion, String kind, Metadata metadata, PrincipalIdentityBindingSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private PrincipalIdentityBindingSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(PrincipalIdentityBindingSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public PrincipalIdentityBinding build() {
            return new PrincipalIdentityBinding(apiVersion, kind, metadata, spec);
        }
    }
}
