// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record PrincipalIdentityBindingSpec(String ownerRealm, ContractReference principalRef, String oidcSubject, String issuer)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ownerRealm = "";
        private ContractReference principalRef = null;
        private String oidcSubject = "";
        private String issuer = "";


        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder principalRef(ContractReference principalRef) {
            this.principalRef = Objects.requireNonNull(principalRef);
            return this;
        }

        public Builder oidcSubject(String oidcSubject) {
            this.oidcSubject = Objects.requireNonNull(oidcSubject);
            return this;
        }

        public Builder issuer(String issuer) {
            this.issuer = Objects.requireNonNull(issuer);
            return this;
        }

    public PrincipalIdentityBindingSpec build() {
            return new PrincipalIdentityBindingSpec(ownerRealm, principalRef, oidcSubject, issuer);
        }
    }
}
