// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record PrincipalSpec(String ownerRealm, PrincipalKind principalKind, String displayName, ContractReference personalSpaceRef, ConsentState consentState)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ownerRealm = "";
        private PrincipalKind principalKind = null;
        private String displayName = "";
        private ContractReference personalSpaceRef = null;
        private ConsentState consentState = null;


        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder principalKind(PrincipalKind principalKind) {
            this.principalKind = Objects.requireNonNull(principalKind);
            return this;
        }

        public Builder displayName(String displayName) {
            this.displayName = Objects.requireNonNull(displayName);
            return this;
        }

        public Builder personalSpaceRef(ContractReference personalSpaceRef) {
            this.personalSpaceRef = Objects.requireNonNull(personalSpaceRef);
            return this;
        }

        public Builder consentState(ConsentState consentState) {
            this.consentState = Objects.requireNonNull(consentState);
            return this;
        }

    public PrincipalSpec build() {
            return new PrincipalSpec(ownerRealm, principalKind, displayName, personalSpaceRef, consentState);
        }
    }
}
