// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record ProcessDurability(String expectedMaximum, ProcessHistoryRetention historyRetention)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String expectedMaximum = "";
        private ProcessHistoryRetention historyRetention = null;


        public Builder expectedMaximum(String expectedMaximum) {
            this.expectedMaximum = Objects.requireNonNull(expectedMaximum);
            return this;
        }

        public Builder historyRetention(ProcessHistoryRetention historyRetention) {
            this.historyRetention = Objects.requireNonNull(historyRetention);
            return this;
        }

    public ProcessDurability build() {
            return new ProcessDurability(expectedMaximum, historyRetention);
        }
    }
}
