// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record ProcessFlow(String id, String from, String to, String branchLabel, String payloadType)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String id = "";
        private String from = "";
        private String to = "";
        private String branchLabel = "";
        private String payloadType = "";


        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }

        public Builder from(String from) {
            this.from = Objects.requireNonNull(from);
            return this;
        }

        public Builder to(String to) {
            this.to = Objects.requireNonNull(to);
            return this;
        }

        public Builder branchLabel(String branchLabel) {
            this.branchLabel = Objects.requireNonNull(branchLabel);
            return this;
        }

        public Builder payloadType(String payloadType) {
            this.payloadType = Objects.requireNonNull(payloadType);
            return this;
        }

    public ProcessFlow build() {
            return new ProcessFlow(id, from, to, branchLabel, payloadType);
        }
    }
}
