// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.List;
import java.util.Objects;


public record ProcessSpecBody(String ownerRealm, ContractReference projectRef, String processId, String processVersion, String inputType, String outputType, ProcessStartTrigger startTrigger, String timerDelay, List<ProcessStep> steps, List<ProcessFlow> flows, ProcessDurability durability, List<ProcessStageWorkerRequirement> stageWorkerRequirementRef, ContractReference resourceBudgetRef)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ownerRealm = "";
        private ContractReference projectRef = null;
        private String processId = "";
        private String processVersion = "";
        private String inputType = "";
        private String outputType = "";
        private ProcessStartTrigger startTrigger = null;
        private String timerDelay = "";
        private List<ProcessStep> steps = List.of();
        private List<ProcessFlow> flows = List.of();
        private ProcessDurability durability = null;
        private List<ProcessStageWorkerRequirement> stageWorkerRequirementRef = List.of();
        private ContractReference resourceBudgetRef = null;


        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder projectRef(ContractReference projectRef) {
            this.projectRef = Objects.requireNonNull(projectRef);
            return this;
        }

        public Builder processId(String processId) {
            this.processId = Objects.requireNonNull(processId);
            return this;
        }

        public Builder processVersion(String processVersion) {
            this.processVersion = Objects.requireNonNull(processVersion);
            return this;
        }

        public Builder inputType(String inputType) {
            this.inputType = Objects.requireNonNull(inputType);
            return this;
        }

        public Builder outputType(String outputType) {
            this.outputType = Objects.requireNonNull(outputType);
            return this;
        }

        public Builder startTrigger(ProcessStartTrigger startTrigger) {
            this.startTrigger = Objects.requireNonNull(startTrigger);
            return this;
        }

        public Builder timerDelay(String timerDelay) {
            this.timerDelay = Objects.requireNonNull(timerDelay);
            return this;
        }

        public Builder steps(List<ProcessStep> steps) {
            this.steps = Objects.requireNonNull(steps);
            return this;
        }

        public Builder flows(List<ProcessFlow> flows) {
            this.flows = Objects.requireNonNull(flows);
            return this;
        }

        public Builder durability(ProcessDurability durability) {
            this.durability = Objects.requireNonNull(durability);
            return this;
        }

        public Builder stageWorkerRequirementRef(List<ProcessStageWorkerRequirement> stageWorkerRequirementRef) {
            this.stageWorkerRequirementRef = Objects.requireNonNull(stageWorkerRequirementRef);
            return this;
        }

        public Builder resourceBudgetRef(ContractReference resourceBudgetRef) {
            this.resourceBudgetRef = Objects.requireNonNull(resourceBudgetRef);
            return this;
        }

    public ProcessSpecBody build() {
            return new ProcessSpecBody(ownerRealm, projectRef, processId, processVersion, inputType, outputType, startTrigger, timerDelay, steps, flows, durability, stageWorkerRequirementRef, resourceBudgetRef);
        }
    }
}
