// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;

/**
 * RGPD art. 30 register entry.
 */
public record ProcessingRegisterEntry(String activity, String purpose, List<String> dataCategories, String retention, ContractReference dpiaEvidenceProfileRef)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String activity = "";
        private String purpose = "";
        private List<String> dataCategories = List.of();
        private String retention = "";
        private ContractReference dpiaEvidenceProfileRef = null;


        public Builder activity(String activity) {
            this.activity = Objects.requireNonNull(activity);
            return this;
        }

        public Builder purpose(String purpose) {
            this.purpose = Objects.requireNonNull(purpose);
            return this;
        }

        public Builder dataCategories(List<String> dataCategories) {
            this.dataCategories = Objects.requireNonNull(dataCategories);
            return this;
        }

        public Builder retention(String retention) {
            this.retention = Objects.requireNonNull(retention);
            return this;
        }

        public Builder dpiaEvidenceProfileRef(ContractReference dpiaEvidenceProfileRef) {
            this.dpiaEvidenceProfileRef = Objects.requireNonNull(dpiaEvidenceProfileRef);
            return this;
        }

    public ProcessingRegisterEntry build() {
            return new ProcessingRegisterEntry(activity, purpose, dataCategories, retention, dpiaEvidenceProfileRef);
        }
    }
}
