// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum ProjectionKind {

  FORM("FORM"),

  DETAIL("DETAIL"),

  COLLECTION("COLLECTION");

  private final static Map<String, ProjectionKind> MAP;

  static {
    Map<String, ProjectionKind> map = new HashMap<String, ProjectionKind>();
    for ( ProjectionKind value : ProjectionKind.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  ProjectionKind(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static ProjectionKind fromString(String v) {
    return MAP.get(v);
  }

}