// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.Objects;


public record ProjectionSpecBody(String ownerRealm, String of, String payloadSchemaRef, ProjectionKind projectionKind, String renderedBy, List<ProjectionSection> sections, List<String> actions)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ownerRealm = "";
        private String of = "";
        private String payloadSchemaRef = "";
        private ProjectionKind projectionKind = null;
        private String renderedBy = "";
        private List<ProjectionSection> sections = List.of();
        private List<String> actions = List.of();


        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder of(String of) {
            this.of = Objects.requireNonNull(of);
            return this;
        }

        public Builder payloadSchemaRef(String payloadSchemaRef) {
            this.payloadSchemaRef = Objects.requireNonNull(payloadSchemaRef);
            return this;
        }

        public Builder projectionKind(ProjectionKind projectionKind) {
            this.projectionKind = Objects.requireNonNull(projectionKind);
            return this;
        }

        public Builder renderedBy(String renderedBy) {
            this.renderedBy = Objects.requireNonNull(renderedBy);
            return this;
        }

        public Builder sections(List<ProjectionSection> sections) {
            this.sections = Objects.requireNonNull(sections);
            return this;
        }

        public Builder actions(List<String> actions) {
            this.actions = Objects.requireNonNull(actions);
            return this;
        }

    public ProjectionSpecBody build() {
            return new ProjectionSpecBody(ownerRealm, of, payloadSchemaRef, projectionKind, renderedBy, sections, actions);
        }
    }
}
