// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * A named view of one generated LinkML class. `of:` follows the same "generated LinkML class name" pattern as ProcessFlow.payloadType and ProcessStep.signalType (execution.yaml) rather than introducing a second typed-payload vocabulary.
 */
public record ProjectionSpec(String apiVersion, String kind, Metadata metadata, ProjectionSpecBody spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private ProjectionSpecBody spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(ProjectionSpecBody spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public ProjectionSpec build() {
            return new ProjectionSpec(apiVersion, kind, metadata, spec);
        }
    }
}
