// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record ProjectCompatibility(String minimumJumoVersion)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String minimumJumoVersion = "";


        public Builder minimumJumoVersion(String minimumJumoVersion) {
            this.minimumJumoVersion = Objects.requireNonNull(minimumJumoVersion);
            return this;
        }

    public ProjectCompatibility build() {
            return new ProjectCompatibility(minimumJumoVersion);
        }
    }
}
