// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * One condition a candidate instance must satisfy to be offered as a field's option.
 */
public record ProjectionOptionCondition(String path, String equalsValue, Boolean present)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String path = "";
        private String equalsValue = "";
        private Boolean present = null;


        public Builder path(String path) {
            this.path = Objects.requireNonNull(path);
            return this;
        }

        public Builder equalsValue(String equalsValue) {
            this.equalsValue = Objects.requireNonNull(equalsValue);
            return this;
        }

        public Builder present(Boolean present) {
            this.present = Objects.requireNonNull(present);
            return this;
        }

    public ProjectionOptionCondition build() {
            return new ProjectionOptionCondition(path, equalsValue, present);
        }
    }
}
