// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * A governed body of work declared in a Realm control repository. Git repositories are optional bound resources, not the identity of a Project.
 */
public record Project(String apiVersion, String kind, Metadata metadata, ProjectSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private ProjectSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(ProjectSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public Project build() {
            return new Project(apiVersion, kind, metadata, spec);
        }
    }
}
