// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum ProjectLifecycle {

  IDEATION("IDEATION"),

  BOOTSTRAP("BOOTSTRAP"),

  ACTIVE("ACTIVE"),

  MAINTENANCE("MAINTENANCE"),

  ARCHIVED("ARCHIVED");

  private final static Map<String, ProjectLifecycle> MAP;

  static {
    Map<String, ProjectLifecycle> map = new HashMap<String, ProjectLifecycle>();
    for ( ProjectLifecycle value : ProjectLifecycle.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  ProjectLifecycle(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static ProjectLifecycle fromString(String v) {
    return MAP.get(v);
  }

}