// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record ProjectRuntime(DurableWorkflowEngine durableWorkflowEngine)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private DurableWorkflowEngine durableWorkflowEngine = null;


        public Builder durableWorkflowEngine(DurableWorkflowEngine durableWorkflowEngine) {
            this.durableWorkflowEngine = Objects.requireNonNull(durableWorkflowEngine);
            return this;
        }

    public ProjectRuntime build() {
            return new ProjectRuntime(durableWorkflowEngine);
        }
    }
}
