// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.List;
import java.util.Objects;


public record ProjectSpec(String contractDirectory, String ownerRealm, ProjectLifecycle lifecycle, ProjectVisibility visibility, List<RepositoryBinding> repositoryBindings, ProjectDocumentation documentation, List<ProjectPersonalSpaceBinding> personalSpaces, ProjectCompatibility compatibility, String purpose, String primaryLanguage, DeploymentTarget deployment, ProjectRuntime runtime, ProjectStateAuthority authority, List<Milestone> milestones)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String contractDirectory = "";
        private String ownerRealm = "";
        private ProjectLifecycle lifecycle = null;
        private ProjectVisibility visibility = null;
        private List<RepositoryBinding> repositoryBindings = List.of();
        private ProjectDocumentation documentation = null;
        private List<ProjectPersonalSpaceBinding> personalSpaces = List.of();
        private ProjectCompatibility compatibility = null;
        private String purpose = "";
        private String primaryLanguage = "";
        private DeploymentTarget deployment = null;
        private ProjectRuntime runtime = null;
        private ProjectStateAuthority authority = null;
        private List<Milestone> milestones = List.of();


        public Builder contractDirectory(String contractDirectory) {
            this.contractDirectory = Objects.requireNonNull(contractDirectory);
            return this;
        }

        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder lifecycle(ProjectLifecycle lifecycle) {
            this.lifecycle = Objects.requireNonNull(lifecycle);
            return this;
        }

        public Builder visibility(ProjectVisibility visibility) {
            this.visibility = Objects.requireNonNull(visibility);
            return this;
        }

        public Builder repositoryBindings(List<RepositoryBinding> repositoryBindings) {
            this.repositoryBindings = Objects.requireNonNull(repositoryBindings);
            return this;
        }

        public Builder documentation(ProjectDocumentation documentation) {
            this.documentation = Objects.requireNonNull(documentation);
            return this;
        }

        public Builder personalSpaces(List<ProjectPersonalSpaceBinding> personalSpaces) {
            this.personalSpaces = Objects.requireNonNull(personalSpaces);
            return this;
        }

        public Builder compatibility(ProjectCompatibility compatibility) {
            this.compatibility = Objects.requireNonNull(compatibility);
            return this;
        }

        public Builder purpose(String purpose) {
            this.purpose = Objects.requireNonNull(purpose);
            return this;
        }

        public Builder primaryLanguage(String primaryLanguage) {
            this.primaryLanguage = Objects.requireNonNull(primaryLanguage);
            return this;
        }

        public Builder deployment(DeploymentTarget deployment) {
            this.deployment = Objects.requireNonNull(deployment);
            return this;
        }

        public Builder runtime(ProjectRuntime runtime) {
            this.runtime = Objects.requireNonNull(runtime);
            return this;
        }

        public Builder authority(ProjectStateAuthority authority) {
            this.authority = Objects.requireNonNull(authority);
            return this;
        }

        public Builder milestones(List<Milestone> milestones) {
            this.milestones = Objects.requireNonNull(milestones);
            return this;
        }

    public ProjectSpec build() {
            return new ProjectSpec(contractDirectory, ownerRealm, lifecycle, visibility, repositoryBindings, documentation, personalSpaces, compatibility, purpose, primaryLanguage, deployment, runtime, authority, milestones);
        }
    }
}
