// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record PromptVariable(String name, String description, VariableTrust trust, Boolean required)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String name = "";
        private String description = "";
        private VariableTrust trust = null;
        private Boolean required = null;


        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }

        public Builder description(String description) {
            this.description = Objects.requireNonNull(description);
            return this;
        }

        public Builder trust(VariableTrust trust) {
            this.trust = Objects.requireNonNull(trust);
            return this;
        }

        public Builder required(Boolean required) {
            this.required = Objects.requireNonNull(required);
            return this;
        }

    public PromptVariable build() {
            return new PromptVariable(name, description, trust, required);
        }
    }
}
