// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record PromptBody(PromptEngine engine, String system, String user, String path)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private PromptEngine engine = null;
        private String system = "";
        private String user = "";
        private String path = "";


        public Builder engine(PromptEngine engine) {
            this.engine = Objects.requireNonNull(engine);
            return this;
        }

        public Builder system(String system) {
            this.system = Objects.requireNonNull(system);
            return this;
        }

        public Builder user(String user) {
            this.user = Objects.requireNonNull(user);
            return this;
        }

        public Builder path(String path) {
            this.path = Objects.requireNonNull(path);
            return this;
        }

    public PromptBody build() {
            return new PromptBody(engine, system, user, path);
        }
    }
}
