// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.Objects;


public record PromptTemplateSpec(ContractReference agentDefinitionRef, String purpose, PromptBody template, List<PromptVariable> variables, PromptOutput output, List<String> mayProposeCapabilities, ContractReference workerRequirementProfileRef, ContractReference resourceBudgetRef, AssuranceLevel minimumAssurance, Ring ring, ConversationTask conversationTask)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private ContractReference agentDefinitionRef = null;
        private String purpose = "";
        private PromptBody template = null;
        private List<PromptVariable> variables = List.of();
        private PromptOutput output = null;
        private List<String> mayProposeCapabilities = List.of();
        private ContractReference workerRequirementProfileRef = null;
        private ContractReference resourceBudgetRef = null;
        private AssuranceLevel minimumAssurance = null;
        private Ring ring = null;
        private ConversationTask conversationTask = null;


        public Builder agentDefinitionRef(ContractReference agentDefinitionRef) {
            this.agentDefinitionRef = Objects.requireNonNull(agentDefinitionRef);
            return this;
        }

        public Builder purpose(String purpose) {
            this.purpose = Objects.requireNonNull(purpose);
            return this;
        }

        public Builder template(PromptBody template) {
            this.template = Objects.requireNonNull(template);
            return this;
        }

        public Builder variables(List<PromptVariable> variables) {
            this.variables = Objects.requireNonNull(variables);
            return this;
        }

        public Builder output(PromptOutput output) {
            this.output = Objects.requireNonNull(output);
            return this;
        }

        public Builder mayProposeCapabilities(List<String> mayProposeCapabilities) {
            this.mayProposeCapabilities = Objects.requireNonNull(mayProposeCapabilities);
            return this;
        }

        public Builder workerRequirementProfileRef(ContractReference workerRequirementProfileRef) {
            this.workerRequirementProfileRef = Objects.requireNonNull(workerRequirementProfileRef);
            return this;
        }

        public Builder resourceBudgetRef(ContractReference resourceBudgetRef) {
            this.resourceBudgetRef = Objects.requireNonNull(resourceBudgetRef);
            return this;
        }

        public Builder minimumAssurance(AssuranceLevel minimumAssurance) {
            this.minimumAssurance = Objects.requireNonNull(minimumAssurance);
            return this;
        }

        public Builder ring(Ring ring) {
            this.ring = Objects.requireNonNull(ring);
            return this;
        }

        public Builder conversationTask(ConversationTask conversationTask) {
            this.conversationTask = Objects.requireNonNull(conversationTask);
            return this;
        }

    public PromptTemplateSpec build() {
            return new PromptTemplateSpec(agentDefinitionRef, purpose, template, variables, output, mayProposeCapabilities, workerRequirementProfileRef, resourceBudgetRef, minimumAssurance, ring, conversationTask);
        }
    }
}
