// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum PromptOutputForm {

  STRUCTURED("STRUCTURED"),

  TEXT("TEXT");

  private final static Map<String, PromptOutputForm> MAP;

  static {
    Map<String, PromptOutputForm> map = new HashMap<String, PromptOutputForm>();
    for ( PromptOutputForm value : PromptOutputForm.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  PromptOutputForm(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static PromptOutputForm fromString(String v) {
    return MAP.get(v);
  }

}