// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;


public record ProviderRouting(Integer priority, AccessMode mode, String gatewayRef, ContractReference platformRef, String upstreamHost, List<EffortRungSpec> effortLadder)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private Integer priority = null;
        private AccessMode mode = null;
        private String gatewayRef = "";
        private ContractReference platformRef = null;
        private String upstreamHost = "";
        private List<EffortRungSpec> effortLadder = List.of();


        public Builder priority(Integer priority) {
            this.priority = Objects.requireNonNull(priority);
            return this;
        }

        public Builder mode(AccessMode mode) {
            this.mode = Objects.requireNonNull(mode);
            return this;
        }

        public Builder gatewayRef(String gatewayRef) {
            this.gatewayRef = Objects.requireNonNull(gatewayRef);
            return this;
        }

        public Builder platformRef(ContractReference platformRef) {
            this.platformRef = Objects.requireNonNull(platformRef);
            return this;
        }

        public Builder upstreamHost(String upstreamHost) {
            this.upstreamHost = Objects.requireNonNull(upstreamHost);
            return this;
        }

        public Builder effortLadder(List<EffortRungSpec> effortLadder) {
            this.effortLadder = Objects.requireNonNull(effortLadder);
            return this;
        }

    public ProviderRouting build() {
            return new ProviderRouting(priority, mode, gatewayRef, platformRef, upstreamHost, effortLadder);
        }
    }
}
