// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum ProviderObservationProvenance {

  DIRECT_PROVIDER_API("DIRECT_PROVIDER_API"),

  STRUCTURED_CLI_OUTPUT("STRUCTURED_CLI_OUTPUT"),

  RESPONSE_HEADER("RESPONSE_HEADER"),

  OBSERVED_ERROR("OBSERVED_ERROR"),

  PARSED_HUMAN_OUTPUT("PARSED_HUMAN_OUTPUT"),

  MANUAL_DECLARATION("MANUAL_DECLARATION"),

  ESTIMATE("ESTIMATE");

  private final static Map<String, ProviderObservationProvenance> MAP;

  static {
    Map<String, ProviderObservationProvenance> map = new HashMap<String, ProviderObservationProvenance>();
    for ( ProviderObservationProvenance value : ProviderObservationProvenance.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  ProviderObservationProvenance(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static ProviderObservationProvenance fromString(String v) {
    return MAP.get(v);
  }

}