// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Provider-native reasoning-effort parameters, applied verbatim by RequestShape for the rung's protocol -- OpenAI reasoning_effort, Anthropic thinking budget and max_tokens, Google thinkingConfig.
 */
public record ProviderNativeEffort(String reasoningEffort, Integer maxOutputTokens, Integer thinkingBudgetTokens)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String reasoningEffort = "";
        private Integer maxOutputTokens = null;
        private Integer thinkingBudgetTokens = null;


        public Builder reasoningEffort(String reasoningEffort) {
            this.reasoningEffort = Objects.requireNonNull(reasoningEffort);
            return this;
        }

        public Builder maxOutputTokens(Integer maxOutputTokens) {
            this.maxOutputTokens = Objects.requireNonNull(maxOutputTokens);
            return this;
        }

        public Builder thinkingBudgetTokens(Integer thinkingBudgetTokens) {
            this.thinkingBudgetTokens = Objects.requireNonNull(thinkingBudgetTokens);
            return this;
        }

    public ProviderNativeEffort build() {
            return new ProviderNativeEffort(reasoningEffort, maxOutputTokens, thinkingBudgetTokens);
        }
    }
}
