// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.time.ZonedDateTime;
import java.util.Objects;

/**
 * Recognized opaque binding between a holder provider session and one ExecutionMachine. It never contains a bearer token, refresh token, or provider credential.
 */
public record ProviderSessionBinding(String id, String ownerRealm, String executionMachineRef, ModelAccessAdapter adapter, String providerAccountRef, String sessionFingerprint, String status, ZonedDateTime expiresAt)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String id = "";
        private String ownerRealm = "";
        private String executionMachineRef = "";
        private ModelAccessAdapter adapter = null;
        private String providerAccountRef = "";
        private String sessionFingerprint = "";
        private String status = "";
        private ZonedDateTime expiresAt = null;


        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }

        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder executionMachineRef(String executionMachineRef) {
            this.executionMachineRef = Objects.requireNonNull(executionMachineRef);
            return this;
        }

        public Builder adapter(ModelAccessAdapter adapter) {
            this.adapter = Objects.requireNonNull(adapter);
            return this;
        }

        public Builder providerAccountRef(String providerAccountRef) {
            this.providerAccountRef = Objects.requireNonNull(providerAccountRef);
            return this;
        }

        public Builder sessionFingerprint(String sessionFingerprint) {
            this.sessionFingerprint = Objects.requireNonNull(sessionFingerprint);
            return this;
        }

        public Builder status(String status) {
            this.status = Objects.requireNonNull(status);
            return this;
        }

        public Builder expiresAt(ZonedDateTime expiresAt) {
            this.expiresAt = Objects.requireNonNull(expiresAt);
            return this;
        }

    public ProviderSessionBinding build() {
            return new ProviderSessionBinding(id, ownerRealm, executionMachineRef, adapter, providerAccountRef, sessionFingerprint, status, expiresAt);
        }
    }
}
