// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum ProviderQuotaWindowKind {

  ROLLING("ROLLING"),

  CALENDAR("CALENDAR"),

  METERED("METERED");

  private final static Map<String, ProviderQuotaWindowKind> MAP;

  static {
    Map<String, ProviderQuotaWindowKind> map = new HashMap<String, ProviderQuotaWindowKind>();
    for ( ProviderQuotaWindowKind value : ProviderQuotaWindowKind.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  ProviderQuotaWindowKind(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static ProviderQuotaWindowKind fromString(String v) {
    return MAP.get(v);
  }

}