// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum ProviderOnExhaustion {

  WAIT_FOR_RECOVERY("WAIT_FOR_RECOVERY"),

  USE_AUTHORIZED_ALTERNATIVE("USE_AUTHORIZED_ALTERNATIVE"),

  REQUEST_HUMAN_DECISION("REQUEST_HUMAN_DECISION"),

  STOP_CLEANLY("STOP_CLEANLY");

  private final static Map<String, ProviderOnExhaustion> MAP;

  static {
    Map<String, ProviderOnExhaustion> map = new HashMap<String, ProviderOnExhaustion>();
    for ( ProviderOnExhaustion value : ProviderOnExhaustion.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  ProviderOnExhaustion(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static ProviderOnExhaustion fromString(String v) {
    return MAP.get(v);
  }

}