// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Per-tenant DNS routing for one RealmTemplate. `baseDomain` is deliberately not named `canonicalDomain` or `hostname`: OfferingTopology.canonicalDomain and OfferingTopology.hostname (this same module) already use both names for an inclusion flag, not a domain value -- a third reuse of either name for a different shape would recreate the exact collision the `ProjectionSource`/`ProjectionSpec` naming warns against elsewhere in this metamodel. Deliberately carries no audience, policy, capability or other authority-bearing attribute: Rego refusing two RealmTemplates the same hostname protects routing correctness, not authorization -- that stays on RealmEnforcement.
 */
public record RealmIngressBinding(String subdomain, String baseDomain)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String subdomain = "";
        private String baseDomain = "";


        public Builder subdomain(String subdomain) {
            this.subdomain = Objects.requireNonNull(subdomain);
            return this;
        }

        public Builder baseDomain(String baseDomain) {
            this.baseDomain = Objects.requireNonNull(baseDomain);
            return this;
        }

    public RealmIngressBinding build() {
            return new RealmIngressBinding(subdomain, baseDomain);
        }
    }
}
