// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Exposure and federation posture of the Realm. Defaults to PRIVATE_STEALTH. PRIVATE_STEALTH isolates the Realm from unauthenticated external discovery and intra-cluster visibility. CLUSTER_SHARED allows peer discovery and role sharing within the same hosted cluster. PUBLIC_DISCOVERABLE exposes public agent cards and external federation endpoints.
 */
public enum RealmExposureMode {

  PRIVATE_STEALTH("PRIVATE_STEALTH"),

  CLUSTER_SHARED("CLUSTER_SHARED"),

  PUBLIC_DISCOVERABLE("PUBLIC_DISCOVERABLE");

  private final static Map<String, RealmExposureMode> MAP;

  static {
    Map<String, RealmExposureMode> map = new HashMap<String, RealmExposureMode>();
    for ( RealmExposureMode value : RealmExposureMode.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  RealmExposureMode(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static RealmExposureMode fromString(String v) {
    return MAP.get(v);
  }

}