// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.List;
import java.util.List;
import java.util.Objects;


public record RealmTemplateSpec(String owner, RealmExposureMode exposure, List<RealmSphere> spheres, RealmChiefOfStaffRef chiefOfStaff, String timezone, RealmIngressBinding ingress, RealmEnforcement enforcement, List<ContractReference> policySetRefs, List<ContractReference> principleSetRefs, String contractRepository, List<ContractReference> kitBindingRefs)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String owner = "";
        private RealmExposureMode exposure = null;
        private List<RealmSphere> spheres = List.of();
        private RealmChiefOfStaffRef chiefOfStaff = null;
        private String timezone = "";
        private RealmIngressBinding ingress = null;
        private RealmEnforcement enforcement = null;
        private List<ContractReference> policySetRefs = List.of();
        private List<ContractReference> principleSetRefs = List.of();
        private String contractRepository = "";
        private List<ContractReference> kitBindingRefs = List.of();


        public Builder owner(String owner) {
            this.owner = Objects.requireNonNull(owner);
            return this;
        }

        public Builder exposure(RealmExposureMode exposure) {
            this.exposure = Objects.requireNonNull(exposure);
            return this;
        }

        public Builder spheres(List<RealmSphere> spheres) {
            this.spheres = Objects.requireNonNull(spheres);
            return this;
        }

        public Builder chiefOfStaff(RealmChiefOfStaffRef chiefOfStaff) {
            this.chiefOfStaff = Objects.requireNonNull(chiefOfStaff);
            return this;
        }

        public Builder timezone(String timezone) {
            this.timezone = Objects.requireNonNull(timezone);
            return this;
        }

        public Builder ingress(RealmIngressBinding ingress) {
            this.ingress = Objects.requireNonNull(ingress);
            return this;
        }

        public Builder enforcement(RealmEnforcement enforcement) {
            this.enforcement = Objects.requireNonNull(enforcement);
            return this;
        }

        public Builder policySetRefs(List<ContractReference> policySetRefs) {
            this.policySetRefs = Objects.requireNonNull(policySetRefs);
            return this;
        }

        public Builder principleSetRefs(List<ContractReference> principleSetRefs) {
            this.principleSetRefs = Objects.requireNonNull(principleSetRefs);
            return this;
        }

        public Builder contractRepository(String contractRepository) {
            this.contractRepository = Objects.requireNonNull(contractRepository);
            return this;
        }

        public Builder kitBindingRefs(List<ContractReference> kitBindingRefs) {
            this.kitBindingRefs = Objects.requireNonNull(kitBindingRefs);
            return this;
        }

    public RealmTemplateSpec build() {
            return new RealmTemplateSpec(owner, exposure, spheres, chiefOfStaff, timezone, ingress, enforcement, policySetRefs, principleSetRefs, contractRepository, kitBindingRefs);
        }
    }
}
