// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Organizational grouping only. A sphere never constitutes a security boundary.
 */
public enum RealmSphere {

  PERSONAL("PERSONAL"),

  PROFESSIONAL("PROFESSIONAL"),

  MOBILITY("MOBILITY"),

  HOUSEHOLD("HOUSEHOLD"),

  CLIENT("CLIENT");

  private final static Map<String, RealmSphere> MAP;

  static {
    Map<String, RealmSphere> map = new HashMap<String, RealmSphere>();
    for ( RealmSphere value : RealmSphere.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  RealmSphere(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static RealmSphere fromString(String v) {
    return MAP.get(v);
  }

}