// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * A Realm is a governance, privacy and security boundary. Spheres group work inside a Realm without being security boundaries (canonical decision 12). `ingress` is the same shape one level up, for DNS instead of workspace grouping: `RealmIngressBinding` carries no audience, policy, capability or other authority-bearing attribute, so a subdomain stays routing only by construction, never a security boundary -- `enforcement` on this same spec remains the only field that is.
 */
public record RealmTemplate(String apiVersion, String kind, Metadata metadata, RealmTemplateSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private RealmTemplateSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(RealmTemplateSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public RealmTemplate build() {
            return new RealmTemplate(apiVersion, kind, metadata, spec);
        }
    }
}
