// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record RealmChiefOfStaffRef(ContractReference roleDefinitionRef, ContractReference chiefOfStaffProfileRef)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private ContractReference roleDefinitionRef = null;
        private ContractReference chiefOfStaffProfileRef = null;


        public Builder roleDefinitionRef(ContractReference roleDefinitionRef) {
            this.roleDefinitionRef = Objects.requireNonNull(roleDefinitionRef);
            return this;
        }

        public Builder chiefOfStaffProfileRef(ContractReference chiefOfStaffProfileRef) {
            this.chiefOfStaffProfileRef = Objects.requireNonNull(chiefOfStaffProfileRef);
            return this;
        }

    public RealmChiefOfStaffRef build() {
            return new RealmChiefOfStaffRef(roleDefinitionRef, chiefOfStaffProfileRef);
        }
    }
}
