// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record RecommendedConnectorReference(ContractReference connectorRef, String rationale)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private ContractReference connectorRef = null;
        private String rationale = "";


        public Builder connectorRef(ContractReference connectorRef) {
            this.connectorRef = Objects.requireNonNull(connectorRef);
            return this;
        }

        public Builder rationale(String rationale) {
            this.rationale = Objects.requireNonNull(rationale);
            return this;
        }

    public RecommendedConnectorReference build() {
            return new RecommendedConnectorReference(connectorRef, rationale);
        }
    }
}
