// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record RecommendedCatalogCandidate(String catalogId, String reason)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String catalogId = "";
        private String reason = "";


        public Builder catalogId(String catalogId) {
            this.catalogId = Objects.requireNonNull(catalogId);
            return this;
        }

        public Builder reason(String reason) {
            this.reason = Objects.requireNonNull(reason);
            return this;
        }

    public RecommendedCatalogCandidate build() {
            return new RecommendedCatalogCandidate(catalogId, reason);
        }
    }
}
