// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Provenance for one rendered binary asset or i18n bundle -- same digest-provenance shape as RenderedKitFile, kept a separate class because the source/target patterns admit assetExports' file types instead of `.yml`.
 */
public record RenderedKitAsset(String sourcePath, String targetPath, String digest)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String sourcePath = "";
        private String targetPath = "";
        private String digest = "";


        public Builder sourcePath(String sourcePath) {
            this.sourcePath = Objects.requireNonNull(sourcePath);
            return this;
        }

        public Builder targetPath(String targetPath) {
            this.targetPath = Objects.requireNonNull(targetPath);
            return this;
        }

        public Builder digest(String digest) {
            this.digest = Objects.requireNonNull(digest);
            return this;
        }

    public RenderedKitAsset build() {
            return new RenderedKitAsset(sourcePath, targetPath, digest);
        }
    }
}
