// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record ResourceBudgetSpec(BudgetLimits limits, AssuranceLevel minimumAssurance, BudgetOnExhaustion onExhaustion, Boolean preferDeterministicRouting)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private BudgetLimits limits = null;
        private AssuranceLevel minimumAssurance = null;
        private BudgetOnExhaustion onExhaustion = null;
        private Boolean preferDeterministicRouting = null;


        public Builder limits(BudgetLimits limits) {
            this.limits = Objects.requireNonNull(limits);
            return this;
        }

        public Builder minimumAssurance(AssuranceLevel minimumAssurance) {
            this.minimumAssurance = Objects.requireNonNull(minimumAssurance);
            return this;
        }

        public Builder onExhaustion(BudgetOnExhaustion onExhaustion) {
            this.onExhaustion = Objects.requireNonNull(onExhaustion);
            return this;
        }

        public Builder preferDeterministicRouting(Boolean preferDeterministicRouting) {
            this.preferDeterministicRouting = Objects.requireNonNull(preferDeterministicRouting);
            return this;
        }

    public ResourceBudgetSpec build() {
            return new ResourceBudgetSpec(limits, minimumAssurance, onExhaustion, preferDeterministicRouting);
        }
    }
}
