// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum Reversibility {

  REVERSIBLE("REVERSIBLE"),

  IRREVERSIBLE("IRREVERSIBLE");

  private final static Map<String, Reversibility> MAP;

  static {
    Map<String, Reversibility> map = new HashMap<String, Reversibility>();
    for ( Reversibility value : Reversibility.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  Reversibility(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static Reversibility fromString(String v) {
    return MAP.get(v);
  }

}