// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * ROOT capabilities are Ring 0 and are never grantable through an ordinary workflow.
 */
public enum RiskTier {

  LOW("LOW"),

  MEDIUM("MEDIUM"),

  HIGH("HIGH"),

  ROOT("ROOT");

  private final static Map<String, RiskTier> MAP;

  static {
    Map<String, RiskTier> map = new HashMap<String, RiskTier>();
    for ( RiskTier value : RiskTier.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  RiskTier(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static RiskTier fromString(String v) {
    return MAP.get(v);
  }

}