// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;


public record RoleLifecyclePolicySpec(String ownerRealm, int shadowEpisodesRequired, int boundedTrialEpisodesRequired, int maxTrialDurationDays, List<String> evaluationCriteria)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ownerRealm = "";
        private int shadowEpisodesRequired = 0;
        private int boundedTrialEpisodesRequired = 0;
        private int maxTrialDurationDays = 0;
        private List<String> evaluationCriteria = List.of();


        public Builder ownerRealm(String ownerRealm) {
            this.ownerRealm = Objects.requireNonNull(ownerRealm);
            return this;
        }

        public Builder shadowEpisodesRequired(int shadowEpisodesRequired) {
            this.shadowEpisodesRequired = Objects.requireNonNull(shadowEpisodesRequired);
            return this;
        }

        public Builder boundedTrialEpisodesRequired(int boundedTrialEpisodesRequired) {
            this.boundedTrialEpisodesRequired = Objects.requireNonNull(boundedTrialEpisodesRequired);
            return this;
        }

        public Builder maxTrialDurationDays(int maxTrialDurationDays) {
            this.maxTrialDurationDays = Objects.requireNonNull(maxTrialDurationDays);
            return this;
        }

        public Builder evaluationCriteria(List<String> evaluationCriteria) {
            this.evaluationCriteria = Objects.requireNonNull(evaluationCriteria);
            return this;
        }

    public RoleLifecyclePolicySpec build() {
            return new RoleLifecyclePolicySpec(ownerRealm, shadowEpisodesRequired, boundedTrialEpisodesRequired, maxTrialDurationDays, evaluationCriteria);
        }
    }
}
