// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Onboarding policy and evaluation criteria for roles. Renamed from OperatorLifecyclePolicy -- kept as its own class, not absorbed into RoleDefinition.
 */
public record RoleLifecyclePolicy(String apiVersion, String kind, Metadata metadata, RoleLifecyclePolicySpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private RoleLifecyclePolicySpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(RoleLifecyclePolicySpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public RoleLifecyclePolicy build() {
            return new RoleLifecyclePolicy(apiVersion, kind, metadata, spec);
        }
    }
}
