// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Deterministic link between a payload, its LinkML class, and exact schema digest.
 */
public record SchemaBinding(String modelClass, String schemaVersion, String schemaId, String schemaDigest, SchemaProfile profile)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String modelClass = "";
        private String schemaVersion = "";
        private String schemaId = "";
        private String schemaDigest = "";
        private SchemaProfile profile = null;


        public Builder modelClass(String modelClass) {
            this.modelClass = Objects.requireNonNull(modelClass);
            return this;
        }

        public Builder schemaVersion(String schemaVersion) {
            this.schemaVersion = Objects.requireNonNull(schemaVersion);
            return this;
        }

        public Builder schemaId(String schemaId) {
            this.schemaId = Objects.requireNonNull(schemaId);
            return this;
        }

        public Builder schemaDigest(String schemaDigest) {
            this.schemaDigest = Objects.requireNonNull(schemaDigest);
            return this;
        }

        public Builder profile(SchemaProfile profile) {
            this.profile = Objects.requireNonNull(profile);
            return this;
        }

    public SchemaBinding build() {
            return new SchemaBinding(modelClass, schemaVersion, schemaId, schemaDigest, profile);
        }
    }
}
