// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Bounded dynamic JSON payload guaranteed by a validated SchemaBinding.
 */
public record SchemaBoundPayload(SchemaBinding schemaBinding, String payloadJson, String payloadDigest, Boolean validated)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private SchemaBinding schemaBinding = null;
        private String payloadJson = "";
        private String payloadDigest = "";
        private Boolean validated = null;


        public Builder schemaBinding(SchemaBinding schemaBinding) {
            this.schemaBinding = Objects.requireNonNull(schemaBinding);
            return this;
        }

        public Builder payloadJson(String payloadJson) {
            this.payloadJson = Objects.requireNonNull(payloadJson);
            return this;
        }

        public Builder payloadDigest(String payloadDigest) {
            this.payloadDigest = Objects.requireNonNull(payloadDigest);
            return this;
        }

        public Builder validated(Boolean validated) {
            this.validated = Objects.requireNonNull(validated);
            return this;
        }

    public SchemaBoundPayload build() {
            return new SchemaBoundPayload(schemaBinding, payloadJson, payloadDigest, validated);
        }
    }
}
