// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record SecretRotation(Boolean required, String maximumAge)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private Boolean required = null;
        private String maximumAge = "";


        public Builder required(Boolean required) {
            this.required = Objects.requireNonNull(required);
            return this;
        }

        public Builder maximumAge(String maximumAge) {
            this.maximumAge = Objects.requireNonNull(maximumAge);
            return this;
        }

    public SecretRotation build() {
            return new SecretRotation(required, maximumAge);
        }
    }
}
