// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum SecretInjectionTarget {

  MCP_PROCESS_ONLY("MCP_PROCESS_ONLY"),

  FORGE_APPLIER_PROCESS_ONLY("FORGE_APPLIER_PROCESS_ONLY"),

  MODEL_WORKER_PROCESS_ONLY("MODEL_WORKER_PROCESS_ONLY"),

  REGISTRY_WORKER_PROCESS_ONLY("REGISTRY_WORKER_PROCESS_ONLY");

  private final static Map<String, SecretInjectionTarget> MAP;

  static {
    Map<String, SecretInjectionTarget> map = new HashMap<String, SecretInjectionTarget>();
    for ( SecretInjectionTarget value : SecretInjectionTarget.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  SecretInjectionTarget(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static SecretInjectionTarget fromString(String v) {
    return MAP.get(v);
  }

}