// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record SecretInjection(SecretInjectionTarget target, String environmentVariable, String fileName)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private SecretInjectionTarget target = null;
        private String environmentVariable = "";
        private String fileName = "";


        public Builder target(SecretInjectionTarget target) {
            this.target = Objects.requireNonNull(target);
            return this;
        }

        public Builder environmentVariable(String environmentVariable) {
            this.environmentVariable = Objects.requireNonNull(environmentVariable);
            return this;
        }

        public Builder fileName(String fileName) {
            this.fileName = Objects.requireNonNull(fileName);
            return this;
        }

    public SecretInjection build() {
            return new SecretInjection(target, environmentVariable, fileName);
        }
    }
}
