// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;


public record SelfDescriptionSpec(SelfDescriptionSubject subject, List<SelfDescriptionAnswer> answers, AgentCard agentCard)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private SelfDescriptionSubject subject = null;
        private List<SelfDescriptionAnswer> answers = List.of();
        private AgentCard agentCard = null;


        public Builder subject(SelfDescriptionSubject subject) {
            this.subject = Objects.requireNonNull(subject);
            return this;
        }

        public Builder answers(List<SelfDescriptionAnswer> answers) {
            this.answers = Objects.requireNonNull(answers);
            return this;
        }

        public Builder agentCard(AgentCard agentCard) {
            this.agentCard = Objects.requireNonNull(agentCard);
            return this;
        }

    public SelfDescriptionSpec build() {
            return new SelfDescriptionSpec(subject, answers, agentCard);
        }
    }
}
