// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.List;
import java.util.Objects;


public record SelfDescriptionAnswer(SelfDescriptionQuestion question, List<SelfDescriptionFact> facts, ContractReference narrationPromptTemplateRef, List<SelfDescriptionAudience> audience)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private SelfDescriptionQuestion question = null;
        private List<SelfDescriptionFact> facts = List.of();
        private ContractReference narrationPromptTemplateRef = null;
        private List<SelfDescriptionAudience> audience = List.of();


        public Builder question(SelfDescriptionQuestion question) {
            this.question = Objects.requireNonNull(question);
            return this;
        }

        public Builder facts(List<SelfDescriptionFact> facts) {
            this.facts = Objects.requireNonNull(facts);
            return this;
        }

        public Builder narrationPromptTemplateRef(ContractReference narrationPromptTemplateRef) {
            this.narrationPromptTemplateRef = Objects.requireNonNull(narrationPromptTemplateRef);
            return this;
        }

        public Builder audience(List<SelfDescriptionAudience> audience) {
            this.audience = Objects.requireNonNull(audience);
            return this;
        }

    public SelfDescriptionAnswer build() {
            return new SelfDescriptionAnswer(question, facts, narrationPromptTemplateRef, audience);
        }
    }
}
