// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum SelfDescriptionAudience {

  HUMAN("HUMAN"),

  AGENT("AGENT"),

  CLIENT("CLIENT");

  private final static Map<String, SelfDescriptionAudience> MAP;

  static {
    Map<String, SelfDescriptionAudience> map = new HashMap<String, SelfDescriptionAudience>();
    for ( SelfDescriptionAudience value : SelfDescriptionAudience.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  SelfDescriptionAudience(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static SelfDescriptionAudience fromString(String v) {
    return MAP.get(v);
  }

}