// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum SelfDescriptionSubjectKind {

  PROJECT("Project"),

  AGENTARCHETYPE("AgentArchetype"),

  REALM("Realm"),

  ROLE("Role");

  private final static Map<String, SelfDescriptionSubjectKind> MAP;

  static {
    Map<String, SelfDescriptionSubjectKind> map = new HashMap<String, SelfDescriptionSubjectKind>();
    for ( SelfDescriptionSubjectKind value : SelfDescriptionSubjectKind.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  SelfDescriptionSubjectKind(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static SelfDescriptionSubjectKind fromString(String v) {
    return MAP.get(v);
  }

}