// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record SelfDescriptionFact(String name, String from, Boolean redactBeyondBoundary)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String name = "";
        private String from = "";
        private Boolean redactBeyondBoundary = null;


        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }

        public Builder from(String from) {
            this.from = Objects.requireNonNull(from);
            return this;
        }

        public Builder redactBeyondBoundary(Boolean redactBeyondBoundary) {
            this.redactBeyondBoundary = Objects.requireNonNull(redactBeyondBoundary);
            return this;
        }

    public SelfDescriptionFact build() {
            return new SelfDescriptionFact(name, from, redactBeyondBoundary);
        }
    }
}
