// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Who must approve a forge-write against a shared repository binding. OWNER_ONLY applies when a single Realm owns the binding. MUTUAL_CONSENT blocks merge until all co-owner Realms have acknowledged.
 */
public enum SharedRepositoryApprovalPolicy {

  OWNER_ONLY("OWNER_ONLY"),

  MUTUAL_CONSENT("MUTUAL_CONSENT");

  private final static Map<String, SharedRepositoryApprovalPolicy> MAP;

  static {
    Map<String, SharedRepositoryApprovalPolicy> map = new HashMap<String, SharedRepositoryApprovalPolicy>();
    for ( SharedRepositoryApprovalPolicy value : SharedRepositoryApprovalPolicy.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  SharedRepositoryApprovalPolicy(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static SharedRepositoryApprovalPolicy fromString(String v) {
    return MAP.get(v);
  }

}