// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum SlaTier {

  NONE("NONE"),

  BEST_EFFORT("BEST_EFFORT"),

  GUARANTEED("GUARANTEED");

  private final static Map<String, SlaTier> MAP;

  static {
    Map<String, SlaTier> map = new HashMap<String, SlaTier>();
    for ( SlaTier value : SlaTier.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  SlaTier(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static SlaTier fromString(String v) {
    return MAP.get(v);
  }

}