// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * The only way one Project or Realm may solicit another (canonical decision 25). Exposes a typed interface, never internal Project data. Renamed from DelegationContract: the word "delegation" is reserved for authority delegation, explicitly excluded from V1, and this schema never modeled that -- it models a typed cross-Project request contract.
 */
public record SolicitationContract(String apiVersion, String kind, Metadata metadata, SolicitationContractSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private SolicitationContractSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(SolicitationContractSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public SolicitationContract build() {
            return new SolicitationContract(apiVersion, kind, metadata, spec);
        }
    }
}
