// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum StructuredOutputMode {

  NATIVE_JSON_SCHEMA("NATIVE_JSON_SCHEMA"),

  PROMPTED_JSON_VALIDATED("PROMPTED_JSON_VALIDATED"),

  UNSUPPORTED("UNSUPPORTED");

  private final static Map<String, StructuredOutputMode> MAP;

  static {
    Map<String, StructuredOutputMode> map = new HashMap<String, StructuredOutputMode>();
    for ( StructuredOutputMode value : StructuredOutputMode.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  StructuredOutputMode(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static StructuredOutputMode fromString(String v) {
    return MAP.get(v);
  }

}