// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * A profile's disposition on an INSUFFICIENT_NEEDS_DEPTH signal (ADR-0019). NONE is the default: no automatic retry, the existing human-decision path applies. AUTO_BOUNDED retries the same invocation once at the next effort rung, never above the ladder's own ceiling and only while the declared ResourceBudget still has model-call budget for it -- otherwise it falls back to the same human-decision path as NONE.
 */
public enum SufficiencyEscalationPolicy {

  NONE("NONE"),

  AUTO_BOUNDED("AUTO_BOUNDED");

  private final static Map<String, SufficiencyEscalationPolicy> MAP;

  static {
    Map<String, SufficiencyEscalationPolicy> map = new HashMap<String, SufficiencyEscalationPolicy>();
    for ( SufficiencyEscalationPolicy value : SufficiencyEscalationPolicy.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  SufficiencyEscalationPolicy(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static SufficiencyEscalationPolicy fromString(String v) {
    return MAP.get(v);
  }

}