// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Realm-declared, per-machine opt-in for the ADR-0056 SYSTEM_EFFECT driver (linux-root-effect-executor AC2). No machine may receive a SYSTEM_EFFECT WorkloadCommand unless one of these names it, optedIn is true, and its own tested-restore attestation is still fresh -- the owner declares the attestation in this same contract rather than a separate observation, so the two facts cannot drift apart.
 */
public record SystemEffectPolicy(String apiVersion, String kind, Metadata metadata, SystemEffectPolicySpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private SystemEffectPolicySpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(SystemEffectPolicySpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public SystemEffectPolicy build() {
            return new SystemEffectPolicy(apiVersion, kind, metadata, spec);
        }
    }
}
