// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum TaskClass {

  CLASSIFICATION("CLASSIFICATION"),

  NARRATION("NARRATION"),

  REASONING("REASONING"),

  CODING("CODING"),

  VERIFICATION("VERIFICATION"),

  REALTIME_DIALOGUE("REALTIME_DIALOGUE");

  private final static Map<String, TaskClass> MAP;

  static {
    Map<String, TaskClass> map = new HashMap<String, TaskClass>();
    for ( TaskClass value : TaskClass.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  TaskClass(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static TaskClass fromString(String v) {
    return MAP.get(v);
  }

}