// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;


public record TeamCoordination(List<CoordinationMechanismBinding> mechanisms, ContractReference leadRoleDefinitionRef)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private List<CoordinationMechanismBinding> mechanisms = List.of();
        private ContractReference leadRoleDefinitionRef = null;


        public Builder mechanisms(List<CoordinationMechanismBinding> mechanisms) {
            this.mechanisms = Objects.requireNonNull(mechanisms);
            return this;
        }

        public Builder leadRoleDefinitionRef(ContractReference leadRoleDefinitionRef) {
            this.leadRoleDefinitionRef = Objects.requireNonNull(leadRoleDefinitionRef);
            return this;
        }

    public TeamCoordination build() {
            return new TeamCoordination(mechanisms, leadRoleDefinitionRef);
        }
    }
}
