// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record TerminologyEntry(String roleKey, String displayName)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String roleKey = "";
        private String displayName = "";


        public Builder roleKey(String roleKey) {
            this.roleKey = Objects.requireNonNull(roleKey);
            return this;
        }

        public Builder displayName(String displayName) {
            this.displayName = Objects.requireNonNull(displayName);
            return this;
        }

    public TerminologyEntry build() {
            return new TerminologyEntry(roleKey, displayName);
        }
    }
}
