// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;


public record ThemeRoom(String roomId, String background, List<ThemeObjectForm> objectForms, VersionedJsonAsset sceneManifest)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String roomId = "";
        private String background = "";
        private List<ThemeObjectForm> objectForms = List.of();
        private VersionedJsonAsset sceneManifest = null;


        public Builder roomId(String roomId) {
            this.roomId = Objects.requireNonNull(roomId);
            return this;
        }

        public Builder background(String background) {
            this.background = Objects.requireNonNull(background);
            return this;
        }

        public Builder objectForms(List<ThemeObjectForm> objectForms) {
            this.objectForms = Objects.requireNonNull(objectForms);
            return this;
        }

        public Builder sceneManifest(VersionedJsonAsset sceneManifest) {
            this.sceneManifest = Objects.requireNonNull(sceneManifest);
            return this;
        }

    public ThemeRoom build() {
            return new ThemeRoom(roomId, background, objectForms, sceneManifest);
        }
    }
}
