// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;


public record ThemeVisualization(String ecosystem, String palette, ThemePresence presence, List<ThemeRoom> rooms)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String ecosystem = "";
        private String palette = "";
        private ThemePresence presence = null;
        private List<ThemeRoom> rooms = List.of();


        public Builder ecosystem(String ecosystem) {
            this.ecosystem = Objects.requireNonNull(ecosystem);
            return this;
        }

        public Builder palette(String palette) {
            this.palette = Objects.requireNonNull(palette);
            return this;
        }

        public Builder presence(ThemePresence presence) {
            this.presence = Objects.requireNonNull(presence);
            return this;
        }

        public Builder rooms(List<ThemeRoom> rooms) {
            this.rooms = Objects.requireNonNull(rooms);
            return this;
        }

    public ThemeVisualization build() {
            return new ThemeVisualization(ecosystem, palette, presence, rooms);
        }
    }
}
