// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * How the Chief of Staff is drawn on a surface. Every field here is presentation: there is no data source, no scope and no threshold, so the representation cannot become the thing represented.
 */
public record ThemePresence(String chiefOfStaffForm, PresenceDensity density, PresenceMotion motion, VersionedJsonAsset livingBitmapManifest)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String chiefOfStaffForm = "";
        private PresenceDensity density = null;
        private PresenceMotion motion = null;
        private VersionedJsonAsset livingBitmapManifest = null;


        public Builder chiefOfStaffForm(String chiefOfStaffForm) {
            this.chiefOfStaffForm = Objects.requireNonNull(chiefOfStaffForm);
            return this;
        }

        public Builder density(PresenceDensity density) {
            this.density = Objects.requireNonNull(density);
            return this;
        }

        public Builder motion(PresenceMotion motion) {
            this.motion = Objects.requireNonNull(motion);
            return this;
        }

        public Builder livingBitmapManifest(VersionedJsonAsset livingBitmapManifest) {
            this.livingBitmapManifest = Objects.requireNonNull(livingBitmapManifest);
            return this;
        }

    public ThemePresence build() {
            return new ThemePresence(chiefOfStaffForm, density, motion, livingBitmapManifest);
        }
    }
}
