// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record ThemeLocalizedName(String locale, String name)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String locale = "";
        private String name = "";


        public Builder locale(String locale) {
            this.locale = Objects.requireNonNull(locale);
            return this;
        }

        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }

    public ThemeLocalizedName build() {
            return new ThemeLocalizedName(locale, name);
        }
    }
}
