// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * A bounded navigation hint. Routes, actions, coordinates and executable handlers are deliberately absent.
 */
public record ThemeHotspot(String id, String targetSurfaceId, String labelKey, ThemeHotspotZone zone)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String id = "";
        private String targetSurfaceId = "";
        private String labelKey = "";
        private ThemeHotspotZone zone = null;


        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }

        public Builder targetSurfaceId(String targetSurfaceId) {
            this.targetSurfaceId = Objects.requireNonNull(targetSurfaceId);
            return this;
        }

        public Builder labelKey(String labelKey) {
            this.labelKey = Objects.requireNonNull(labelKey);
            return this;
        }

        public Builder zone(ThemeHotspotZone zone) {
            this.zone = Objects.requireNonNull(zone);
            return this;
        }

    public ThemeHotspot build() {
            return new ThemeHotspot(id, targetSurfaceId, labelKey, zone);
        }
    }
}
