// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.List;
import java.util.Objects;


public record ThemeVoice(VoiceStyle style, VoiceVerbosity verbosity, List<ThemeVoiceRoleOverride> roleOverrides)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private VoiceStyle style = null;
        private VoiceVerbosity verbosity = null;
        private List<ThemeVoiceRoleOverride> roleOverrides = List.of();


        public Builder style(VoiceStyle style) {
            this.style = Objects.requireNonNull(style);
            return this;
        }

        public Builder verbosity(VoiceVerbosity verbosity) {
            this.verbosity = Objects.requireNonNull(verbosity);
            return this;
        }

        public Builder roleOverrides(List<ThemeVoiceRoleOverride> roleOverrides) {
            this.roleOverrides = Objects.requireNonNull(roleOverrides);
            return this;
        }

    public ThemeVoice build() {
            return new ThemeVoice(style, verbosity, roleOverrides);
        }
    }
}
