// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Informative only -- origin, authorship, source and license notes carry no capability, policy or assurance and are never validated for completeness (AC4).
 */
public record ThemeCreativeRights(String origin, String author, String source, String license, String notes)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String origin = "";
        private String author = "";
        private String source = "";
        private String license = "";
        private String notes = "";


        public Builder origin(String origin) {
            this.origin = Objects.requireNonNull(origin);
            return this;
        }

        public Builder author(String author) {
            this.author = Objects.requireNonNull(author);
            return this;
        }

        public Builder source(String source) {
            this.source = Objects.requireNonNull(source);
            return this;
        }

        public Builder license(String license) {
            this.license = Objects.requireNonNull(license);
            return this;
        }

        public Builder notes(String notes) {
            this.notes = Objects.requireNonNull(notes);
            return this;
        }

    public ThemeCreativeRights build() {
            return new ThemeCreativeRights(origin, author, source, license, notes);
        }
    }
}
