// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record ThemeLocalization(String locale, VersionedJsonAsset messages)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String locale = "";
        private VersionedJsonAsset messages = null;


        public Builder locale(String locale) {
            this.locale = Objects.requireNonNull(locale);
            return this;
        }

        public Builder messages(VersionedJsonAsset messages) {
            this.messages = Objects.requireNonNull(messages);
            return this;
        }

    public ThemeLocalization build() {
            return new ThemeLocalization(locale, messages);
        }
    }
}
