// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record ThemeManifestSet(VersionedJsonAsset shell, VersionedJsonAsset components, VersionedJsonAsset motion, VersionedJsonAsset illustrations)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private VersionedJsonAsset shell = null;
        private VersionedJsonAsset components = null;
        private VersionedJsonAsset motion = null;
        private VersionedJsonAsset illustrations = null;


        public Builder shell(VersionedJsonAsset shell) {
            this.shell = Objects.requireNonNull(shell);
            return this;
        }

        public Builder components(VersionedJsonAsset components) {
            this.components = Objects.requireNonNull(components);
            return this;
        }

        public Builder motion(VersionedJsonAsset motion) {
            this.motion = Objects.requireNonNull(motion);
            return this;
        }

        public Builder illustrations(VersionedJsonAsset illustrations) {
            this.illustrations = Objects.requireNonNull(illustrations);
            return this;
        }

    public ThemeManifestSet build() {
            return new ThemeManifestSet(shell, components, motion, illustrations);
        }
    }
}
