// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum TopologyPlacement {

  DEDICATED("DEDICATED"),

  SHARED("SHARED");

  private final static Map<String, TopologyPlacement> MAP;

  static {
    Map<String, TopologyPlacement> map = new HashMap<String, TopologyPlacement>();
    for ( TopologyPlacement value : TopologyPlacement.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  TopologyPlacement(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static TopologyPlacement fromString(String v) {
    return MAP.get(v);
  }

}