// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Reason required when disposition is WITHHELD or QUARANTINED (Rego): exposing a tool is justified by the operation that maps it to a capability; holding one back has no such document, so the reason lives here or nowhere.
 */
public record UpstreamToolEntry(String upstreamToolName, UpstreamToolDisposition disposition, String reason)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String upstreamToolName = "";
        private UpstreamToolDisposition disposition = null;
        private String reason = "";


        public Builder upstreamToolName(String upstreamToolName) {
            this.upstreamToolName = Objects.requireNonNull(upstreamToolName);
            return this;
        }

        public Builder disposition(UpstreamToolDisposition disposition) {
            this.disposition = Objects.requireNonNull(disposition);
            return this;
        }

        public Builder reason(String reason) {
            this.reason = Objects.requireNonNull(reason);
            return this;
        }

    public UpstreamToolEntry build() {
            return new UpstreamToolEntry(upstreamToolName, disposition, reason);
        }
    }
}
