// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * A schema-versioned JSON theme asset. V1 repository-relative .jumo/assets paths remain readable; ThemePack v2 uses a normalized path relative to the autonomous pack directory. Runtime resolution stays bound to the exact source and pack that declared the reference.
 */
public record VersionedJsonAsset(String schemaVersion, String asset)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String schemaVersion = "";
        private String asset = "";


        public Builder schemaVersion(String schemaVersion) {
            this.schemaVersion = Objects.requireNonNull(schemaVersion);
            return this;
        }

        public Builder asset(String asset) {
            this.asset = Objects.requireNonNull(asset);
            return this;
        }

    public VersionedJsonAsset build() {
            return new VersionedJsonAsset(schemaVersion, asset);
        }
    }
}
