// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Generated concept glossary. One entry per CONTRACT kind names its canonical class, English and French display and plural forms, target instance directory and commit trailer -- the single source every directory, trailer, UI label and metamodel description name is renamed to match (canonical decision 15's sibling for vocabulary).
 */
public record VocabularySet(String apiVersion, String kind, Metadata metadata, VocabularySetSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private VocabularySetSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(VocabularySetSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public VocabularySet build() {
            return new VocabularySet(apiVersion, kind, metadata, spec);
        }
    }
}
