// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum VoiceStyle {

  CALM_PRECISE("CALM_PRECISE"),

  DIRECT("DIRECT"),

  ANALYTICAL("ANALYTICAL"),

  WARM("WARM");

  private final static Map<String, VoiceStyle> MAP;

  static {
    Map<String, VoiceStyle> map = new HashMap<String, VoiceStyle>();
    for ( VoiceStyle value : VoiceStyle.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  VoiceStyle(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static VoiceStyle fromString(String v) {
    return MAP.get(v);
  }

}