// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * The CLI a worker substrate runs. Shared vocabulary -- a WorkerSubstrate declares which one it runs (integration) and a CliToolDefinition declares which one it implements (execution), so neither module has to import the other and no naming convention links a tool to a value.
 */
public enum WorkerCli {

  CLAUDE_CODE("CLAUDE_CODE"),

  CODEX("CODEX"),

  GEMINI_CLI("GEMINI_CLI"),

  COPILOT_CLI("COPILOT_CLI");

  private final static Map<String, WorkerCli> MAP;

  static {
    Map<String, WorkerCli> map = new HashMap<String, WorkerCli>();
    for ( WorkerCli value : WorkerCli.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  WorkerCli(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static WorkerCli fromString(String v) {
    return MAP.get(v);
  }

}