// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum WorkloadCommandStatus {

  QUEUED("QUEUED"),

  CLAIMED("CLAIMED"),

  STARTED("STARTED"),

  COMPLETED("COMPLETED"),

  FAILED("FAILED"),

  TIMED_OUT("TIMED_OUT"),

  CANCELLED("CANCELLED"),

  EXPIRED("EXPIRED");

  private final static Map<String, WorkloadCommandStatus> MAP;

  static {
    Map<String, WorkloadCommandStatus> map = new HashMap<String, WorkloadCommandStatus>();
    for ( WorkloadCommandStatus value : WorkloadCommandStatus.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  WorkloadCommandStatus(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static WorkloadCommandStatus fromString(String v) {
    return MAP.get(v);
  }

}