// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record WorkerInteractionRequirement(ToolUseRequirement toolUse, ToolUseRequirement structuredOutput)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private ToolUseRequirement toolUse = null;
        private ToolUseRequirement structuredOutput = null;


        public Builder toolUse(ToolUseRequirement toolUse) {
            this.toolUse = Objects.requireNonNull(toolUse);
            return this;
        }

        public Builder structuredOutput(ToolUseRequirement structuredOutput) {
            this.structuredOutput = Objects.requireNonNull(structuredOutput);
            return this;
        }

    public WorkerInteractionRequirement build() {
            return new WorkerInteractionRequirement(toolUse, structuredOutput);
        }
    }
}
