// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record WorkerContextRequirement(int minimumTokens, ContextRetrievalMode retrievalMode)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private int minimumTokens = 0;
        private ContextRetrievalMode retrievalMode = null;


        public Builder minimumTokens(int minimumTokens) {
            this.minimumTokens = Objects.requireNonNull(minimumTokens);
            return this;
        }

        public Builder retrievalMode(ContextRetrievalMode retrievalMode) {
            this.retrievalMode = Objects.requireNonNull(retrievalMode);
            return this;
        }

    public WorkerContextRequirement build() {
            return new WorkerContextRequirement(minimumTokens, retrievalMode);
        }
    }
}
