// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum WorkerSubstrateKind {

  LOCAL_CLI_CONTAINER("LOCAL_CLI_CONTAINER"),

  MODEL_WORKER_PROCESS("MODEL_WORKER_PROCESS");

  private final static Map<String, WorkerSubstrateKind> MAP;

  static {
    Map<String, WorkerSubstrateKind> map = new HashMap<String, WorkerSubstrateKind>();
    for ( WorkerSubstrateKind value : WorkerSubstrateKind.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  WorkerSubstrateKind(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static WorkerSubstrateKind fromString(String v) {
    return MAP.get(v);
  }

}