// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * PROPOSED and ACCEPTED are separate because a work order is not an acceptance, in the same way a CapturedInput is not a Commitment.
 */
public enum WorkOrderState {

  PROPOSED("PROPOSED"),

  ACCEPTED("ACCEPTED"),

  IN_PROGRESS("IN_PROGRESS"),

  DECLINED("DECLINED"),

  COMPLETED("COMPLETED"),

  FAILED("FAILED");

  private final static Map<String, WorkOrderState> MAP;

  static {
    Map<String, WorkOrderState> map = new HashMap<String, WorkOrderState>();
    for ( WorkOrderState value : WorkOrderState.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  WorkOrderState(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static WorkOrderState fromString(String v) {
    return MAP.get(v);
  }

}