// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record WorkerLimits(String maximumLatency, CostClass maximumCostClass)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String maximumLatency = "";
        private CostClass maximumCostClass = null;


        public Builder maximumLatency(String maximumLatency) {
            this.maximumLatency = Objects.requireNonNull(maximumLatency);
            return this;
        }

        public Builder maximumCostClass(CostClass maximumCostClass) {
            this.maximumCostClass = Objects.requireNonNull(maximumCostClass);
            return this;
        }

    public WorkerLimits build() {
            return new WorkerLimits(maximumLatency, maximumCostClass);
        }
    }
}
