// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;

/* metamodel_version: 1.11.0 */
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum WorkOrderDeclineReason {

  OUT_OF_SCOPE("OUT_OF_SCOPE"),

  NO_CAPABILITY("NO_CAPABILITY"),

  OVER_BUDGET("OVER_BUDGET"),

  CONFLICTING_COMMITMENT("CONFLICTING_COMMITMENT"),

  AMBIGUOUS("AMBIGUOUS"),

  /**
   * Absorbed into another WorkOrder that carries the same acceptance criteria forward.
   */
  SUPERSEDED("SUPERSEDED");

  private final static Map<String, WorkOrderDeclineReason> MAP;

  static {
    Map<String, WorkOrderDeclineReason> map = new HashMap<String, WorkOrderDeclineReason>();
    for ( WorkOrderDeclineReason value : WorkOrderDeclineReason.values() ) {
      map.put(value.toString(), value);
    }

    MAP = Collections.unmodifiableMap(map);
  }

  private final String repr;

  WorkOrderDeclineReason(String repr) {
    this.repr = repr;
  }

  @Override
  public String toString() {
    return repr;
  }

  @JsonCreator
  public static WorkOrderDeclineReason fromString(String v) {
    return MAP.get(v);
  }

}