// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * A multi-dimensional task requirement vector used to select an eligible runtime Worker. Names neither provider nor model and defines no aggregate power score.
 */
public record WorkerRequirementProfile(String apiVersion, String kind, Metadata metadata, WorkerRequirementProfileSpec spec)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String apiVersion = "";
        private String kind = "";
        private Metadata metadata = null;
        private WorkerRequirementProfileSpec spec = null;


        public Builder apiVersion(String apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder kind(String kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = Objects.requireNonNull(metadata);
            return this;
        }

        public Builder spec(WorkerRequirementProfileSpec spec) {
            this.spec = Objects.requireNonNull(spec);
            return this;
        }

    public WorkerRequirementProfile build() {
            return new WorkerRequirementProfile(apiVersion, kind, metadata, spec);
        }
    }
}
