// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record WorkOrderSpecification(String title, String body)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String title = "";
        private String body = "";


        public Builder title(String title) {
            this.title = Objects.requireNonNull(title);
            return this;
        }

        public Builder body(String body) {
            this.body = Objects.requireNonNull(body);
            return this;
        }

    public WorkOrderSpecification build() {
            return new WorkOrderSpecification(title, body);
        }
    }
}
