// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record WorkerImage(String reference, String digest)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String reference = "";
        private String digest = "";


        public Builder reference(String reference) {
            this.reference = Objects.requireNonNull(reference);
            return this;
        }

        public Builder digest(String digest) {
            this.digest = Objects.requireNonNull(digest);
            return this;
        }

    public WorkerImage build() {
            return new WorkerImage(reference, digest);
        }
    }
}
