// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;

/**
 * Terminal outcome of a claimed WorkloadCommand, sanitized before it leaves the machine.
 */
public record WorkloadCommandResult(String commandId, String machineId, WorkloadCommandStatus status, String sanitizedEvidence, String evidenceDigest, String completedAt)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String commandId = "";
        private String machineId = "";
        private WorkloadCommandStatus status = null;
        private String sanitizedEvidence = "";
        private String evidenceDigest = "";
        private String completedAt = "";


        public Builder commandId(String commandId) {
            this.commandId = Objects.requireNonNull(commandId);
            return this;
        }

        public Builder machineId(String machineId) {
            this.machineId = Objects.requireNonNull(machineId);
            return this;
        }

        public Builder status(WorkloadCommandStatus status) {
            this.status = Objects.requireNonNull(status);
            return this;
        }

        public Builder sanitizedEvidence(String sanitizedEvidence) {
            this.sanitizedEvidence = Objects.requireNonNull(sanitizedEvidence);
            return this;
        }

        public Builder evidenceDigest(String evidenceDigest) {
            this.evidenceDigest = Objects.requireNonNull(evidenceDigest);
            return this;
        }

        public Builder completedAt(String completedAt) {
            this.completedAt = Objects.requireNonNull(completedAt);
            return this;
        }

    public WorkloadCommandResult build() {
            return new WorkloadCommandResult(commandId, machineId, status, sanitizedEvidence, evidenceDigest, completedAt);
        }
    }
}
