// GENERATED by scripts/generate-metamodel.sh from metamodel/jumo-v1.yaml -- do not edit. Edit the LinkML source and regenerate.
package dev.jumo.model;


import java.util.Objects;


public record WorkerModelAccess(AccessMode mode, ContractReference providerAccountRef, CredentialSource credentialSource, String gatewayRef, ContractReference secretBindingRef)  {

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private AccessMode mode = null;
        private ContractReference providerAccountRef = null;
        private CredentialSource credentialSource = null;
        private String gatewayRef = "";
        private ContractReference secretBindingRef = null;


        public Builder mode(AccessMode mode) {
            this.mode = Objects.requireNonNull(mode);
            return this;
        }

        public Builder providerAccountRef(ContractReference providerAccountRef) {
            this.providerAccountRef = Objects.requireNonNull(providerAccountRef);
            return this;
        }

        public Builder credentialSource(CredentialSource credentialSource) {
            this.credentialSource = Objects.requireNonNull(credentialSource);
            return this;
        }

        public Builder gatewayRef(String gatewayRef) {
            this.gatewayRef = Objects.requireNonNull(gatewayRef);
            return this;
        }

        public Builder secretBindingRef(ContractReference secretBindingRef) {
            this.secretBindingRef = Objects.requireNonNull(secretBindingRef);
            return this;
        }

    public WorkerModelAccess build() {
            return new WorkerModelAccess(mode, providerAccountRef, credentialSource, gatewayRef, secretBindingRef);
        }
    }
}
